# id 940011150 (Eastern Region of Pantheon : East Sanctum), field 940011150
sm.lockInGameUI(True, True)
sm.forcedInput(0)
sm.forcedInput(1)
sm.sendDelay(60)
sm.forcedInput(0)
sm.sendDelay(300)
sm.showEffect("Effect/Direction10.img/effect/tuto/BalloonMsg1/4", 900, 0, -120, 0, 0, 0, 0)
sm.sendDelay(150)
sm.forcedInput(2)
sm.sendDelay(60)
sm.forcedInput(1)
sm.sendDelay(60)
sm.forcedInput(2)
sm.sendDelay(90)
sm.forcedInput(1)
sm.sendDelay(60)
sm.forcedInput(0)
sm.sendDelay(510)
sm.showEffect("Effect/Direction10.img/effect/tuto/BalloonMsg1/9", 900, 0, -120, 0, 0, 0, 0)
sm.sendDelay(900)
sm.setSpeakerType(3)
sm.setSpeakerID(3000132) # Eskalade
sm.setParam(1)
sm.sendNext("Mwahahaha, how's THAT for power?!")
sm.setParam(17)
sm.sendSay("That was so much fun! It was all PEW PEW KABLOOOM!!")
sm.setParam(1)
sm.sendSay("Uh, yes. Yes it was sort of like that, only a lot less stupid.")
sm.setParam(17)
sm.sendSay("Hehehe, hahahaha, HAHAHAHAHA!")
sm.setParam(1)
sm.sendSay("You didn't hear a single word I said, did you? HEY! Enough with the terrifying laughter. You need some practice to use my powers properly.")
sm.setParam(17)
sm.sendSay("Awww, practice? I don't wannnaaaa....")
sm.setParam(1)
sm.sendSay("My powers require a transformation to really be effective. I think you should give it a shot. ")
sm.setParam(17)
sm.sendSay("Oh, okay!")
sm.setParam(1)
sm.sendSay("Hehehe... Ahem, then look deep into your heart, feel my presence, and say REALLY loud... Dress-Up!")
sm.setParam(17)
sm.sendSay("Dress-Up?")
sm.lockInGameUI(False, True)
sm.warp(940012020)
