# id 940011110 (Eastern Region of Pantheon : East Sanctum), field 940011110
sm.lockInGameUI(True, True)
sm.forcedInput(0)
sm.forcedInput(2)
sm.sendDelay(60)
sm.forcedInput(0)
sm.showEffect("Effect/Direction10.img/effect/tuto/BalloonMsg1/2", 1200, 0, -120, 0, 0, 0, 0)
sm.sendDelay(1200)
sm.setSpeakerType(3)
sm.setSpeakerID(3000132) # Eskalade
sm.setParam(1)
sm.sendNext("Holy moly, you look amazing! Look at those legs! And that hair! And your-- why are you looking at me like that?")
sm.setParam(17)
sm.sendSay("W-what am I wearing?! Where are my pants?!")
sm.spawnNpc(3000119, 150, 220)
sm.showNpcSpecialActionByTemplateId(3000119, "summon", 0)
sm.sendDelay(90)
sm.spawnNpc(3000115, 250, 220)
sm.showNpcSpecialActionByTemplateId(3000115, "summon", 0)
sm.sendDelay(90)
sm.spawnNpc(3000111, 350, 220)
sm.showNpcSpecialActionByTemplateId(3000111, "summon", 0)
sm.sendDelay(90)
sm.setSpeakerID(3000119) # Nefarious Priest
sm.setParam(1)
sm.sendNext("There! That girl has the relic on her arm!")
sm.setSpeakerID(3000115) # Nefarious Priest
sm.sendSay("Do we really need to hurt a pretty little thing like her? The relic is out of the Sanctum, it won't cause us any trouble.")
sm.setSpeakerID(3000119) # Nefarious Priest
sm.sendSay("Don't be stupid! We can't let some little bimbo take credit for our actions!")
sm.setSpeakerID(3000111) # Nefarious Priest
sm.sendSay("I-I'm sorry, um, ma'am, but would you please give me that relic?")
sm.setParam(17)
sm.sendSay("You're one of those creeps I saw before!")
sm.setParam(1)
sm.sendSay("Well, I wouldn't say 'creep' so much as liberator. Look, maybe you can give me that beautiful bracelet of yours for a bit and I can take you out for dinner...")
sm.setParam(17)
sm.sendSay("No way, you old weirdo! I can't even get this thing off of my arm.")
sm.setSpeakerID(3000119) # Nefarious Priest
sm.setParam(1)
sm.sendSay("Would you stop flirting?! Just grab the bimbo and we'll get out of here!")
sm.setSpeakerID(3000132) # Eskalade
sm.sendSay("#h0#! Now would be a good time to kick the tar out of them.")
sm.setParam(17)
sm.sendSay("H-how do I do that?!")
sm.showEffect("Effect/Direction10.img/effect/tuto/BalloonMsg1/3", 900, 30, -70, 0, 0, 0, 0)
sm.sendDelay(900)
sm.setSpeakerID(3000119) # Nefarious Priest
sm.setParam(1)
sm.sendNext("What mad devilry is going on inside that lovely little head of yours? Come now! Let's go!")
sm.sendDelay(300)
sm.showFieldEffect("lightning/screenMsg/0", 0)
sm.lockInGameUI(False, True)
sm.warp(940011150)
