# id 450007000 (Esfera : Living Spring), field 450007000
if not sm.hasQuest(34562) and not sm.hasQuestCompleted(34562):
    sm.lockInGameUI(True, False)
    sm.removeAdditionalEffect()
    sm.changeBGM("Bgm00.img/Silence", 0, 0)
    sm.sendDelay(300)
    sm.sendDelay(300)
    sm.forcedFlip(False)
    sm.sendDelay(1000)
    sm.playSound("Sound/SoundEff.img/blackHeaven/explosion5", 5000)
    sm.sendDelay(5000)
    sm.playSound("Sound/SoundEff.img/esfera/waterdrop", 3000)
    sm.sendDelay(1200)
    sm.sendDelay(1400)
    sm.setSpeakerType(3)
    sm.setParam(57)
    sm.setColor(1)
    sm.sendNext("Are you okay?")
    sm.setParam(37)
    sm.setInnerOverrideSpeakerTemplateID(3003500) # Ollie
    sm.sendSay("#face1#Ooh... Yeah, I guess so. I mean, I'm alive. That's what counts, right?")
    sm.sendSay("#face1#Gee, I thought being a good swimmer would be helpful here. Doesn't seem like we're dealing with normal waters, though.")
    sm.setParam(57)
    sm.sendSay("I don't see the ship, Or Shubert. Or Melange. I wonder why we're the only ones that ended up here.")
    sm.setParam(37)
    sm.sendSay("#face2#I wonder what happened. Were we attacked? And if so, who was it?")
    sm.setParam(57)
    sm.sendSay("I don't know, but I've got a feeling someone sinister's behind this.")
    sm.sendSay("And if they're linked to that #rblack orb in the sky#k in any way, I know who it is.")
    sm.changeBGM("Bgm26.img/DarkMage", 0, 0)
    sm.zoomCamera(2000, 1500, 0, 32, -750)
    sm.sendDelay(3000)
    sm.sendNext("The Black Mage.")
    sm.setParam(37)
    sm.sendSay("#face2#The Black Mage?! Do you really think he's here? ")
    sm.sendSay("#face3#Wow... If that's the case, maybe the final reckoning really is coming.")
    sm.setParam(57)
    sm.sendSay("Yeah... ")
    sm.sendSay("If we hadn't been dumped here... ")
    sm.sendSay("If we had kept on towards the black orb.... Maybe we would be facing him right now.")
    sm.sendDelay(2000)
    sm.sendNext("#fc0xFFAAAAAA#(The Black Mage... Feels like this long struggle is finally coming to an end.)")
    sm.createQuestWithQRValue(34562, "enter=fin")
    sm.sendDelay(2000)
    sm.bgmVolume(0, 3000)
    sm.sendDelay(3000)
    sm.moveCamera(True, 0, 0, 0)
    sm.sendDelay(300)
    sm.removeOverlapScreen(1000)
    sm.changeBGM("Bgm49/SoupOfLife", 0, 0)
    sm.sendDelay(200)
    sm.bgmVolume(100, 0)
    sm.lockInGameUI(False, True)
