# id 993185000 (Sellas : Somewhere in Sellas), field 993185000
sm.lockInGameUI(True, False)
sm.removeAdditionalEffect()
sm.blind(True, 255, 0, 0, 0, 0)
sm.hideUser(True)
sm.sendDelay(2000)
sm.onLayer(0, "BlackOut", 0, 0, 2000000, "Map/Effect2.img/BlackOut", 4, True, 0, True)
sm.spineScreen(False, True, False, 0, "Effect/Direction25.img/Sellas/whale/skeleton","1","3500")
sm.sendDelay(2000)
sm.sayMonologue("So many things disappeared that day. ", 1)
sm.sendDelay(3000)
sm.changeBGM("Bgm55/SinkingThings", 0, 0)
sm.sendDelay(4000)
sm.offLayer(3500, "BlackOut", False)
sm.sendDelay(6500)
sm.sayMonologue("Ships. Cargo. People...", 0)
sm.sayMonologue("So many dreams, all sinking into the dark.", 1)
sm.sendDelay(3500)
sm.sayMonologue("Now, after all this time...", 0)
sm.sayMonologue("Even my memories of that day are disappearing, bit by bit.", 1)
sm.sendDelay(2000)
sm.sayMonologue("But there's one thing I'll never forget.", 1)
sm.sendDelay(3500)
sm.spineScreen(False, False, False, 0, "Effect/Direction25.img/Sellas/whale/skeleton","2","02")
sm.sendDelay(8000)
sm.sayMonologue("Those eyes...", 1)
sm.sendDelay(3000)
sm.sayMonologue("Staring down at all our petty little tragedies.", 0)
sm.sayMonologue("There was no rage in those eyes. No pity, no compassion...", 0)
sm.sayMonologue("No emotions at all.", 1)
sm.sendDelay(3500)
sm.sayMonologue("Only the eyes, watching in terrible silence...", 1)
sm.sendDelay(3500)
sm.onLayer(3000, "BlackOut2", 0, 0, 2000000, "Map/Effect2.img/BlackOut", 4, True, 0, True)
sm.sendDelay(4000)
sm.blind(True, 255, 0, 0, 0, 1000)
sm.sendDelay(1300)
sm.lockInGameUI(False, True)
sm.warp(993185001)
