# id 940204008 (Morass : Somewhere in Morass), field 940204008
sm.lockInGameUI(True, False)
sm.removeAdditionalEffect()
sm.blind(True, 255, 0, 0, 0, 0)
sm.changeBGM("Bgm00.img/Silence", 0, 0)
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(3003409) # Flying Fish
sm.sendNext("#face0#The escape failed in the end.")
sm.setParam(57)
sm.sendSay("How?")
sm.setParam(37)
sm.sendSay("#face0#It triggered the fall of Kritias.")
sm.setParam(57)
sm.sendSay("But that means I have to...")
sm.setParam(37)
sm.sendSay("#face0#Help Jean #bsuccessfully escape#k. Change the story. It's the only way to draw out Tana's consciousness. \r\nAnd... oh...")
sm.setParam(57)
sm.sendSay("What's wrong?")
sm.setParam(37)
sm.sendSay("#face0#It's time. Soon, I too will become trapped in the morass of Tana's memory.")
sm.setParam(57)
sm.sendSay("What? But you won't be able to talk anymore!")
sm.setParam(37)
sm.sendSay("#face0#If you ever want to escape, you must complete this task.")
sm.setParam(57)
sm.sendSay("Wait! I need more to go on than that!")
sm.setParam(37)
sm.sendSay("#face0#Don't worry. In this place,\r\nthere's always #banother chance#k... \r\nalways a#b backup plan.#k")
sm.setParam(57)
sm.sendSay("What? How do you know for sure? Hey! Flying Fish! Wait!")
sm.zoomCamera(0, 512000, 0, -81920, 71935)
sm.spawnNpc(3003406, -240, 226)
sm.showNpcSpecialActionByTemplateId(3003406, "summon", 0)
sm.sendDelay(4000)
sm.createFieldTextEffect("#fnﾳﾪﾴﾮﾰ￭ﾵ￱ ExtraBold##fs18#Hekatonian Year 54, Trueffet, Abandoned Area", 100, 2200, 6, -50, -50, 1, 4, 0, 0, 0)
sm.blind(True, 255, 0, 0, 0, 0)
sm.sendDelay(1200)
sm.blind(False, 0, 0, 0, 0, 1000)
sm.sendDelay(1400)
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(3003406) # Jean
sm.sendNext("#face13#Hmm... Why did you want to meet me here again?")
sm.setParam(57)
sm.sendSay("You're not suspicious of me, are you?")
sm.setParam(37)
sm.sendSay("#face13#Suspicious? Me? No.")
sm.setParam(57)
sm.sendSay("Be careful. It's dangerous this late at night.")
sm.setParam(37)
sm.sendSay("#face11#Hmph! I am Jean the thief, master of darkness. I'm the last person you need to worry about.")
sm.moveNpcByTemplateId(3003406, True, 10, 150)
sm.sendDelay(200)
sm.sendDelay(500)
sm.sendNext("#face1#Ah!")
sm.setParam(57)
sm.sendSay("I told you to be careful. Look, I'm helping you, because the whole of Kritias is at stake if the King's Ascendancy goes wrong.")
sm.setParam(37)
sm.sendSay("#face8#Hmm... take it from a thief. Nobody helps anybody for no reason at all.\r\nAnd anyway, Tana is special. This is really important.")
sm.setParam(57)
sm.sendSay("Don't you think I already know that?")
sm.setParam(37)
sm.sendSay("#face6#You don't understand. It's more than Kritias at stake.")
sm.setParam(57)
sm.sendSay("...What?")
sm.setParam(37)
sm.sendSay("#face0#Look, I have a special gift for her, but somehow I managed to lose it. Could you help me find it first?")
sm.setParam(57)
sm.sendSay("#fs18#I thought you were preparing to escape!")
sm.sendSay("#b(Hm, the journal is glowing again. Has another entry appeared in it? Better take a look.)#k")
sm.lockInGameUI(False, True)
sm.warp(450006300)
