# id 865090003 (null), field 865090003
sm.lockInGameUI(True, False)
sm.hideUser(True)
sm.sendDelay(3000)
sm.createFieldTextEffect("#fnﾳﾪﾴﾮﾰ￭ﾵ￱ ExtraBold##fs26#That Evening", 100, 2500, 4, 0, 0, 1, 4, 0, 0, 0)
sm.onLayer(3000, "0", 0, 0, 0, "Map/EffectBT.img/dawnveil1/storm", 4, True, -1, False)
sm.sendDelay(1000)
sm.playSound("Sound/SoundEff.img/thunder3", 100)
sm.sendDelay(1000)
sm.playSound("Sound/SoundEff.img/thunder2", 100)
sm.sendDelay(2000)
sm.playSound("Sound/SoundEff.img/thunder", 100)
sm.setSpeakerType(3)
sm.setParam(57)
sm.setColor(1)
sm.sendNext("Whoa, whoa, whoa! Mr. Great Explorer, sir! What's going on!?")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9390200) # Parbell
sm.sendSay("Well yuh sure weren't burdened with an over-abundance o' brains, now were yuhs? This right here is what we call a storm. Hold on to something so yuhs don't get gobbled up by the waves!")
sm.setParam(57)
sm.sendSay("(A 'safe and cozy' trip, my foot! I'll get you for this, Neinheart!)")
sm.sendSay("Aaaaaaaaaah! Mr. Parbell! #eThe ship's going to be torn apart!#n")
sm.setParam(37)
sm.sendSay("Dagnabbit! The mast looks like it's 'bout to give way! But we's so close to Commerci... Hey, greenhorn! What're yuh doin' layin' about at a time like this'un!")
sm.setParam(57)
sm.sendSay("#b(...You passed out, just like that.)#k")
sm.offLayer(3000, "0", False)
sm.hideUser(False)
sm.lockInGameUI(False, True)
sm.warp(865010200)
