#   [Job Adv] (5th job)   5th Job : Arcane stone of Tynerium

sm.setSpeakerID(1540944)
sm.sendNext("如果说冒险岛世界是井然有序的，那绯红就是混乱、充满未知的。我们从很久前开始就充当着这个世界的影子。")
sm.sendNext("其实，我并不想帮助冒险岛世界。不过，如果冒险岛世界消失，我们的世界也会受到威胁。就算是为我们自己考虑，我们也要尽全力阻止黑魔法师。")
sm.setPlayerAsSpeaker()
sm.sendNext("那你愿意帮忙喽？")
sm.setSpeakerID(1540944)
sm.sendNext("嗯？我好像没那么说吧？")
sm.setPlayerAsSpeaker()
sm.sendNext("我知道了。你不要露出这种表情。我帮你不就行了嘛。不过，在此之前，我想进行简单的测试！\r\n\r\n#L0#测试？")
sm.setSpeakerID(1540944)
sm.sendNext("嗯，是非常简单的运气测试。我会把你赶走，你只要重新回来就行了。不过，入口将会被转移到其他地方，而不是原来的地方。\r\n\r\n#L0#等等，怎么能这样……")
sm.setPlayerAsSpeaker()
sm.sendNext("我不会等你太久的，让我看看你的运气吧。\r\n\r\n#b(5分钟内，在世界树上端找到传送口吧！)#k")
sm.setSpeakerID(1540944)
sm.sendNext("All right, all right, don't look at me like that. I'll help you. But I want to test you first. \r\n\r\n #L0#What test? #l")
sm.sendNext("It's a simple test to see how lucky you are. I'm going to send you out of this place. You'll have to come back, but the entrance to this place will have been moved someplace else. \r\n\r\n #L1# Wait, that's unfair?#l")
sm.sendNext("I'm not going to wait for you long. Prove to me how lucky you are. \r\n\r\n #b(Find a Horizon Portal near the upper side of the World Tree within 5 minutes.)")
sm.sendNext("This is what you want, right? I was going to give it to you from the start. Hurry, take it. \r\n\r\n #v2435736# #bArcane Stone of Tynerum x1")
sm.startQuest(parentID)
sm.completeQuest(parentID)#todo
sm.dispose()