# id 17679 ([Commerci Republic] Red Tide), field 865010011
sm.setSpeakerID(9390246) # Captain Blood
sm.setParam(56)
sm.setColor(1)
sm.sendNext("现在我就让你们这些家伙的海盗行为到达截止日期。")
sm.setParam(32)
sm.sendSay("嗯？见过这么脑袋不灵光的朋友吗。看来你还不太明白你现在的处境啊。")
sm.setParam(56)
sm.sendSay("才不呢，我可是非常清楚呢。我要抓的家伙们全部聚集在这里，反而是我们要说声谢谢呢。")
sm.setParam(32)
sm.sendSay("哼，真是个趾高气昂的家伙。我就等着看你能装得意装到什么时候。")
sm.setParam(56)
res = sm.sendAskYesNo("(话是那么说，可是该怎么办呢。现在就立马攻击吗？")
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.closeUI(1128)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.createQuestWithQRValue(18418, "B=33273")
