# id 17645 ([Commerci Republic] Close Up with Captain Blood), field 865010001
sm.setSpeakerID(9390209) # Captain Blood
sm.sendNext("呜哦！岂有此理，这么厉害的家伙我真是很久没遇到了！")
sm.setParam(2)
sm.sendSay("彼此彼此。果然是和海盗小毛头有些不一样啊。")
sm.setParam(0)
sm.sendSay("你打算搞什么鬼。不管你做什么现在对你来说都毫无胜算了。")
sm.setParam(2)
sm.sendSay("来吧，还是乖乖地束手就擒吧。")
sm.setParam(4)
sm.setInnerOverrideSpeakerTemplateID(9390235) # Leon Daniella
sm.sendSay("你知道我是怎么坐上海盗王之位的吗。")
sm.setParam(0)
sm.sendSay("现在说那些有什么用。")
sm.setParam(2)
sm.sendSay("比其他海盗佣兵技术更好？射击技术更高？都不是的。我能成为海盗王是因为……")
sm.setParam(0)
sm.sendSay("我对情况判断和我的腿脚比较快而已。")
sm.sendSay("呼。但是还没结束呢。")
sm.completeQuestNoCheck(parentID)
sm.createQuestWithQRValue(18418, "B=33271")
