# id 17678 ([Commerci Republic] Ship of Blood), field 865010001
sm.setSpeakerID(9390244) # Leon Daniella
sm.sendNext("怎，怎么回事。瞬间消失了。去哪儿啦？")
sm.setParam(2)
sm.sendSay("莱文看那里！")
sm.setParam(0)
sm.sendSay("不知何时已经回到了自己的舰船上去了嘛。岂有此理！到嘴的鸭子飞了！！")
sm.setParam(2)
sm.sendSay("怎么办呢？就这么放弃太可惜了，但是对方可是被称为海盗王的男人啊。随便进入敌人的根据地会……")
sm.setParam(0)
sm.sendSay("我也知道。可是到目前为止见过无数的普赛依远征队。但一次也没有成功过。现在这是我们走运。如果现在放弃的话说不定就再也没可能了。")
res = sm.sendAskYesNo("这也许是普赛依布下的陷阱。你不和我一起去也没关系。但是我要去。为了我，为了我们的商团，为了凯梅尔兹！")
sm.setParam(2)
sm.sendNext("嗯……那么好吧。我也和你一块去。")
sm.setParam(0)
sm.sendSay("真的吗？也许可能就像你说的那样是陷阱呢。")
sm.setParam(2)
sm.sendSay("啊哎，没关系。我自己会想办法逃出来的。")
sm.setParam(4)
sm.setInnerOverrideSpeakerTemplateID(9390204) # Robed Lady
sm.sendSay("我也一起去吧？")
sm.setParam(0)
sm.sendSay("你就别去了。你留下来守好这条船。")
sm.sendSay("好了，#h0#走吧！我来开条活路！")
sm.setParam(2)
sm.sendSay("等会，你在这儿等着。那地方我要一个人去。")
sm.setParam(0)
sm.sendSay("你说什么呢。你一个人去置身死地，让我装作视而不见吗？")
sm.setParam(2)
sm.sendSay("我说莱文。你现在是这船的舰长。舰长如果离开了这船万一发生什么事的话可怎么办。我们必须得顾虑到万一若是发生不测的情况啊。")
sm.setParam(0)
sm.sendSay("虽说是那样……可是也……")
sm.setParam(2)
sm.sendSay("作为舰长你必须守住船。")
sm.setParam(0)
sm.sendSay("……拜托你了。")
sm.startQuest(parentID)
