# id 17650 ([Commerci Republic] Troubling Reports), field 865000002
sm.setSpeakerID(9390203) # Gilberto Daniella
sm.setParam(2)
sm.sendNext("首领大人，海盗讨伐队现在归航了。")
sm.setParam(0)
sm.sendSay("快来。看到你没事我可真高兴。看你的表情，任务很好地完成了啊。我说的对吧？")
sm.setParam(2)
sm.sendSay("是的，你说对了。有了莱文的卓越指挥我们比想象中更轻松地击退了敌人。")
sm.setParam(0)
sm.sendSay("嗯，那真是万幸。多亏了你们，现在海上交易也会进一步好转了。")
sm.setParam(2)
sm.sendSay("首领大人你的脸色不太好，是因为海本王国的原因吗？")
sm.setParam(0)
sm.sendSay("你听说了吗？你不提我还正在为那个头疼呢。我真是琢磨不出这又会出什么事儿。")
sm.completeQuestNoCheck(parentID)
sm.createQuestWithQRValue(18418, "B=33280")
