# id 17642 ([Commerci Republic] A Fickle Man), field 865010001
sm.setSpeakerID(9390244) # Leon Daniella
sm.sendNext("好了，赶紧动起来吧。没时间了。就现在这一刻说不定普赛依又在袭击某条商船了。")
sm.setParam(2)
sm.sendSay("欢迎你。第一次来到我们船上吧？虽然是用商船改造的船，但是样子还是有些变了吧。不过说到底还是艘商船而已。")
sm.setParam(0)
sm.sendSay("可是你有什么事吗？有什么要办的事情吗？")
res = sm.sendAskYesNo("我还没来得及跟你说，这位是要搭乘这船的人。所以尽管迟了但是还是应该跟你说一声才是")
sm.startQuest(parentID)
sm.setParam(2)
sm.sendNext("你在说什么呀？谁要乘船？")
sm.setParam(0)
sm.sendSay("啊……其实我也不知道她名字呢。可是你应该认识她的。她的实力好像也还行。")
sm.setParam(2)
sm.sendSay("你说什么？你现在让一个连名字都不知道的人随便搭乘我们船吗？实力不是重要的。重要的是航海不是开玩笑的。")
sm.setParam(0)
sm.sendSay("喂，莱文。")
