# id 17667 ([Commerci Republic] Plans from Heaven), field 865030111
sm.setSpeakerID(9390238) # Zion
sm.setParam(32)
sm.setColor(1)
sm.sendNext("我当然知道吉，吉尔伯特大人会拒绝和平条约的。")
sm.setParam(56)
sm.sendSay("原来是有计划的行动啊。如果那样的话，明知道会被拒绝还来提议的理由是什么呢？")
sm.setParam(32)
sm.sendSay("好的，如，如果拒绝了王国的和约后，愤怒的凯梅尔兹首领杀死了海本王国的使节这样的消息传开了……")
sm.setParam(36)
sm.setInnerOverrideSpeakerTemplateID(9390202) # Leon Daniella
sm.sendSay("周围的所有势力都会孤立凯梅尔兹共和国的。")
sm.setParam(32)
sm.sendSay("就，就是那样。")
sm.setParam(56)
sm.sendSay("好的，你得把这事实在首领面前再完完整整地重复一遍。")
sm.setParam(32)
sm.sendSay("当，当然了。")
sm.setParam(36)
sm.sendSay("AND, we get to have your stuff.")
sm.setParam(32)
sm.sendSay("T-that's...!")
sm.setParam(36)
sm.sendSay("What? Mine? You're right. It IS mine now. Unless you want mr. mustache to meet the tweezers... ")
sm.setParam(32)
sm.sendSay("N-no. I was going to say... that's m-my gift... to you!")
sm.setParam(36)
sm.sendSay("Oh, really? Thanks man, that's super nice. I kinda feel bad now.")
sm.sendSay("Hey #h0#, you should use this.")
sm.completeQuestNoCheck(parentID)
sm.createQuestWithQRValue(18418, "B=33299")
