# id 17676 ([Commerci Republic] Her Circumstances), field 865000000
sm.setSpeakerID(9390240) # Claire Tremier
sm.setParam(56)
sm.setColor(1)
sm.sendNext("这会儿马上父亲准备好就要离开了。")
sm.setParam(32)
sm.sendSay("看来班·特来敏大人要一起去了？")
sm.setParam(56)
sm.sendSay("是的。他好像担心说不定又中途在哪消失了似的。")
sm.setParam(32)
sm.sendSay("原来如此。那也别放弃自己的梦想。成为大魔法师的梦想。")
sm.setParam(56)
sm.sendSay("谢谢你。有空的时候我自己会继续筹集资本……不是，是学习。")
sm.setParam(32)
sm.sendSay("(这姑娘，如此的话又该离家出走了。)")
sm.setParam(56)
sm.sendSay("你没什么话要我转告莱文吗？现在离开的话想见面可就难了。")
sm.sendSay("嗯？应该是那样吧。我也没什么要说的呢。")
sm.setParam(32)
sm.sendSay("…………？？？你会想他都没关系吗？")
sm.setParam(56)
sm.sendSay("啊？为什么？啊，当然也不会完全不想他啦。")
sm.setParam(32)
sm.sendSay("原，原来如此。(莱，莱文你这家伙……呵呵)")
sm.setParam(56)
sm.sendSay("啊，那么能请你把这个转交给他吗？")
sm.setParam(32)
res = sm.sendAskYesNo("知道了。我会转交给他的。")
sm.startQuest(parentID)
sm.setParam(56)
sm.sendNext("我尝试着做的。那就拜托你了。")
sm.setParam(32)
sm.sendSay("克莱尔何时离开呢。")
