# id 17651 ([Commerci Republic] A Funny Kind of Peace), field 865000002
sm.setSpeakerID(9390207) # Zion
sm.setParam(32)
sm.setColor(1)
sm.sendNext("好的，您既然先开口提了，我也就直言相告了。")
sm.sendSay("首先，凯梅尔兹共和国在和与海本王国建交的其他国家进行贸易时，只能交易我国指定的品目，并且我国要收取售价的1%作为酬金。")
sm.setParam(56)
sm.sendSay("你说什么？那是什么！！")
sm.setParam(36)
sm.setInnerOverrideSpeakerTemplateID(9390203) # Gilberto Daniella
sm.sendSay("等会，先听完他说的。请继续。")
sm.setParam(32)
sm.sendSay("好的，第二点是，和我们海本交易时，有关交易包含的所有项目都必须由我们管理。")
sm.sendSay("第三，现在贵国使用的航线实际上是在海本王国的管辖下，希望你们能够支付航线使用的费用。")
sm.sendSay("第四。两国从今以后绝不相互猜忌并坚信两国之间的友谊深厚。因此我们为了向凯梅尔兹共和国表达我们的诚意，我们将提供给能代表凯梅尔兹的首领亲属作为贵宾到我国留学的机会，可以花10年来学习我们的先进技术。")
sm.sendSay("我说完了。您意下如何？")
sm.setParam(36)
sm.sendSay("呃嗯…… ")
sm.showNpcSpecialActionByTemplateId(9390236, "summon", 0)
sm.setInnerOverrideSpeakerTemplateID(9390202) # Leon Daniella
sm.sendSay("这是什么无厘头的话啊！！")
sm.setParam(32)
sm.sendSay("嗯？这位是……？")
sm.setParam(36)
sm.sendSay("我是凯梅尔兹共和国首领吉尔伯特·达尼尔拉的二儿子莱文·达尼尔拉！")
sm.setParam(32)
sm.sendSay("见到你真的非常荣幸。关于莱文大人的传闻我已是耳熟能详了。优秀的船长……")
sm.setParam(36)
sm.sendSay("吵死了！你胆敢在那里玩花招啊！")
sm.setParam(32)
sm.sendSay("耍花招，您这话说得太过分了吧。我是为了促进两国之间的和平而来的。")
sm.setParam(36)
sm.sendSay("和平？哈！让我们成为你们这些家伙的附属国就是你所指的和平吗！再不赶紧给我滚出去的话，我就让你尝尝凯梅尔兹的厉害！")
sm.setParam(32)
sm.sendSay("这这……可不能这样啊。吉尔伯特首领。今天我们就先告辞了。明天再来拜见您。那时希望能听到您的答复。希望您会给我一个肯定的回答。")
sm.setParam(36)
sm.sendSay("哼，放肆的家伙。首领大人，我还有事没有处理完先告辞了。")
sm.completeQuestNoCheck(parentID)
sm.createQuestWithQRValue(18418, "B=33281")
