# id 17675 ([Commerci Republic] His Circumstances), field 865000000
sm.setSpeakerID(9390240) # Claire Tremier
sm.setParam(56)
sm.setColor(1)
sm.sendNext("是#h0#。如此看来我还没介绍过我的名字呢。")
sm.setParam(32)
sm.sendSay("啊，是的，#h0#。有什么事吗？找我有事吗？")
sm.setParam(56)
sm.sendSay("啊，这是莱文让我转交给你的。")
sm.setParam(32)
sm.sendSay("啊，好的。谢谢你了。辛苦你了。")
sm.setParam(56)
sm.sendSay("克莱尔，请稍等。")
sm.setParam(32)
sm.sendSay("嗯？啊…那……")
sm.completeQuestNoCheck(parentID)
sm.createQuestWithQRValue(18418, "B=33308")
