# id 17641 ([Commerci Republic] Robed Adventures), field 865000000
sm.setSpeakerID(9390204) # Robed Lady
sm.setParam(32)
sm.setColor(1)
sm.sendNext("你在这儿干嘛呢？")
sm.setParam(56)
sm.sendSay("啊，你说过是要讨伐海盗还是什么的对吧。")
sm.setParam(32)
sm.sendSay("可是你能做到吗？看上去佣兵人数也不多，而且没个能值得信赖的人……")
sm.setParam(56)
sm.sendSay("…………走吧。")
sm.setParam(32)
sm.sendSay("哎？走吧？走去哪儿？")
sm.setParam(56)
sm.sendSay("都到这时候了你就直接说吧。想一起去。")
sm.setParam(32)
sm.sendSay("…………虽然我是个大忙人，但是你坚持需要帮助的话，我就答应你吧。走吧。")
sm.setParam(56)
sm.sendSay("…………这女孩到底干嘛的呀。可是……我随便接收下来没问题吗。让她跟莱文说一声他会看着办的吧。")
sm.setParam(32)
sm.sendSay("...Well, I'm a VERY busy woman, but if you REALLY need my help, I'll go.")
sm.setParam(56)
sm.sendSay("...Strange lady. I hope she doesn't cause trouble. I'll just talk to Leon later.")
sm.completeQuestNoCheck(parentID)
sm.warp(865010001)
