# id 17670 ([Commerci Republic] Ominous Feeling), field 865030300
sm.setSpeakerID(9390236) # Leon Daniella
sm.sendNext("特来敏小姐。是这个结界吗？")
sm.setParam(4)
sm.setInnerOverrideSpeakerTemplateID(9390205) # Claire Tremier
sm.sendSay("应该就是这里。从这儿能感觉到强烈的不好的气息。")
sm.setParam(0)
res = sm.sendAskYesNo("嗯…… 原来如此。进去看看吧。#h0#，赶紧进去调查调查吧")
sm.startQuest(parentID)
sm.setParam(2)
sm.sendNext("好吧。但是就我一个人进去。你留在这里。")
sm.setParam(0)
sm.sendSay("嗯？你干嘛要一个人进去啊？")
sm.setParam(2)
sm.sendSay("谁知道里面有什么。而且你一起进去的话我不放心克莱尔的安全。")
sm.setParam(0)
sm.sendSay("嗯。好吧，知道了。但是如果发生什么事的话，你不要逞强马上出来。")
sm.setParam(2)
sm.sendSay("嗯，知道了。好了，那我进去喽。")
sm.warp(865030400)
