# id 17658 ([Commerci Republic] Claire's Story), field 865030000
sm.setSpeakerID(9390205) # Claire Tremier
sm.setParam(32)
sm.setColor(1)
sm.sendNext("我需要谢谢你肯听我说吗？你们还记得我是救过你们的恩人吗？")
sm.setParam(56)
sm.sendSay("关于那点是要谢谢你。但是知道你是班·特来敏的女儿之后不得不与你划清界线也是事实。")
sm.setParam(32)
res = sm.sendAskYesNo("也对。那也不是不能理解的。那我就说明一下吧。现在要听吗？")
sm.startQuest(parentID)
sm.sendNext("刚才也说了我是班·特来敏的独生女。母亲呢在生我的时候就去世了。所以父亲非常宝贝地养育了我。")
sm.setParam(56)
sm.sendSay("你生得金贵，为什么这么遮头盖脸地过日子？")
sm.setParam(32)
sm.sendSay("嗯…… 该从哪说起呢……")
