# id 17637 ([Commerci Republic] Deus Ex You), field 865000002
sm.setSpeakerID(9390262) # Leon Daniella
sm.sendNext("首领，交给我的话，我就去击退普赛依。")
sm.setParam(4)
sm.setInnerOverrideSpeakerTemplateID(9390203) # Gilberto Daniella
sm.sendSay("嗯？你吗？你和阿库旁多战斗回来都还没过多久呢")
sm.setParam(2)
sm.sendSay("(是的。说得对。)")
sm.setParam(0)
sm.sendSay("但是海上贸易不是我们最核心的最重要的部分嘛")
sm.setParam(4)
sm.sendSay("正因如此才更那个。当然你出色地阻挡了阿库旁多，但是普赛依跟阿库旁多小混混们可不一样。")
sm.setParam(2)
sm.sendSay("(对的。莱文还需要再修炼修炼……)")
sm.setParam(0)
sm.sendSay("可，可是……就是那样！我和#h0#一起去。#h0#的能力相当优秀一定能起到很大帮助的。")
sm.setParam(2)
sm.sendSay("(嗯？可是，这家伙干嘛连我也……！！)")
sm.setParam(4)
sm.sendSay("又想借他人之手吗！！像你这样的家伙终究是没有发展可能的！！每次期待你会有所表现的时候就立刻让我感到失望！！")
sm.setParam(2)
sm.sendSay("(呃，怎么又是这种情况……吉尔伯特首领的话也有他的道理，可是这对我来说也是一个机会。)")
sm.sendSay("首领，我和莱文一起去。")
sm.setParam(4)
sm.sendSay("上一次也是接受了你的帮助。这次要凭我们自己的力量来完成。")
sm.setParam(2)
sm.sendSay("上次我也说过了，虽然是友邦国家，但这次我作为莱文的朋友也想拜托你。")
sm.setParam(4)
sm.sendSay("嗯……如果这么说的话让我考虑考虑。")
sm.startQuest(parentID)
