# id 17647 ([Commerci Republic] The Fall of Captain Blood), field 865010001
sm.setSpeakerID(9390243) # Robed Lady
sm.setParam(32)
sm.setColor(1)
sm.sendNext("你到时候可不能反悔哦。好吧，那就退后吧。不想一起被卷走的话。")
sm.lockInGameUI(True, True)
sm.forcedInput(0)
sm.showFieldEffect("Map/EffectBT.img/dawnveil1/Cut3_1", 0)
sm.sendDelay(2000)
sm.showFieldEffect("Map/EffectBT.img/dawnveil1/Cut3_2", 0)
sm.playSound("Sound/SoundEff.img/thunder3", 100)
sm.sendDelay(2000)
sm.lockInGameUI(False, True)
sm.setParam(57)
sm.sendNext("还活着吗……")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9390235) # Leon Daniella
sm.sendSay("可，可能……恐怕不行了吧。")
sm.setParam(57)
sm.sendSay("不知怎么的有些同情他。")
sm.setParam(37)
sm.sendSay("你，报酬可不能少了我的啊。")
sm.setParam(57)
sm.sendSay("I almost feel bad for them now.")
sm.setParam(33)
sm.sendSay("Now, to discuss my payment.")
sm.completeQuestNoCheck(parentID)
sm.createQuestWithQRValue(18418, "B=33276")
