# id 17656 ([Commerci Republic] Dances with Wolves 1), field 865030000
sm.setSpeakerID(9390249) # Robed Lady
sm.sendNext("即使知道了我是谁好像也不能改变各位的处境啊。")
sm.setParam(2)
sm.sendSay("虽然是那样，但也得搞清楚是谁帮助了我们呀，不是吗。")
sm.setParam(4)
sm.setInnerOverrideSpeakerTemplateID(9390202) # Leon Daniella
sm.sendSay("那就这样吧。如果你告诉我你是谁，我给你双倍的谢礼。")
sm.setParam(0)
sm.sendSay("吼哦……那可真是很有吸引力哦。可是你现在有能力支付那笔金额吗？")
sm.setParam(4)
sm.sendSay("呃……其实现在眼前是有点困难……好像只能给你一半的金额。")
sm.setParam(0)
sm.sendSay("好吧。其实我是……")
sm.setParam(2)
res = sm.sendAskYesNo("等会！！我感到这附近有很重的杀气！是狼群！快做好准备！！")
sm.startQuest(parentID)
sm.setParam(4)
sm.sendNext("这里有狼群？？先赶紧消灭掉吧！得把女性的安全放在第一位！")
sm.startQuest(parentID)
sm.startQuest(16689)
sm.startQuest(parentID)
sm.startQuest(16689)
