# id 17669 ([Commerci Republic] Barricaded 2), field 865030300
sm.setSpeakerID(9390237) # Claire Tremier
sm.setParam(2)
sm.sendNext("赶紧一起回桑凯梅尔兹吧。")
sm.setParam(0)
sm.sendSay("请稍等。我感觉到了什么。")
sm.setParam(2)
sm.sendSay("感觉？你感觉到了什么啊？")
sm.setParam(0)
sm.sendSay("说不上来……虽然不知道是什么，但是是种不祥的感觉。")
sm.setParam(4)
sm.setInnerOverrideSpeakerTemplateID(9390202) # Leon Daniella
res = sm.sendAskYesNo("特来敏小姐说感觉到什么，我也好像有所感觉似的。#h0#我们稍微查看一下四周如何？")
sm.startQuest(parentID)
sm.setParam(2)
sm.sendNext("嗯，就看看吧。而且说是不祥的感觉，就这么走的话真是有点不踏实。克莱尔你是在哪儿感觉到的呢？")
sm.setParam(0)
sm.sendSay("好像就在这附近。其实从一开始我就感觉到了，那时还以为是因为西温和暗杀团员们的原因呢。")
sm.setParam(2)
sm.sendSay("那么就得以这为中心四周找找看看了。")
