# id 17653 ([Commerci Republic] Don't Even Ask), field 865000002
sm.setSpeakerID(9390203) # Gilberto Daniella
sm.sendNext("来啦。见到班·特来敏了吗？")
sm.setParam(2)
sm.sendSay("是的，见到了。可是……")
sm.setParam(0)
sm.sendSay("可是？")
sm.setParam(2)
sm.sendSay("那个……虽然我不知道书信的内容，但是其中的议事被断然地拒绝了。说全部都是首领的责任让您自己看着办……")
sm.setParam(0)
sm.sendSay("什么？那是我为了自己好才那样做的吗！！")
sm.setParam(2)
sm.sendSay("说商团的事务繁忙所以没法帮忙。")
sm.setParam(0)
sm.sendSay("他的意思是商团的事情比国家的事情更重要吗？呵呵，没看出来啊，真是可耻的人啊！其实那人一直盯着我的位子呢。果然拒绝帮忙。")
sm.sendSay("反正我知道了。辛苦你了。赶紧去休息吧。")
sm.completeQuestNoCheck(17740)
sm.createQuestWithQRValue(18418, "B=33283")
sm.createQuestWithQRValue(18418, "B=33284")
