# id 17647 ([Commerci Republic] The Fall of Captain Blood), field 865010001
sm.setSpeakerID(9390243) # Robed Lady
sm.sendNext("话说回来，那海盗该怎么办呢？")
sm.setParam(2)
sm.sendSay("海盗？啊……普赛依！！")
sm.setParam(4)
sm.setInnerOverrideSpeakerTemplateID(9390235) # Leon Daniella
sm.sendSay("普赛依那家伙在哪？因为深海巨妖的出现我都没心思顾及他了。")
sm.setParam(0)
sm.sendSay("像老鼠一样悄悄地逃跑了，往那边去了。")
sm.setParam(4)
sm.sendSay("怎么搞的，什么时候跑那么远去了！！赶紧去追吧！！")
sm.setParam(2)
sm.sendSay("那是不太可能。用商船追海盗船那是不可能的。")
sm.setParam(4)
sm.sendSay("就这样失之交臂了吗……几乎就要抓到他了。切。")
sm.setParam(0)
res = sm.sendAskYesNo("好像该轮到我登场的时候了吧。怎么样……要我帮忙吗？")
sm.startQuest(parentID)
sm.setParam(56)
sm.setColor(1)
sm.sendNext("你打算怎么办呢？你不会是打算游泳追过去吧")
sm.setParam(32)
sm.sendSay("怎么会有这么低俗的人啊。")
sm.setParam(56)
sm.sendSay("什么，你说什么……(这女人做什么都说是低俗……)")
sm.setParam(32)
sm.sendSay("怎么办呢？要不要我出马。当然你得给我适当的报酬。")
sm.setParam(36)
sm.sendSay("呃嗯……好吧，就拜托你了。")
