# id 17676 ([Commerci Republic] Her Circumstances), field 865000000
sm.setSpeakerID(9390256) # Leon Daniella
sm.setParam(32)
sm.setColor(1)
sm.sendNext("哟，你来啦。书信转交给她了吗？")
sm.setParam(56)
sm.sendSay("嗯。我亲手转交的。你放心。")
sm.setParam(32)
sm.sendSay("好吧，有什么反应呢？高兴吗？")
sm.setParam(56)
sm.sendSay("哦……嗯…那……当然啦……(莱文你真是的……) 啊，还有让我把这个交给你。")
sm.setParam(32)
sm.sendSay("这是什么？")
sm.setParam(56)
sm.sendSay("那我就不知道喽。你拆开来看看啊。")
sm.setParam(32)
sm.sendSay("哪呢……。啊，这是……？这是什么呢？")
sm.setParam(56)
sm.sendSay("好像是什么符似的。")
sm.setParam(32)
sm.sendSay("噢，看来是保佑平安的符咒！我要随身携带！")
sm.setParam(56)
sm.sendSay("好了，真是万幸。(就没必要告诉他是试验品而已了吧。希望那可千万别是诅咒，而得是祝福的符文。)")
sm.completeQuestNoCheck(parentID)
sm.createQuestWithQRValue(18418, "B=33309")
