# id 17673 ([Commerci Republic] Undeniable Proof), field 865000002
sm.setSpeakerID(9390203) # Gilberto Daniella
sm.sendNext("真是万幸。洗脱了嫌疑。")
sm.setParam(2)
sm.sendSay("是啊，真是万幸啊。我也就算了，害莱文你也一起受冤枉我心里真是过意不去呢。")
sm.setParam(0)
sm.sendSay("虽然现在才这么说毫无意义，但是其实我是一直相信你的。当然我儿子莱文就更不用说了。")
sm.setParam(2)
sm.sendSay("我理解的。身为共和国的首领也是无可奈何的事。")
sm.setParam(0)
res = sm.sendAskYesNo("关于海本使节团的事情你能再详细说说吗？")
sm.startQuest(parentID)
sm.setParam(2)
sm.sendNext("是，其实我们被捕前救出我们的人就是克莱尔·特来敏。")
sm.setParam(0)
sm.sendSay("那时使用那魔法的人就是克莱尔啊。")
sm.setParam(2)
sm.sendSay("是的，我们逃到了凯梅尔兹外围的大森林里，在那里克莱尔小姐被一伙人给绑架了。")
sm.setParam(0)
sm.sendSay("那绑匪们就是海本王国的暗杀团吗？")
sm.setParam(2)
sm.sendSay("虽然一直都是推测，但是应该是那样的。因为西温称之为自己的部下。")
sm.setParam(0)
sm.sendSay("嗯……但是也说不定是哪里雇来的暗杀公会的家伙们。反正西温死了就再也无从而知了。")
