# id 17643 ([Commerci Republic] Yar! Pirates!), field 865010001
sm.setSpeakerID(9390244) # Leon Daniella
sm.sendNext("怎么这么宁静。该不会是海盗们有所察觉撤退了吧。")
sm.setParam(2)
sm.sendSay("说不准哦。说不定会那样呢。但是才没过几天再等等看吧。")
sm.setParam(0)
res = sm.sendAskYesNo("嗯……就那样吧。你做好了随时和海盗交战的准备吗？")
sm.startQuest(parentID)
sm.setParam(5)
sm.setInnerOverrideSpeakerTemplateID(9390217) # Tepes
sm.sendNext("是海盗！！海盗出现了！！")
sm.setParam(1)
sm.sendSay("终于上钩了！！")
sm.setParam(5)
sm.sendSay("海盗们朝我们商船过来了！！")
sm.setParam(1)
sm.sendSay("去吧！#h0# ！！")
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
