# id 17637 ([Commerci Republic] Deus Ex You), field 865000002
sm.setSpeakerID(9390203) # Gilberto Daniella
sm.sendNext("好吧，希望这次你也能助我们一臂之力。")
sm.setParam(4)
sm.setInnerOverrideSpeakerTemplateID(9390202) # Leon Daniella
sm.sendSay("谢谢。首领！")
sm.setParam(0)
sm.sendSay("你可以借助他的力量，但不可依赖于他的力量。")
sm.setParam(4)
sm.sendSay("好的，我会牢记的。我一定会凭我的力量打倒普赛依的。")
sm.setParam(2)
sm.sendSay("太好了。莱文。谢谢。首领。")
sm.setParam(4)
sm.sendSay("嗯？这次就拜托你了。我还有很多事情要告诉你，准备好的话就跟我说。")
sm.sendSay("好，你拿着这个，这礼物给你是为了让我们一起好好加油。")
sm.completeQuestNoCheck(parentID)
sm.setParam(1)
sm.sendSay("莱文就拜托给你了。也许是因为还小所以好像有些欲望高胀。")
sm.createQuestWithQRValue(18418, "B=33261")
sm.setParam(3)
sm.sendSay("请别担心。根据我一直在旁的观察来看，我觉得他一定能出色地完成任务的。")
sm.createQuestWithQRValue(18418, "B=33262")
