# id 17642 ([Commerci Republic] A Fickle Man), field 865010001
sm.setSpeakerID(9390244) # Leon Daniella
sm.setParam(56)
sm.setColor(1)
sm.sendNext("啊……对不起。我太轻率了。我应该先和你商量一下的。")
sm.setParam(32)
sm.sendSay("那样才对。虽然我们是朋友，但是我现在的身份是这艘船的船长啊。任何小事都应该先向我报告……")
sm.setParam(36)
sm.setInnerOverrideSpeakerTemplateID(9390204) # Robed Lady
sm.sendSay("哎呀，这船怎么造的这么没品味啊？是为了控制在便宜的价格范围内吗。")
sm.setParam(32)
sm.sendSay("听你一说我觉得莱文你说得对。虽然是朋友关系也该公私分明。我好好跟她说让她下船，你就别操心了。")
sm.setParam(56)
sm.sendSay("嗯？什么事？你应该不会是要我做这低贱的船务吧？")
sm.sendSay("不，那倒不是的。其实是想对你说抱歉……")
sm.setParam(36)
sm.sendSay("虽然是抱歉的话，但是今后也许会发生一些危险的事情。关于这点希望你能理解。")
sm.setParam(56)
sm.sendSay("我以为你要说什么呢。那个我早就想到了。我要是被抓了一定不会麻烦你来救我的，你就别担心我了，担心担心那边吧。如果没别的事我就失陪了。")
sm.setParam(32)
sm.sendSay("莱文怎么说的？你让她下船也行。和我也没什么深交，不过是比你多见过一次罢了。")
sm.setParam(36)
sm.sendSay("喔呵呵。船已经离港，想下船都难喽。让女孩一个人回去也不安全。反正不管怎样你知道那么回事就行了。")
sm.setParam(56)
sm.sendSay("(不管怎么说，好像了解了又貌似完全不了解的家伙。变来变去的。)")
sm.setParam(32)
sm.sendSay("喂。我有话跟你说。")
sm.setParam(56)
sm.sendSay("(Weirdo. I just can't figure him out.)")
sm.completeQuestNoCheck(parentID)
sm.createQuestWithQRValue(18418, "B=33268")
