# id 17663 ([Commerci Republic] Assassins's Den), field 865030101
sm.setSpeakerID(9390263) # Leon Daniella
sm.sendNext("那些家伙们看上去是这地方的守卫。")
sm.setParam(2)
sm.sendSay(" ……如果说是守卫的话这人数也太多了吧？")
sm.setParam(0)
res = sm.sendAskYesNo("……不管怎样不干掉他们的话就无法通过这里了。先把能看到的都干掉。")
sm.startQuest(parentID)
sm.sendNext("我们比比看谁干掉的更多吧？走吧！")
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
