# id 17657 ([Commerci Republic] Who's That Lady?), field 865030000
sm.setSpeakerID(9390205) # Claire Tremier
sm.setParam(32)
sm.setColor(1)
sm.sendNext("好了，准备好了吗。")
sm.setParam(36)
sm.setInnerOverrideSpeakerTemplateID(9390202) # Leon Daniella
sm.sendSay("噢噢……。")
sm.setParam(56)
sm.sendSay("莱文你怎么了？已经见到你真面目了，现在就介绍一下你的来历吧。")
sm.setParam(32)
sm.sendSay(" …………我这样做了你都还认不出我吗？所以说男人啊……")
sm.sendSay("我的名字是 #b克莱尔·特来敏#k。我是特来敏商团的独生女。")
sm.setParam(56)
sm.sendSay("你说特来敏？你是说让我受冤屈的那个特来敏吗？！")
sm.setParam(32)
sm.sendSay("是的。班·特来敏。那是我爸爸。")
sm.setParam(56)
sm.sendSay("这又是葫芦里卖什么药来着？")
sm.setParam(32)
sm.sendSay("葫芦里卖什么药，你这说法真低俗。")
sm.setParam(56)
sm.sendSay("等会，#h0#！先听听特来敏小姐怎么说。究竟是怎么一回事。她也许也有什么隐情呢。")
sm.setParam(36)
sm.sendSay("好的，那就听听吧。")
sm.setParam(56)
sm.sendSay("你说什么？")
sm.completeQuestNoCheck(parentID)
sm.createQuestWithQRValue(18418, "B=33288")
