# id 17618 ([Commerci Republic] The Lady in Robes), field 865020001
sm.setSpeakerID(9390204) # Robed Lady
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(9390204) # Robed Lady
sm.sendNext("怎么可能。我花了那么多钱雇来的佣兵竟然这模样……")
sm.setParam(57)
sm.sendSay("怎么样，我看你现在还是乖乖交出交易品吧。")
sm.setParam(33)
sm.sendSay("额…… 你是什么人，为什么要妨碍我的好事。")
sm.setParam(57)
sm.sendSay("你不用知道我是谁。我有我的理由。再说，你偷了东西，我不能就这么放过你。")
sm.sendSay("好了，你要怎么做。是乖乖交出交易品，还是要让我教训你一下才行。")
sm.setParam(33)
sm.sendSay("切。现在状况不妙。我们今天就此作别吧。")
sm.hideNpcByTemplateIdhi(9390204, True, True)
sm.setParam(57)
sm.sendSay("一下子就逃得没影了。那，我现在还是回村子吧。")
sm.sendSay("那人是叫提皮斯吗？把东西还给那个船员就可以了吧。")
sm.completeQuestNoCheck(parentID)
sm.startQuest(17619)
