# id 17672 ([Commerci Republic] Claire Tremier: Ace Attorney), field 865000002
sm.setSpeakerID(9390203) # Gilberto Daniella
sm.setParam(56)
sm.setColor(1)
sm.sendNext("您好吗。首领。我有话对您说。")
sm.setParam(36)
sm.setInnerOverrideSpeakerTemplateID(9390206) # Vaughn Tremier
sm.sendSay("你这些家伙还有什么脸面到这地方来啊！")
sm.setParam(32)
sm.sendSay("吉尔伯特首领，没有必要听他的。还不赶紧逮捕他们，干嘛呢。")
sm.setParam(36)
sm.sendSay("就算该抓的时候就抓，先听听他们说什么有何不妥。你说说什么事情？")
sm.setParam(32)
res = sm.sendAskYesNo("西温一开始实际上并没死，他是在装死。")
sm.setParam(56)
sm.sendNext("是的，这都是为了孤立凯梅尔兹共和国而计划的阴谋。")
sm.setParam(32)
sm.sendSay("是的，对外说海本王国提出了和约，但是凯梅尔兹反对，还杀死了使节团。最终，凯梅尔兹共和国就会被冒险岛世界的各个地方责难和孤立。")
sm.setParam(56)
sm.sendSay("那是什么荒唐的阴谋论啊！")
sm.setParam(32)
sm.sendSay("呃嗯……那叫西温的人现在在哪？")
sm.setParam(56)
sm.sendSay("虽已成功抓捕…… 但最终又被海本的暗杀者杀死了。")
sm.setParam(36)
sm.sendSay("那么你的意思是现在是真的死了吗？")
sm.setParam(32)
sm.sendSay("这种谎话王！毫无证据空口无凭来骗我")
sm.setParam(56)
sm.sendSay("你有什么想说的？")
sm.setParam(32)
sm.sendSay("他是装死？")
sm.setParam(56)
sm.sendSay("孤立的阴谋？")
sm.setParam(36)
sm.sendSay("是的，是那样的。")
sm.startQuest(parentID)
