# id 17668 ([Commerci Republic] Twice Cooked), field 865030111
sm.setSpeakerID(9390238) # Zion
sm.sendNext("现在就去，去了就行了吧。")
sm.setParam(2)
sm.sendSay("好吧，现在就去吧。")
sm.setParam(4)
sm.setInnerOverrideSpeakerTemplateID(9390202) # Leon Daniella
sm.sendSay("等会，特来敏小姐去哪了？")
sm.setParam(0)
sm.sendSay("啊，刚刚战斗前我怕克莱尔小姐被卷进来，把她送到外面去了。")
sm.sendSay("大概……在#b#m865030300##k了吧。")
sm.setParam(2)
res = sm.sendAskYesNo("原来是那样。那么我们也赶紧出去吧。")
sm.setParam(57)
sm.setColor(1)
sm.sendNext("好吧，赶紧带到吉尔伯特首领那儿去吧。")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9390218) # Il Capo
sm.sendSay("那样可不行。")
sm.setParam(32)
sm.sendSay("呃啊！")
sm.startQuest(parentID)
sm.setParam(57)
sm.sendSay("糟糕，西温呢！重要的证人消失了！")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9390202) # Leon Daniella
sm.sendSay("这下麻烦了，现在要如何才能洗脱罪名呢？")
sm.setParam(57)
sm.sendSay("稍微放松一下竟然就发生这样的事情！将来的事情也让人担心呐……")
sm.setParam(37)
sm.sendSay(" 嗯……啊！如此特来敏小姐也叫人担心呢！得赶紧出去看看！")
sm.setParam(57)
sm.sendSay("刚刚西温说克莱尔在哪里？")
sm.setParam(37)
sm.sendSay("说大概会在#b#m865030300##k。赶紧走吧。")
