# id 17640 ([Commerci Republic] Pack Up, and Set Sail 3), field 865000000
sm.setSpeakerID(9390204) # Robed Lady
sm.setParam(56)
sm.setColor(1)
sm.sendNext("好了，我也现在就去码头吧。")
sm.setParam(32)
sm.sendSay("哎呀，又遇见了呢。")
sm.setParam(56)
sm.sendSay("呃啊！吓了我一大跳！！干嘛呀，在别人背后干嘛呢！")
sm.setParam(32)
sm.sendSay("就是路过的时候看见了而已。")
sm.setParam(56)
sm.sendSay("原来如此。那么就请继续路过吧。我很忙失陪……")
sm.setParam(32)
sm.sendSay("你要去讨伐海盗吗？")
sm.setParam(56)
sm.sendSay("是的，是那样的。怎么了？你感兴趣吗？")
sm.setParam(32)
sm.sendSay("哦呵呵，怎么会呢。我怎么会对那种低俗又野蛮的事情感兴趣呢。那我就告辞了")
sm.setParam(56)
sm.sendSay("…………低俗？野蛮？这人真是……算了。赶紧去码头吧。")
sm.completeQuestNoCheck(parentID)
sm.completeQuestNoCheck(17730)
sm.createQuestWithQRValue(18418, "B=33265")
sm.createQuestWithQRValue(18418, "B=33266")
