# id 17681 ([Commerci Republic] Final Report), field 130000000
sm.setSpeakerID(1101002) # Neinheart
sm.setParam(36)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(1540451) # Neinheart
sm.sendNext("你来了啊，从你的脸上就能看到你很辛苦啊。")
sm.setParam(56)
sm.sendSay("真是多亏了某人啊。")
sm.setParam(36)
sm.sendSay("什么某人啊，你这说的像是有哪个人特意让你受苦了啊。你的表情似乎是在说我就是那个人啊？")
sm.setParam(56)
sm.sendSay("……究竟帕尔巴特是什么人，你给了他什么才让他带我到凯梅尔兹的？还有，一开始去凯梅尔兹的船本身……")
sm.setParam(36)
sm.sendSay("请你不要再说这些没营养的话了。最终你不是没什么损失吗？而且还交到了好朋友。当然，我并没有预料到这一点。")
sm.setParam(56)
sm.sendSay("#b(……我感觉这次也被这个人玩弄于股掌之中啊。)#k")
sm.setParam(36)
sm.sendSay("总之，辛苦你了。委托你做事的时候，总是有好结果呢。看来这就是意外之喜吧。")
sm.sendSay("哎呀，我说错了，这都是你有实力的结果啊。")
sm.setParam(56)
sm.sendSay("#b(……我居然忘了让女皇教训南哈特……)#k")
sm.setParam(36)
sm.sendSay("对了，这个是女皇大人为了你准备的小小奖励。\r\n\r\n#b#i2049702:##t2049702##k\r\n#b#i2431935:##t2431935##k\r\n#b#i2431936:##t2431936##k")
sm.sendSay("还有，你从凯梅尔兹带来的书信里，还附有这样的东西。你可得好好保管它。\r\n\r\n#b#i1142981:##t1142981##k")
sm.sendPrev("You don't have enough space in your inventory. Please empty at least 2 slots in Equip tab, and 3 slots in Use tab.")
