# id 17660 ([Commerci Republic] Clairenapped), field 865030000
sm.setSpeakerID(9390236) # Leon Daniella
sm.setParam(2)
sm.sendNext("出什么事了？克莱尔去哪儿了？")
sm.setParam(0)
sm.sendSay("你去抓狼的时候有些奇怪的家伙们来过。不分青红皂白地扑过来，我就一味地抵挡，然后就发现特来敏小姐不见了！")
sm.sendSay("是逃去哪儿了吗？还是被抓走了呢？我真是个笨蛋！！怎么都没想到保护特来敏小姐！！")
sm.setParam(2)
sm.sendSay("别自责了，莱文。她不会有事的。")
sm.setParam(0)
res = sm.sendAskYesNo("赶紧去找找她吧！")
sm.startQuest(parentID)
sm.showNpcSpecialActionByTemplateId(9390227, "summon", 0)
sm.showNpcSpecialActionByTemplateId(9390228, "summon", 0)
sm.setParam(5)
sm.setInnerOverrideSpeakerTemplateID(9390227) # Guild Assassin
sm.sendNext("现在担心你们自己的小命才是更明智的。")
sm.setParam(1)
sm.sendSay("谁呀！")
sm.setParam(5)
sm.sendSay("那个你们没必要知道。反正你们马上就要从这世界上消失了。")
sm.setParam(3)
sm.sendSay("你们这些家伙是暗杀海本王国使节团的家伙们啊！！")
sm.setParam(5)
sm.sendSay("呼，醒悟吧！")
sm.startQuest(16689)
sm.startQuest(parentID)
sm.startQuest(16689)
sm.startQuest(parentID)
sm.startQuest(16689)
sm.startQuest(16689)
sm.startQuest(parentID)
sm.startQuest(16689)
sm.startQuest(parentID)
sm.startQuest(16689)
sm.startQuest(16689)
sm.startQuest(parentID)
sm.startQuest(16689)
sm.startQuest(parentID)
sm.startQuest(16689)
sm.startQuest(16689)
sm.startQuest(parentID)
sm.startQuest(16689)
sm.startQuest(16689)
sm.startQuest(16689)
sm.startQuest(parentID)
sm.startQuest(16689)
sm.startQuest(parentID)
sm.startQuest(16689)
sm.startQuest(parentID)
sm.startQuest(16689)
sm.startQuest(parentID)
sm.startQuest(16689)
sm.startQuest(parentID)
sm.startQuest(16689)
