# id 17645 ([Commerci Republic] Close Up with Captain Blood), field 865010001
sm.setSpeakerID(9390209) # Captain Blood
sm.setParam(4)
sm.setInnerOverrideSpeakerTemplateID(9390235) # Leon Daniella
sm.sendNext("果然是受了普赛依的指挥的家伙们更有组织性了！")
sm.setParam(0)
sm.sendSay("你是海盗王普赛依！！")
sm.setParam(4)
sm.setInnerOverrideSpeakerTemplateID(9390202) # Leon Daniella
sm.sendSay("能把我们赶到这里，实力还算是够可以得啦。但是玩笑就开到这为止了。")
sm.setParam(0)
sm.sendSay("到底谁不行等着瞧就知道了！#h0#！准备好了吗！？")
sm.setParam(4)
sm.setInnerOverrideSpeakerTemplateID(9390235) # Leon Daniella
res = sm.sendAskYesNo("把海盗们从这海峡赶出去！！")
sm.startQuest(parentID)
sm.setParam(5)
sm.sendNext("好的，痛快地干一场吧！！")
sm.sendSay("谢谢你的称赞。")
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
