# id 17658 ([Commerci Republic] Claire's Story), field 865030000
sm.setSpeakerID(9390205) # Claire Tremier
sm.setParam(32)
sm.setColor(1)
sm.sendNext("父亲是为了我的幸福什么都肯去做的人。但是那份心意有些过头了。父亲想把我嫁到海本王族去。")
sm.setParam(36)
sm.setInnerOverrideSpeakerTemplateID(9390202) # Leon Daniella
sm.sendSay("嫁过去！！？？")
sm.setParam(32)
sm.sendSay("是的，所以父亲把我送到了海本王族人们接受教育的地方去留学。可是我讨厌那样。也讨厌没有爱情的婚姻，连海本王国的思想都让我讨厌。还有……")
sm.setParam(56)
sm.sendSay("还有？")
sm.setParam(32)
sm.sendSay("还有？其实我想系统地学习魔法！")
sm.setParam(56)
sm.sendSay("学魔法？")
sm.setParam(32)
sm.sendSay("是的，成为冒险岛世界最出色的魔法师是我的梦想。所以我一个人偷偷地自学了。")
sm.setParam(56)
sm.sendSay("啊哈，所以你才会用那么多魔法啊。")
sm.setParam(32)
sm.sendSay("是的，可是自学总会到达极限的。所以我决心瞒着父亲到魔法王国去留学。但是我这个年纪的女孩一个人想挣到那么大笔的留学费用有点难以实现。所以……那个……")
sm.setParam(56)
sm.sendSay("啊，好了，你不说我也明白了。我明白你的意思了。")
sm.setParam(32)
sm.sendSay("好的，谢谢你。会实现的。")
sm.setParam(56)
sm.sendSay("可是克莱尔小姐的父亲为什么咬定我是杀人犯呢？")
sm.setParam(32)
sm.sendSay("是啊。这我也不是很清楚，我想或许跟海本王国有所关联。父亲最近好像给海本王族寄去了很多礼物和书信。")
sm.completeQuestNoCheck(parentID)
sm.createQuestWithQRValue(18418, "B=33289")
