# 1800 - [Evolution System] Suspicious Movement on the path
sm.setSpeakerID(9400115)
sm.sendNext("感谢你来到埃德尔斯坦。因为必须告诉联盟下属的各位，所以才突然和你联系。我就简单地为你说明一下埃德尔斯坦地下矿山发生的事情。首先……你知道左边的人是谁吗？")
sm.setPlayerAsSpeaker()
sm.sendNext("……那个人是……！")
sm.setSpeakerID(9400115)
sm.sendNext("你的猜测是对的。是的，她就是黑色之翼的创始人和领导者，黑魔法师的军团长……")
sm.setPlayerAsSpeaker()
sm.sendNext("奥尔卡？")
sm.setSpeakerID(9400115)
sm.sendNext("是的，他就是占领埃德尔斯坦并夺取能源，在冒险岛世界各地夺取封印石，攻击联盟成员双弩精灵的人……军团长奥尔卡。")
sm.sendNext("我说后来她怎么就销声匿迹了……看来是有原因的。黑色之翼内部，以及军团长的构成都发生了巨大的变化。")
sm.sendNext("老实说，我们也没有完全掌握所有的情况……根据军团长奥尔卡的陈述和在地下矿山研究所中发现的痕迹，我们推测出了一些情况，所以才将联盟的人召集了起来。")
sm.sendNext("好了，我来为你说明一下，军团长奥尔卡到底发生了什么事，以及我们所了解到的事件的真相。说明可能会有点长……但是这是非常重要的事情，希望你能注意听。")
sm.startQuest(parentID)
sm.warpInstanceIn(957020001, 0)