# A Close Call - Start (3rd job adv for CoK)
sm.setPlayerAsSpeaker()
sm.sendNext("到底是什么书啊……啊，这到底是……我还是头一次看见这种文字。一个字都看不懂……")
sm.sendNext("好像是非常重要的东西，必须尽快送到圣地去。")
sm.sendNext("怎么感觉阴森森的……")
sm.setSpeakerID(1104302)
sm.sendSay("咦，怎么突然有人出现了？！难道是想把书抢走吗？不行！不能让黑色之翼抢走。来吧！！！")
sm.warp(922030400, 0)
sm.startQuest(parentID)