#The Alliance gathers
sm.setSpeakerID(1540838)
sm.sendNext("你来啦？女皇殿下刚到金银岛。其他骑士团长也都来了，不过希望你不要因此放松警惕。好了，你想现在出发吗？")
sm.sendNext("咦，等等……奇库？奇库怎么突然到这里来了？而且……好像受伤了！大家先停下来！")
sm.removeEscapeButton()
sm.spawnNpc(1104311, 232, 97, True)
sm.setSpeakerID(1104311)
sm.sendNext("S-stop. Please! L-listen...")
sm.setSpeakerID(1101007)
sm.sendNext("Kiku? What happened? Are you okay You have to be treated...")
sm.setSpeakerID(1104311)
sm.sendNext("No..  I am okay. Please listen to me...! Ereve. Ereve has been invaded!")
sm.sendNext("Shinsoo was fighting against it... We have to be quick to help him... Towards Ereve!")
sm.setSpeakerID(1540838)
sm.sendNext("Wait, Kiku. Who attacked Ereve? Do you remember their face?")
sm.setSpeakerID(1104311)
sm.sendNext("It was my first time seeing him. White skin with plum coloured hair...")
sm.setSpeakerID(1540838)
sm.sendNext("My lady! I guess the meeting needs to be ceased. Please send our knights to Ereve...!")
sm.completeQuest(parentID)
sm.startQuest(20951)
sm.completeQuest(20951)
sm.warp(130000000)