#The Alliance gathers
sm.setSpeakerID(1540838)
sm.sendNext("How did things go? Oh, I should tell you that the Empress just arrived on Victoria Island. All the other CHief Knights are here as well, but you should never lower your guard. Shall we head out?")
sm.sendNext("Wait...Kiku? Why is Kiku here? Goodness, he's injured!")
sm.removeEscapeButton()
sm.spawnNpc(1104311, 232, 97, True)
sm.setSpeakerID(1104311)
sm.sendNext("S-stop. Please! L-listen...")
sm.setSpeakerID(1101007)
sm.sendNext("Kiku? What happened? Are you okay You have to be treated...")
sm.setSpeakerID(1104311)
sm.sendNext("No..  I am okay. Please listen to me...! Ereve. Ereve has been invaded!")
sm.sendNext("Shinsoo was fighting against it... We have to be quick to help him... Towards Ereve!")
sm.setSpeakerID(1540838)
sm.sendNext("Wait, Kiku. Who attacked Ereve? Do you remember their face?")
sm.setSpeakerID(1104311)
sm.sendNext("It was my first time seeing him. White skin with plum coloured hair...")
sm.setSpeakerID(1540838)
sm.sendNext("My lady! I guess the meeting needs to be ceased. Please send our knights to Ereve...!")
sm.completeQuest(parentID)
sm.startQuest(20951)
sm.completeQuest(20951)
sm.warp(130000000)