# 21201 - [Job Adv] (Lv.30)   Aran
sm.setSpeakerID(1201002)
sm.sendNext("曾经是谁说要让我成为击退黑魔法师的传世武器的？结果中了诅咒，自顾自地沉睡了几百年，把我丢在一边不管不顾。……什么？想不起来了？一句想不起来了就想了事？当初苦苦求我，拜托我的时候怎么说的来着……")
sm.setPlayerAsSpeaker()
sm.sendNext("说要向#p1203000#证明自己的实力，请他给我一个机会。")
sm.setSpeakerID(1201002)
sm.sendNext("没错！当初为了得到我，你低三下四地苦苦哀求。要知道像我这样优秀的武器，你上哪里去找啊？能够和黑魔法师相抗衡的最强的#p1201001#就是我了！结果你却把我扔在冰窟里，一放就是几百年……")
sm.setPlayerAsSpeaker()
sm.sendNext("什么？没有苦苦哀求？是谁哭着闹着要得到我，甚至不惜双膝下跪苦苦哀求？要不#p1203000#怎么会答应……等等？战神！你难道……难道已经想起来了？！")
sm.setSpeakerID(1201002)
sm.sendNext("有一点点……")
sm.setPlayerAsSpeaker()
sm.sendNext("……真不愧是战神啊……呜，呜呜！不，我一点都没有感动！……虽然中了黑魔法师的诅咒，能力尽失，连拿起我的力气都没有了……即便如此，你居然还能想起我，真不愧是我的主人啊！")
sm.setSpeakerID(1201002)
sm.sendNext("就算你失去记忆也还是我的主人。那经过极端训练的身体依然能够记得当初的技能，虽然在冰窟中沉睡了数百年，但这一点我还是很清楚的。好吧，我帮你唤醒你的能力！")
if sm.sendAskYesNo("你的等级还没有以前那么高，没法帮你唤醒所有的能力。不过，先帮你唤醒一部分的能力，这样将来升级也会更快一些。快点恢复从前的能力吧！"):
    if not sm.canHold(1142130):
        sm.sendSayOkay("倒也没有苦苦哀求。")
        sm.dispose()
    sm.completeQuest(parentID)
    sm.giveItem(1142130)
    sm.jobAdvance(2110)
    sm.sendNext("Your level isn't what it used to be back in your glory days, so I can't restore all of your old abilities. But the few that I can restore should help you level up faster. Now hurry up and train so you can return to the old you.")
