# 21200 - [Job Adv] (Lv.30)   Aran
sm.setSpeakerID(1201001)
sm.sendNext("嗡嗡嗡嗡嗡……")
sm.setPlayerAsSpeaker()
sm.sendNext("#b（#p1201001#在发出嗡鸣声。奇怪，那边的少年是谁？）#k")
sm.sendNext("#b（以前没见过他啊？怎么看起来不太像人类？）#k")
sm.setSpeakerID(1201002)
sm.sendNext("喂！战神！还听不见我的声音吗？到底听不听得见？唉，烦死了！")
sm.setPlayerAsSpeaker()
sm.sendNext("#b（咦？这是谁的声音？怎么听起来像个凶巴巴的少年……）#k")
sm.setSpeakerID(1201002)
sm.sendNext("唉……哪有这样的主人啊？丢开武器在冰窟里睡了几百年，现在连话都听不懂了……")
sm.setPlayerAsSpeaker()
sm.sendNext("你是谁啊？")
sm.setSpeakerID(1201002)
sm.sendNext("啊，战神？现在听到我的声音了？是我啊，不记得我了？我就是武器#b长矛 #p1201002##k啊？")
sm.setPlayerAsSpeaker()
sm.sendNext("#b（……#p1201002#？#p1201001#会说话？）#k")
sm.setSpeakerID(1201002)
sm.sendNext("不至于吧？这么吃惊？再怎么失忆，总不能连我都忘了吧？太不够意思了！")
sm.setPlayerAsSpeaker()
sm.sendNext("不好意思，真的一点都想不起来。")
sm.setSpeakerID(1201002)
if sm.sendAskYesNo("说声不好意思就能算了？！几百年来就我一个人孤苦伶仃地，有多寂寞你知道吗？不管怎样，你快点给我想起来！"):
    sm.completeQuest(parentID)
    sm.setPlayerAsSpeaker()
    sm.sendNext("#b（一口一个自己是#p1201001#、#p1201002#的，还越说越生气了。再这么说下去也不会有啥进展，还是先走到 #p1201000#跟前，好好商量商量。）#k")
    sm.dispose()
else:
    sm.dispose()