# 22008 |   Chasing away the foxes (Evan intro)
sm.setSpeakerID(1013101)
sm.sendNext("#o9300385#消灭掉了吗？")
sm.setPlayerAsSpeaker()
sm.sendNext("#b你说要去收拾剩下的狐狸的，怎么回事？")
sm.setSpeakerID(1013101)
sm.sendNext("啊，那个嘛？我后来是去了，但走错了路，怕被#o9300385#抓去做人质，所以就回来了。")
sm.setPlayerAsSpeaker()
sm.sendNext("#b该不会是害怕狐狸而躲起来了吧？")
sm.setSpeakerID(1013101)
sm.sendNext("你在胡说什么啊？！我为什么会害怕狐狸？！我一点都不害怕狐狸！")
sm.setPlayerAsSpeaker()
sm.sendNext("#b……啊，有一只#o9300385#！")
sm.setSpeakerID(1013101)
sm.sendNext("啊！快躲起来！")
sm.setPlayerAsSpeaker()
sm.sendNext("……你这家伙。别吓哥哥我！哥哥我的心脏不好，不能受惊吓！")
sm.setSpeakerID(1013101)
sm.sendNext("#b(所以叫哥哥才不愿意去，叫我去。)")
sm.sendNext("哼哼，不管怎样，#o9300385#消灭掉了。辛苦你了，我把一个路过的冒险家送我的东西送给你，作为给你的报酬。来，拿着。\r\n\r\n#fUI/UIWindow2.img/QuestIcon/4/0# \r\n#i1372043# #t1372043#1个\r\n#i2022621# #t2022621#25个\r\n#i2022622# #t2022622#25个\r\n\r\n#fUI/UIWindow2.img/QuestIcon/8/0# 910 exp")
sm.setPlayerAsSpeaker()
sm.sendNext("是#b魔法师的攻击武器短杖#k。虽然你也可能没什么用，但拿在手里到处走，还是很帅的，哈哈哈。")
sm.setSpeakerID(1013101)
sm.sendNext("狐狸的数量确实增加了，对吧？奇怪。狐狸的数量为什么会增加呢？看来必须调查一下。")
if sm.canHold(1372107):
    sm.giveItem(1372107)
    sm.giveExp(910)
    sm.completeQuest(parentID)
    sm.sendNext("#bThis is a weapon that Magicians use. It's a Wand. #k You probably won't really need it, but it'll make you look important if you carry it around. Hahaha")
    sm.sendSay("Anyways, the Foxes have increased, right? How weird is that? Why are they growing day by day? We should really look into it and get to the bottom of this.")
    sm.dispose()
else:
    sm.sendNext("Please make room in your Equip Inventory.")
    sm.dispose()



