# id 22714 (Ultimate Skill), field 331001130
sm.startQuest(parentID)
sm.lockInGameUI(True, False)
sm.removeAdditionalEffect()
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(1531000) # Kinesis
sm.sendNext("Is that all?")
sm.setInnerOverrideSpeakerTemplateID(1531001) # Jay
sm.sendSay("#face9#No, of course not. Don't get ahead of yourself, K.")
sm.sendSay("#face9#I'm tracking your Psychic Points #g(PP)#k so you'll know when you can use your ultimate. That's what I call that super technique you came up with. Seemed appropriate.")
sm.sendSay("#face9#You'll get Psychic Points just by using psychokinesis abilities. I have to say, you have a very convenient power set, K.")
sm.progressMessageFont(3, 20, 20, 0, "Collect Psychic Points to unleash your ultimate skill.")
sm.sendDelay(2500)
sm.avatarOriented("UI/tutorial.img/kinesis/2")
sm.playExclSoundWithDownBGM("Voice3.img/Kinesis/guide_14", 100)
sm.sendNext("#face9#Your ultimate skill should be on your #g[END]#k key, if you haven't moved it. Go ahead and let loose with it... I reinforced the walls after last time.")
sm.playSound("Sound/SoundEff.img/blackHeaven/metaldrop", 100)
sm.sendDelay(1000)
sm.sendNext("#face9#Ultimate: Metal Press#g [END]#k will crush everything in its path, including targets high above you.")
sm.lockInGameUI(False, True)
sm.createQuestWithQRValue(16700, "count=13;date=20190716")
sm.createQuestWithQRValue(16700, "count=14;date=20190716")
sm.createQuestWithQRValue(16700, "count=15;date=20190716")
sm.createQuestWithQRValue(16700, "count=16;date=20190716")
sm.createQuestWithQRValue(16700, "count=17;date=20190716")
sm.createQuestWithQRValue(16700, "count=18;date=20190716")
sm.createQuestWithQRValue(16700, "count=19;date=20190716")
sm.playSound("Party1/Clear", 100)
sm.showFieldEffect("monsterPark/clear", 0)
