# id 22723 (Petitioning 2), field 331002000
sm.setSpeakerID(1531046) # Young
sm.setParam(9)
sm.sendNext("Hey there, #b#h0##k! Did you see this picture in the paper? My dumb friend is convinced it's you. We've been arguing all morning.")
sm.lockInGameUI(True, False)
sm.sendDelay(1500)
sm.blind(True, 255, 0, 0, 0, 500)
sm.sendDelay(500)
sm.onLayer(1000, "1", 0, 0, 12, "Map/Effect2.img/kinesis/news2", 4, False, -1, False)
sm.sendDelay(1500)
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(1531000) # Kinesis
sm.sendNext("#b...Oh yeah, I remember that. Good one.#k")
sm.sendDelay(1500)
sm.offLayer(1500, "1", False)
sm.sendDelay(1500)
sm.blind(True, 255, 0, 0, 0, 0)
sm.sendDelay(1200)
sm.blind(False, 0, 0, 0, 0, 1000)
sm.sendDelay(1400)
sm.lockInGameUI(False, True)
sm.setSpeakerType(4)
sm.setParam(9)
sm.setColor(0)
sm.sendNext("What?")
sm.setParam(3)
sm.sendSay("What? I didn't say anything.")
sm.setParam(9)
sm.sendSay("The really weird part is that they're saying this Kinesis person uses psyro... psino... mind powers to move things.")
sm.sendSay("That's just ridiculous, right? No one can do that, right #b#h0##k?")
sm.sendSay("Think about it. Here, I'll sign that thing for you.")
sm.progressMessageFont(3, 20, 20, 0, "Two down, one to go.")
sm.startQuest(parentID)
sm.completeQuestNoCheck(parentID)
