# id 22724 (Petitioning 3), field 331002000
sm.setSpeakerID(1531047) # Joon
sm.setParam(9)
sm.sendNext("Oh, hi! Need me to sign something? Sure, anything for the Student Council President.")
sm.sendSay("Hey, I heard Kinesis caught a bank robber. Did you see the news?")
sm.lockInGameUI(True, False)
sm.sendDelay(1500)
sm.blind(True, 255, 0, 0, 0, 500)
sm.sendDelay(500)
sm.onLayer(1000, "2", 0, 0, 12, "Map/Effect2.img/kinesis/news3", 4, False, -1, False)
sm.sendDelay(1500)
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(1531000) # Kinesis
sm.sendNext("#b...Man, that picture came out great. I'll have to repost that.#k")
sm.sendDelay(1500)
sm.offLayer(1500, "2", False)
sm.sendDelay(1500)
sm.blind(True, 255, 0, 0, 0, 0)
sm.sendDelay(1200)
sm.blind(False, 0, 0, 0, 0, 1000)
sm.sendDelay(1400)
sm.lockInGameUI(False, True)
sm.setSpeakerType(4)
sm.setParam(9)
sm.setColor(0)
sm.sendNext("I got the inside story on their true identity, too. You ready for this?")
sm.sendSay("Kinesis is an alien from an exploded planet who crashed on Earth! They were adopted by humans who were killed by a criminal, so they vowed to spend their life fighting crime. While training they got struck by lightning, but then saved by a magic ring from outer space.")
sm.sendSay("I mean, it's really the only logical story once you narrow it down.")
sm.setParam(3)
sm.sendSay("...Comic books are destroying society.")
sm.progressMessageFont(3, 20, 20, 0, "That's all of them. Time to get this list back to Yuna.")
sm.startQuest(parentID)
sm.completeQuestNoCheck(parentID)
sm.startQuest(11620)
sm.createQuestWithQRValue(15710, "lasttime=19/07/16/05/31")
