# 25511 - [Job Adv] (Lv.60)   The Power of Crystals
sm.removeEscapeButton()
sm.setSpeakerID(1032209)
sm.sendNext("夜光法师，我已经将秘宝力量全部收集来了。")
sm.sendNext("现在利用这种力量，就能将夜光法师身体内的黑暗与光明融合在一起。")
sm.sendNext("别忘了。无论秘宝力量有多强大，最终还是要靠夜光法师你去战胜它。")
sm.setPlayerAsSpeaker()
sm.sendNext("不要担心。我对自己的承受力有信心。")
sm.setSpeakerID(1032209)
sm.sendNext("记住这句话。#b<最黑暗的时候，光芒最盛。>#k一定会有帮助的。开始啦。嘿啊啊呀！")
sm.setPlayerAsSpeaker()
sm.sendNext("哇呀呀呀呀！")
sm.setSpeakerID(1032209)
sm.sendNext("成功了！我就知道这样，不愧是夜光法师。")
sm.setPlayerAsSpeaker()
sm.sendNext("(流淌在我体内的气息不太一样了。有种光与黑暗融为一体的感觉……)")
sm.setSpeakerID(1032209)
sm.sendNext("刚才应该消耗了不少力气，先休息休息吧。关于你现在的情况，我一会和你细说。")
sm.setJob(2711)
sm.startQuest(parentID)
sm.completeQuest(parentID)
sm.addSP(4)

