# id 25837 (Challenge: Recharge!), field 400000000
sm.setSpeakerType(3)
sm.setParam(4)
sm.setInnerOverrideSpeakerTemplateID(3000018) # Eskalade
sm.sendNext("下面就通过实战来学习重生的相关内容吧。")
sm.setParam(16)
sm.sendSay("实战？怎么这么突然？")
sm.setParam(4)
sm.sendNext("要是光说说就能理解所有东西，世上的事情就太简单了。你先去消灭怪物练练手吧。")
sm.setParam(16)
sm.sendSay("冷不丁地来这一句，什么跟什么嘛！")
sm.setParam(4)
sm.sendSay("简单得很。就是你去挑战在这附近乱晃的那些怪物，练习如何使用你获得的力量。只要#b成功重生5次#k就行，不会花多长时间。好啦，快去~！")
sm.setParam(16)
sm.sendSay("你说话算话哦……唉，不管啦，硬着头皮上吧。")
sm.setParam(4)
sm.sendSay("Just walk out there, find a monster, and use your skills! #bRecharge successfully 5 times#k. It won't take you long!")
sm.setParam(17)
sm.sendSay("Ugh, I don't wanna get all sweaty, but I guess I have to.")
sm.startQuest(parentID)
sm.startQuest(11620)
sm.createQuestWithQRValue(15710, "lasttime=19/07/16/06/15")
