# id 25829 (Skill Starter), field 400000000
sm.setSpeakerType(3)
sm.setParam(4)
sm.setInnerOverrideSpeakerTemplateID(3000018) # Eskalade
sm.sendNext("你获得力量还没多久，还不太适应吧？我给你讲讲几种技能，你好好听。")
sm.setParam(16)
sm.sendSay("好，快说吧。")
sm.setParam(4)
sm.sendSay("我要讲解的是新手技能中几种和攻击无关的技能，先说说都有哪些吧。")
sm.sendSay("第一个技能是#i3800342#白日梦。使用该技能可以移动到我#e特别#n准备的据点。")
sm.setParam(16)
sm.sendSay("特别？据点？那又是什么东东？")
sm.setParam(4)
sm.sendSay("呵呵，你要是想知道，就亲自用技能去看看。接下来是#i3800344#装扮技能，使用该技能可以自由转换变身前、后的效果，即便在变身前尝试使用其他技能，也会先行使用装扮技能，你也没必要觉得吃惊。")
sm.setParam(16)
sm.sendSay("看来你被我的介绍打动了呢。其他那些攻击技能你亲自使用后会更快了解，我的说明就到此结束吧。")
sm.setParam(4)
sm.sendSay("That's kind of all I feel like explaining. I can see it's not really sinking in anyway. Just... try that other stuff out on your own.")
sm.completeQuestNoCheck(parentID)
