# id 30051 ([Theme Dungeon] The Straight-Faced Princess), field 106030000
sm.setSpeakerID(1302000) # Mushking
sm.setParam(32)
sm.setColor(1)
sm.sendNext("欢迎↗ 来→ 到↘ 蘑菇↗ 城→，陌生人↘ \r\n谢谢你接受了我的邀请，来到这么远的地方。呵呵，当然，所有人只要一看到我美丽的女儿碧欧蕾塔的肖像画，就会无法控制自己的脚步。那是一种本能！")
sm.setParam(56)
sm.sendSay("……当然，她本人的冲击力要比照片更强。")
sm.setParam(32)
sm.sendSay("是的，碧欧蕾塔拥有的魔性的魅力是不分男女的。我可以理解你所受到的冲击。你一定觉得很遗憾，无法成为碧欧蕾塔的#r#e新郎#k#n！")
sm.setParam(56)
sm.sendSay("公主的……新郎？完全不感兴趣(郑重其事)。")
sm.setParam(32)
sm.sendSay("你也看到了，这里的宴会场正在举行大会。大会的名字叫做#r博碧欧蕾塔一笑大会#k。很遗憾，从来没人见过我女儿碧欧蕾塔笑过。我这个做父亲的心情能好受吗？也许是为了不让其他人因为自己的美貌而患上相思病，所以碧欧蕾塔一直在忍着不笑……")
res = sm.sendAskAccept("所以我下了决心，我要让能博公主一笑的人成为碧欧蕾塔的新郎，并把王位让给他。但是很遗憾，这个大会只有蘑菇才能参加。不过我可以破例给你一个和公主对话的机会！好了，你快去和公主谈谈吧。")
sm.startQuest(parentID)
sm.sendSayOkay("但是，注意别被公主的美貌给迷住。当然，那个不是自己可以控制的。")
