# id 34263 ([Morass] The Prince and the Princess 2), field 450006300
sm.setSpeakerType(3)
sm.setParam(36)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(3003406) # Jean
sm.sendNext("#face12#I think I dropped it somewhere here.")
sm.setParam(56)
sm.sendSay("What is it that you dropped exactly?")
sm.setParam(36)
sm.sendSay("#face0#It's just... something Tana would like. \r\nI got distracted and dropped it somewhere around here.")
sm.setParam(56)
sm.sendSay("Is it jewelry or what?")
sm.closeUI(1128)
sm.setParam(36)
sm.sendSay("#face11#Sort of...")
sm.closeUI(1128)
sm.closeUI(1128)
sm.closeUI(1128)
sm.setParam(56)
sm.sendSay("#b(Why is he being so weird about it?)#k")
sm.sendSay("#b(And what would Tana want with jewelry?)#k")
sm.closeUI(1128)
sm.sendSay("One of these monsters must have taken it.")
sm.closeUI(1128)
sm.closeUI(1128)
sm.setParam(36)
res = sm.sendAskYesNo("#face0#Oh! Well, you're really strong. Do you think you could get it?")
sm.closeUI(1128)
sm.closeUI(1128)
sm.setParam(56)
sm.sendNext("Yeah. I-I think so.")
sm.startQuest(parentID)
sm.closeUI(1128)
