# id 34256 ([Morass] A Frightening Rumor 2), field 450006130
sm.setSpeakerType(3)
sm.setParam(56)
sm.setColor(1)
sm.sendNext("You know that monument in the center square?")
sm.setParam(36)
sm.setInnerOverrideSpeakerTemplateID(3003412) # Woman
sm.sendSay("#face0#Mm hm, yes.")
sm.sendSay("#face0#It was placed after that anti-magic stone fell and broke all those years ago. ")
sm.sendSay("#face0#The moment that stone shattered, everyone in the vicinity disappeared without a trace. It was so sad.")
sm.setParam(56)
sm.sendSay("Is it true there was a survivor?")
sm.setParam(36)
sm.sendSay("#face0#You mean the Angel of Death?")
sm.setParam(56)
sm.sendSay("People call her the Angel of Death?")
sm.setParam(36)
sm.sendSay("#face0#Yes. I mean, she was quite a frightening sight. \r\nI'll never forget her. Couldn't sleep for days after that. ")
sm.sendSay("#face0#She just vanished and rematerialized like it was nothing.\r\nAnd the way she looked too... that darkness... her eyes...\r\nOnly someone incredibly powerful could have managed something like that.\r\nI suppose that's why they took such an interest in her.")
sm.setParam(56)
sm.sendSay("Who took an interest in her? What happened to her?")
sm.setParam(36)
sm.sendSay("#face0#The soldiers... Once they got a hold of her, no one ever saw her again. There have been rumors though.")
sm.sendSay("#face0#You know, there's one person who might know more. \r\nHe's been asking about those rumors too, but I haven't seen him lately...")
sm.setParam(56)
sm.sendSay("Who's that?")
sm.setParam(36)
sm.sendSay("#face0#Well, Jean, of course. He was the last one to see her alive... or so they say.")
sm.setParam(56)
sm.sendSay("Hmm... Jean... I'll have to track him down. Thanks.")
sm.completeQuestNoCheck(parentID)
sm.createQuestWithQRValue(parentID, "book=1")
sm.sendSay("#b(Hm? What's this journal doing in your bag? Who does it belong to? And why is it glowing? Maybe you should take a look at it.)#k")
