# id 34252 ([Morass] Unexpected Enemy 3), field 450006030
sm.closeUI(1128)
sm.setSpeakerType(3)
sm.setParam(56)
sm.setColor(1)
sm.sendNext("No matter how many I defeat, there are always more!")
sm.setParam(36)
sm.setInnerOverrideSpeakerTemplateID(3003409) # Flying Fish
sm.sendSay("#face0#Wonderful isn't it, the ability for the Erda to be born anew?")
sm.setParam(56)
sm.sendSay("Wonderful isn't exactly the first thing that comes to mind...")
sm.setParam(36)
sm.sendSay("#face0#Wait... I can sense her nearby.\r\nShe's much closer than I expected.")
sm.setParam(56)
sm.sendSay("Her? Who are you talking about?")
sm.setParam(36)
sm.sendSay("#face0#Tana! Her presence alone is enough to effect even me...")
sm.sendSay("#face0#Let's proceed with caution.")
sm.warp(940204002)
