# id 34256 ([Morass] A Frightening Rumor 2), field 450006130
sm.setSpeakerType(3)
sm.setParam(56)
sm.setColor(1)
sm.sendNext("那个广场中央的纪念碑……")
sm.setParam(36)
sm.setInnerOverrideSpeakerTemplateID(3003412) # Woman
sm.sendSay("#face0#嗯？纪念碑？当时你不在吗？")
sm.sendSay("#face0#几年前发生了一场大事故。反魔力石在设置过程中摔碎了。")
sm.sendSay("#face0#那东西损毁后，在附近做生意的商贩一下子……\r\n#fs18##r蒸发#k#fs16#了。真是可惜。")
sm.setParam(56)
sm.sendSay("原来如此……可听说有人活下来了……")
sm.setParam(36)
sm.sendSay("#face0#你是说#fs18##r死神#k#fs16#啊。")
sm.setParam(56)
sm.sendSay("死神？")
sm.setParam(36)
sm.sendSay("#face0#我当时也在场，\r\n场面太惨了，吓得我好一阵子都睡不着觉。")
sm.sendSay("#face0##fs18##r死人竟然再次复活#k#fs16#\r\n这种事多不吉利啊。")
sm.setParam(56)
sm.sendSay("原来是这样。塔纳……那个死神最后怎么样了？")
sm.setParam(36)
sm.sendSay("#face0#被士兵们带走后就没消息了。其实传闻说……")
sm.sendSay("#face0#说不定那家伙知道。\r\n先前总是四处打探消息。可惜最近一直不见他出现……")
sm.setParam(56)
sm.sendSay("#face0#还有谁啊，当然是#b江#k。")
sm.setParam(36)
sm.sendSay("啊，#b回忆录#k又发光了。")
sm.setParam(56)
sm.sendSay("那是谁啊？")
sm.completeQuestNoCheck(parentID)
sm.createQuestWithQRValue(parentID, "book=1")
sm.sendSay("哦……是江……")
