# id 34259 ([Morass] In Search of the Diary), field 450006240
sm.setSpeakerType(3)
sm.setParam(36)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(3003408) # Researcher
sm.sendNext("#face0#Did you find the Journal?")
sm.setParam(56)
sm.sendNext("Yes. Who wrote this?")
sm.setParam(36)
sm.sendSay("The former High Priest. He resigned shortly after that incident. Here's what he put in his final entry.")
sm.sendSay("'This is neither magic nor science. \r\nIt is beyond human; it is of the gods. \r\n\r\nWe have overstepped our bounds.'")
sm.setParam(56)
sm.sendSay("What does he mean by that?!")
sm.setParam(36)
sm.sendSay("That is why you're here. We needed you to bring High Priest Arkarium.")
sm.setParam(56)
sm.sendSay("Is that why Arkarium...")
sm.setParam(36)
sm.sendSay("Sh! The high priest is coming this way.")
sm.completeQuest(parentID)
