# id 34255 ([Morass] A Frightening Rumor 1), field 993017200
sm.setSpeakerType(3)
sm.setParam(36)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(3003413) # Man
sm.sendNext("#face0#哎呦，谢谢夏伊了。你点的东西马上送到。")
sm.setParam(56)
sm.sendSay("谢谢。")
sm.sendSay("那个……你知道那件惨案吗？")
sm.setParam(36)
sm.sendSay("#face0#你是说……惨案？当然知道。那都是好几年前的事了……\r\n不是在你留学之前发生的吗？")
sm.setParam(56)
sm.sendSay("听说当时有人活下来了，难道是……")
sm.setParam(36)
sm.sendSay("#face0#这、这我不知道。抱歉啊。\r\n不如你去问问其他人吧？")
sm.sendSay("#face0#不然去问问#b瓷器店大婶#k吧？")
sm.consumeItem(4036310, 20)
sm.completeQuestNoCheck(parentID)
