# id 34263 ([Morass] The Prince and the Princess 2), field 450006300
sm.lockInGameUI(True, False)
sm.setSpeakerType(3)
sm.setParam(57)
sm.setColor(1)
sm.sendNext("#face0#很好，干得漂亮！")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(3003406) # Jean
sm.sendSay("等等，这不是反魔力石碎片嘛？呃啊！")
sm.setParam(57)
sm.sendSay("#face1#呼哧，差点出大事了。小心点。")
sm.onLayer(500, "00", 0, 0, 12, "Map/Effect3.img/morass/Jean/3", 4, True, -1, False)
sm.blind(True, 200, 0, 0, 0, 500)
sm.sendDelay(500)
sm.sendDelay(1000)
sm.offLayer(500, "00", False)
sm.blind(False, 0, 0, 0, 0, 500)
sm.sendDelay(500)
sm.setParam(37)
sm.sendNext("#face1#你不记得那个惨案吗？\r\n这东西一旦摔碎，周围的生命就会全部蒸发。")
sm.sendSay("这么危险的东西干嘛带在身上？！")
sm.setParam(57)
sm.sendSay("#face0#你不知道玫瑰带刺吗？\r\n越是美丽的东西就越是危险。我们塔纳就是这样。")
sm.setParam(37)
sm.sendSay("……我看你是彻底被迷住了。")
sm.setParam(57)
sm.sendSay("找到了。原来是项链。")
sm.completeQuestNoCheck(parentID)
sm.moveCamera(True, 0, 0, 0)
sm.lockInGameUI(False, True)
