# id 34263 ([Morass] The Prince and the Princess 2), field 450006300
sm.lockInGameUI(True, False)
sm.setSpeakerType(3)
sm.setParam(57)
sm.setColor(1)
sm.sendNext("Got it! So... it was a necklace!")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(3003406) # Jean
sm.sendSay("#face0#Perfect!")
sm.setParam(57)
sm.sendSay("Wait a minute... this looks like an anti-magic stone fragment. Ah!")
sm.onLayer(500, "00", 0, 0, 12, "Map/Effect3.img/morass/Jean/3", 4, True, -1, False)
sm.blind(True, 200, 0, 0, 0, 500)
sm.sendDelay(500)
sm.sendDelay(1000)
sm.offLayer(500, "00", False)
sm.blind(False, 0, 0, 0, 0, 500)
sm.sendDelay(500)
sm.setParam(37)
sm.sendNext("#face1#Whoa! That was close. Be careful! ")
sm.sendSay("#face1#Don't you remember the last time one of these broke? \r\nShatter this, and every living thing nearby will disappear without a trace.")
sm.setParam(57)
sm.sendSay("Why are you carrying something so dangerous?!")
sm.setParam(37)
sm.sendSay("#face0#Anything worth having comes with a little risk. \r\nThe more beautiful and special something is, the more dangerous... just like Tana.")
sm.setParam(57)
sm.sendSay("Well, you ought to be more careful.")
sm.completeQuestNoCheck(parentID)
sm.moveCamera(True, 0, 0, 0)
sm.lockInGameUI(False, True)
