# id 34258 ([Morass] Truth behind the Rumor), field 450006240
sm.setSpeakerType(3)
sm.setParam(56)
sm.setColor(1)
sm.sendNext("She looks like she's in pain.")
sm.setParam(36)
sm.setInnerOverrideSpeakerTemplateID(3003408) # Researcher
sm.sendSay("#face0#We're only testing whether we can transfer her regenerative power to others. The subject is fine. It's just a side effect of the daily experiments. ")
sm.setParam(56)
sm.sendSay("Daily?")
sm.setParam(36)
sm.sendSay("#face0#Yes. If the experiment fails, the test recipients vanish, but her power enables her body to restore itself perfectly every time. \r\nShe's barely even aware of it happening.")
sm.setParam(56)
sm.sendSay("Isn't this inhumane?")
sm.setParam(36)
sm.sendSay("#face0#Whatever she looks and acts like, she's not human. \r\nWhat you see is a shell formed by the power she possesses.")
sm.sendSay("#face0#She barely even exists at all. She experiences no emotion, desire, or memory.")
sm.setParam(56)
sm.sendSay("But...")
sm.setParam(36)
sm.sendSay("#face0#I'm not explaining this well. The notes in our #bResearch Journal#k explain far better than I can. I'll get it for you.")
sm.completeQuestNoCheck(parentID)
