# id 34259 ([Morass] In Search of the Diary), field 450006240
sm.setSpeakerType(3)
sm.setParam(36)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(3003408) # Researcher
sm.sendNext("#face0#找到文件了吗？")
sm.setParam(56)
sm.sendNext("#face0#那是上任所长。自从爆炸事件后就引咎辞职了。\r\n他最后留下了这么一句话。")
sm.setParam(36)
sm.sendSay("这既非魔法的领域，也不是科学的范畴。")
sm.sendSay("那是人类之上的存在，即#r「神之领域」#k。")
sm.setParam(56)
sm.sendSay("我们正在将手伸向不该碰触的东西。")
sm.setParam(36)
sm.sendSay("神之领域？")
sm.setParam(56)
sm.sendSay("#face0#所以才需要#b夏伊#k大人。为了侍奉大神官大人。")
sm.setParam(36)
sm.sendSay("原来如此。所以阿卡伊勒……")
sm.completeQuest(parentID)
