# id 34258 ([Morass] Truth behind the Rumor), field 450006240
sm.setSpeakerType(3)
sm.setParam(56)
sm.setColor(1)
sm.sendNext("看你那么痛苦，没事吧？")
sm.setParam(36)
sm.setInnerOverrideSpeakerTemplateID(3003408) # Researcher
sm.sendSay("#face0#没关系。这是正常的实验副作用。")
sm.setParam(56)
sm.sendSay("正常？")
sm.setParam(36)
sm.sendSay("#face0#她的身体往往会迅速恢复。\r\n根本不受本人控制。")
sm.setParam(56)
sm.sendSay("这完全有悖人类构造嘛……")
sm.setParam(36)
sm.sendSay("#face0#她并不是人类。\r\n虽然外貌和行为跟人类没什么两样，但总觉得不过是个驱壳而已。")
sm.sendSay("#face0##r#fs18不过是#没有感情、没有欲望、没有回忆的行尸走肉#fs16##k。")
sm.setParam(56)
sm.sendSay("#face0#看来你还没理解。\r\n查看#b研究日志#k应该能有助于你理解。请稍等。")
sm.setParam(36)
sm.sendSay("#face0#I'm not explaining this well. The notes in our #bResearch Journal#k explain far better than I can. I'll get it for you.")
sm.completeQuestNoCheck(parentID)
