# id 34331 ([Lachelein] Decisive Battle), field 450004000
sm.lockInGameUI(True, False)
sm.setSpeakerType(3)
sm.setParam(57)
sm.setColor(1)
sm.sendNext("现在真的都结束了吗？还是还没有结束？！！")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(3003251) # Protective Mask
sm.sendSay("#face0#虽然笼罩城市的梦境还没有消失，但好像告一段落了。")
sm.setParam(57)
sm.sendSay("#face0#梦就是梦，现实就是现实，虽然不是立刻，但梦境将会逐渐减弱。")
sm.setParam(37)
sm.sendSay("可是，如果梦境消失，你也……  ")
sm.setParam(57)
sm.sendSay("#face0#天亮的时候，噩梦消散，这是不变的法则。")
sm.setParam(37)
sm.sendSay("#face0#如果成功拯救了居民和艾尔达，\r\n我存在的意义也算是完成了，现在就算消失也没有关系。")
sm.sendSay("#face0#如果红色迷雾消散，你也会出发去完成你的使命吧。")
sm.setParam(57)
sm.sendSay("#face0#这场旅途肯定充满艰辛，希望你能平安无事。")
sm.setParam(37)
sm.sendSay("可以缩短之前神秘河地区的每日任务。")
sm.sendSay("以后你打算怎么做？")
sm.completeQuestNoCheck(parentID)
sm.lockInGameUI(False, True)
sm.progressMessageFont(3, 20, 10, 0, "You can shorten previous Arcane River area Daily Quests.")
