# id 34467 ([Arcana] Reviving the Bramble Harp 1), field 940200216
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(3003301) # Small Spirit
sm.sendNext("#face1#你收集到了致命尖叫啊！那，那现在就用这个在树生长的反方向……")
sm.completeQuestNoCheck(parentID)
sm.lockInGameUI(True, False)
sm.removeAdditionalEffect()
sm.sendDelay(600)
sm.playExclSoundWithDownBGM("Mob.img/8644005/Die", 100)
sm.sendDelay(1500)
sm.sendNext("#face6#啊，不行，看来光靠致命尖叫似乎还不够。")
sm.sendDelay(1000)
sm.sendNext("#face6#It didn't work. #b(Sighs)#k\r\nIt looks like the noise wasn't loud enough.")
sm.lockInGameUI(False, True)
