# id 34562 ([Esfera] Origin Sea), field 450007000
sm.setSpeakerType(3)
sm.setParam(57)
sm.setColor(1)
sm.sendNext("Anyway... where are we?")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(3003500) # Ollie
sm.sendSay("#face3#Actually, I've got a letter from Neinhart for you. It might answer a few questions you were about to ask.")
sm.lockInGameUI(True, False)
sm.removeAdditionalEffect()
sm.blind(True, 200, 0, 0, 0, 1300)
sm.sendDelay(1600)
sm.sayMonologue("To #h0#", 0)
sm.sayMonologue("It's been a long time, #h0#.", 0)
sm.sayMonologue("This letter was meant to be opened once you reached this new region of the Arcane River, #gEsfera#k.", 0)
sm.setParam(57)
sm.sendNext("Esfera?")
sm.sayMonologue("I'm sure you have many questions, but in the interests of security I will explain to you directly the next time we speak.", 0)
sm.sayMonologue("If all goes as planned, there should be at least one Alliance scout with you at the moment.", 0)
sm.sayMonologue("Have them connect to our communications network so that I may reach you.", 1)
sm.blind(False, 0, 0, 0, 0, 1300)
sm.sendDelay(1600)
sm.setParam(37)
sm.sendNext("#face0#Okay, well, I guess that letter didn't really answer much. But man, look at this place! The #bOrigin Sea#k has a pretty appropriate name, huh?")
sm.setParam(57)
sm.sendSay("How in the world did Neinheart know what kind of place we'd end up in?")
sm.setParam(37)
sm.sendSay("#face0#After the World Tree incident, he's been pretty obsessive about knowing what our enemies are up to all the time.")
sm.sendSay("#face0#I'm as surprised as you that he knew about a place like this! But I'm sure he'll explain everything when you talk to him. Hopefully.")
sm.sendSay("#face0#Our communication uplink is on the ship. Was on the ship. I hope it still exists. And Shubert and Melange too.")
sm.completeQuestNoCheck(parentID)
sm.showFadeTransition(0, 1000, 3000)
sm.zoomCamera(0, 256000, -256, -129, -129)
sm.moveCamera(True, 0, 0, 0)
sm.sendDelay(300)
sm.removeOverlapScreen(1000)
sm.moveCamera(True, 0, 0, 0)
sm.lockInGameUI(False, True)
