# id 34562 ([Esfera] Origin Sea), field 450007000
sm.setSpeakerType(3)
sm.setParam(57)
sm.setColor(1)
sm.sendNext("但是，这是什么地方啊？")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(3003500) # Ollie
sm.sendSay("#face3#这是南哈特的信。")
sm.lockInGameUI(True, False)
sm.removeAdditionalEffect()
sm.blind(True, 200, 0, 0, 0, 1300)
sm.sendDelay(1600)
sm.sayMonologue("To #h0#", 0)
sm.sayMonologue("It's been a long time, #h0#.", 0)
sm.sayMonologue("This letter was meant to be opened once you reached this new region of the Arcane River, #gEsfera#k.", 0)
sm.setParam(57)
sm.sendNext("好久不见，#h0#。")
sm.sayMonologue("I'm sure you have many questions, but in the interests of security I will explain to you directly the next time we speak.", 0)
sm.sayMonologue("If all goes as planned, there should be at least one Alliance scout with you at the moment.", 0)
sm.sayMonologue("Have them connect to our communications network so that I may reach you.", 1)
sm.blind(False, 0, 0, 0, 0, 1300)
sm.sendDelay(1600)
sm.setParam(37)
sm.sendNext("我决定在你到达神秘河海底的巨大空间——\r\n#g「太初之海埃斯佩拉」#k的时候，将这封信交给你。")
sm.setParam(57)
sm.sendSay("你应该会有很多疑问，但由于涉及到保密问题，具体的情况我会直接告诉你。")
sm.setParam(37)
sm.sendSay("按照预定，最少会有1名联盟侦察兵与你同行。")
sm.sendSay("请你让他接通通信装备。")
sm.sendSay("#face0#请环顾一下四周。#b太初之海……#k这个名字真的很适合这里。")
sm.completeQuestNoCheck(parentID)
sm.showFadeTransition(0, 1000, 3000)
sm.zoomCamera(0, 256000, -256, -129, -129)
sm.moveCamera(True, 0, 0, 0)
sm.sendDelay(300)
sm.removeOverlapScreen(1000)
sm.moveCamera(True, 0, 0, 0)
sm.lockInGameUI(False, True)
