#34230 [Esfera]  The Strangers
sm.setSpeakerType(3)
sm.setColor(1)
sm.setParam(56)
sm.sendSay("(This place... I saw it in Tana's memory.)")
sm.setParam(36)
sm.setInnerOverrideSpeakerTemplateID(3003501) #Melange
sm.sendSay("#face0#I think I finally know all that I need to.")
sm.setParam(56)
sm.sendSay("Great, then maybe you can start clearing all of this up! What did that memory mean? What was the voice that Tana, or Aeona, tried to free herself from?")
sm.setParam(36)
sm.sendSay("#face0#I can't be certain of that. What I know for sure is that Tana is the true #bTranscendent of Light#k.")
sm.sendSay("#face0#And that means that the #rBlack Moon#k and the #bWhite Sun#k will fuse.")
sm.setParam(56)
sm.sendSay("Fuse?!")
sm.setParam(36)
sm.sendSay("#face0#When that happens, the power of the #rTranscendents from the two worlds#k will become one. I'd say victory against that great a force is hopeless.")
sm.setParam(56)
sm.sendSay("...")
sm.sendSay("It won't happen if we can stop the ritual. And that means I have to defeat Will.")
sm.setParam(36)
sm.sendSay("#face0#Will is inside the mirror. Heh, a Mirror World within a Mirror World...")
sm.sendSay("#face0#I can't do much else for you. I can't fight in his Mirror World.")
sm.setParam(56)
if sm.sendAskYesNo("Looks like this is it. I'm going in."):
    sm.setParam(36)
    sm.sendSay("#face0#You'll still be able to hear my voice, so I'll advise you as much as I can from here.")
    sm.setParam(56)
    sm.sendSay("(Will is inside. This is it.)")
    if sm.canHold(1712006):
        sm.startQuest(parentID)
        sm.completeQuestNoCheck(parentID)
        sm.completeQuestNoCheck(34586)
        sm.completeQuestNoCheck(34772)
        sm.giveItem(1712006)
        sm.createQuestWithQRValue(34560, "40=h0;41=h0;42=h0;43=h0;44=h0;45=h0;46=h0;47=h0;48=h0;49=h0;50=h0;51=h0;52=h0;53=h0;54=h0;55=h0;56=h0;57=h0")
    else:
        sm.sendSay("I should make one free slot in my equip inventory before accepting this quest.")