# id 34562 ([Esfera] Origin Sea), field 450006330
sm.lockInGameUI(True, False)
sm.removeAdditionalEffect()
sm.zoomCamera(0, 2000, 0, 1450, 63)
sm.sendDelay(1000)
sm.forcedFlip(True)
sm.sendDelay(1200)
sm.sendDelay(1400)
sm.forcedMove(False, 500)
sm.sendDelay(4300)
sm.forcedFlip(True)
sm.sendDelay(500)
sm.setSpeakerType(3)
sm.setParam(57)
sm.setColor(1)
sm.sendNext("Hey there! Cygnus Knights, right? Whatcha up to?")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(3003500) # Ollie
sm.sendSay("#face3#Oh! It's you! Nice to meet you! ")
sm.sendSay("#face3#I'm Ollie! I'm a Cygnus Knights Thunder Breaker assigned to the Arcane River to #bprotect and provide guidance#k!")
sm.setInnerOverrideSpeakerTemplateID(3003502) # Shubert
sm.sendSay("#face0#I'm her partner, Shubert, and I've been tasked to #bkeep the lines open to HQ and keep all our gear running#k. And blow things up that need blowin' up. And this is... ")
sm.setInnerOverrideSpeakerTemplateID(3003501) # Melange
sm.sendSay("#face1#Zzz...")
sm.setInnerOverrideSpeakerTemplateID(3003502) # Shubert
sm.sendSay("#face0#Hey, Melange? ")
sm.setInnerOverrideSpeakerTemplateID(3003501) # Melange
sm.sendSay("#face0#Hahhh... Oh, are we on? Right. I'm Melange. That's... (yawn) ...That's short for Melangioruiana. I'd stick with the short version. Makes me tired just saying it.")
sm.setInnerOverrideSpeakerTemplateID(3003500) # Ollie
sm.sendSay("#face3#Melange is a magician from Pantheon. He can #bcreate a dimensional gate#k that leads back to HQ. Y'know, just in case.")
sm.setParam(57)
sm.sendSay("From Pantheon? Wow, I wasn't expecting to have this kind of support here.")
sm.setParam(37)
sm.sendSay("#face0#Hey, the Empress didn't pull the Alliance together for nothing! We're not just gonna sit around and hand out quests!")
sm.sendSay("#face0#Back in Maple World, the Alliance is gearing up for a #bfull-scale operation#k against the Black Mage. It's been years in the making!")
sm.setParam(57)
sm.sendSay("Everyone's been working so hard...")
sm.setParam(37)
sm.sendSay("#face0#Of course! Our world's at stake!")
sm.showEffect("Effect/OnUserEff.img/emotion/oh", 0, 0, 0, 0, 0, 0, 0)
sm.forcedFlip(True)
sm.sendDelay(1000)
sm.setParam(57)
sm.sendNext("So... were you here looking for this door?")
sm.setParam(37)
sm.sendSay("#face0#Well, we were looking for you. But Melange examined it earlier and told us a transcendent force is sealed somewhere behind it.")
sm.setParam(57)
sm.sendSay("#fc0xFFAAAAAA#(Huh. Maybe that's why it wouldn't open before...)")
sm.sendSay("I wonder if the Flying Fish knows-")
sm.changeBGM("Bgm00.img/Silence", 0, 0)
sm.sendDelay(1000)
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(3003501) # Melange
sm.sendNext("#face0#Ahh... It's opening... ")
sm.setInnerOverrideSpeakerTemplateID(3003500) # Ollie
sm.sendSay("#face3#Huh?")
sm.setMapTaggedObjectVisible("6330_gate", True, 0, 0)
sm.forcedFlip(True)
sm.sendDelay(1000)
sm.setInnerOverrideSpeakerTemplateID(3003502) # Shubert
sm.sendNext("#face1#Wait, the door's opening by itself?")
sm.blind(True, 255, 0, 0, 0, 250)
sm.sendDelay(250)
sm.sendDelay(1000)
sm.playSound("Sound/SoundEff.img/esfera/door2", 1700)
sm.sendDelay(2000)
sm.setInnerOverrideSpeakerTemplateID(3003500) # Ollie
sm.sendNext("#face1#Ahhh! We're being sucked in!")
sm.setInnerOverrideSpeakerTemplateID(3003502) # Shubert
sm.sendSay("#face1#I'll call the patrol ship! Hang on!")
sm.setInnerOverrideSpeakerTemplateID(3003501) # Melange
sm.sendSay("#face1#Zzz zzz...")
sm.setParam(57)
sm.sendSay("HOW ARE YOU STILL ASLEEP?! ")
sm.startQuest(parentID)
sm.showFadeTransition(0, 1000, 3000)
sm.moveCamera(True, 0, 0, 0)
sm.sendDelay(300)
sm.removeOverlapScreen(1000)
sm.moveCamera(True, 0, 0, 0)
sm.lockInGameUI(False, True)
sm.createQuestWithQRValue(34560, "30=h0;40=h0")
sm.warpInstanceOut(450007000)
