# 34658 (Fourth Fighting Tactic, Cadena 4th job adv)
sm.setPlayerAsSpeaker()
if chr.getJob() == 6411:
    sm.sendNext("我已经能够熟练运用支部长传授的技术了。支部长不是说过，这些技术早晚需要更新换代吗？")
    sm.sendSay("好，我会以在战斗中获得的经验为基础，创造出一套我自己的专属技术。")
    sm.sendSay("这种形态似乎不错……好，那东西也放进来试试……我卡德娜大人前无古人，后无来者的技术马上就要成形了……")
    # add stats
    sm.setJob(6412)
    sm.addAP(5)
    sm.addSP(5)
    sm.addMaxHP(350)
    sm.addMaxMP(200)
    sm.sendNext("哈，终于完成了。百分百适合我的专属技术！支部长看到我的新技术一定会大吃一惊吧？")
    sm.sendSayOkay("嘻嘻，不说这个了，我想赶快试验一下我的新技术。快打开技能栏(K)看看吧。")
    sm.completeQuestNoCheck(parentID)