# id 34860 (Wielding the Elder Crystal), field 940202032
sm.startQuest(parentID)
sm.completeQuestNoCheck(parentID)
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(3001353) # Illium
sm.sendNext("#face0#我感觉到#b古代水晶…#k强大的力量了。\r\n如何将这力量用在战斗中呢？")
sm.sendSay("#face0#先使用#b#fUI/UIWindow6/illiumSkillTutorial/0#水晶控制#k，即可#b召唤水晶#k。\r\n处于召唤水晶状态时，即可自由移动到#b我面前#k，按#r↓键#k，水晶#b就能瞬间移动到我的位置吗？#k")
sm.sendSay("#face0#嗯……使用这水晶的力量，应该可以#r增强我的魔法能力#k。")
sm.sendSay("#face0#使用#b#fUI/UIWindow6/illiumSkillTutorial/5##b#fUI/UIWindow6/illiumSkillTutorial/4#秘技技能#k命中水晶后，#r#fUI/UIWindow6/illiumSkillTutorial/1##r,#fUI/UIWindow6/illiumSkillTutorial/2##r反应技能#k会在水晶发动。")
sm.sendSay("#face0#按照这个原理……把水晶转移到#b适当的位置#k，启动#r反应技能#k，就能在战斗时事半功倍了。")
sm.sendSay("#face0#嗯，命中水晶的#b#fUI/UIWindow6/illiumSkillTutorial/4#秘技：标枪#b#fUI/UIWindow6/illiumSkillTutorial/5#秘技：宝珠#k后，#b水晶中好像积累了一些魔力#k了？")
sm.sendSay("#face0#可是#b充入水晶的力量数量#k好像有点不一样啊，如果想迅速充值魔力，最好#r混合使用#k两种技能。")
sm.sendSay("#face0#哦！#b水晶的魔力积累到一定程度#k，#r水晶的外形#k就会改变。\r\n水晶外形改变后，就能使用#b#fUI/UIWindow6/illiumSkillTutorial/3#水晶技能#k了吧？")
sm.sendSay("#face0#虽然暂时#r无法完全掌握#k水晶的力量，但只要认真研究水晶，一定能发挥出#b更强大的力量#k！")
