# id 34902 (Crumbling Abyss), field 402000644
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(3001500) # Ark
sm.sendNext("#face2#I think I might be strong enough to learn more powerful skills now...")
sm.startQuest(parentID)
sm.completeQuestNoCheck(parentID)
sm.completeQuestNoCheck(34907)
sm.setJob(15510)
sm.addMaxHP(350)
sm.addMaxMP(200)
sm.addAP(5)
sm.addSP(5)
sm.giveSkill(155101006)
sm.openUI(2)
sm.sendSay("#face0#With these new skills, I'll be able to fight stronger enemies and help my friends!")
sm.sendSay("#face6#My arm is where the Specter manifests the strongest. It's like it has a mind of its own now.")
sm.sendSay("#face3#If the Specter's strength grows with mine, will I eventually turn into a monster too? Or am I already a monster...?")
