# id 34903 (From the Abyss), field 402000644
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(3001500) # Ark
sm.sendNext("#face6#(呃,怪物的力量沿着左臂……席卷了全身。呃,心脏……好像要炸开了……啊……)")
sm.sendNext("#face6#(神智正在变得模糊……为什么？那个事件之后……我难道没能完全控制住怪物的力量吗……)\r\n\r\n#b(接受时切换地图。)")
sm.sendNext("#face0#Am I special because Albert interrupted the ritual?")
sm.sendNext("#face0#No... I don't know. The only one who can answer this question is that Specter, at least for now. I don't want to, but I'll have to wait until we meet again.")
sm.startQuest(parentID)
sm.completeQuestNoCheck(parentID)
sm.setJob(15511)
sm.addMaxHP(350)
sm.addMaxMP(200)
sm.addAP(5)
sm.addSP(5)
