# id 34916 (Caravan Leader Zippy), field 402000600
sm.lockInGameUI(True, False)
sm.removeAdditionalEffect()
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(3001508) # Zippy
sm.sendNext("#face0#We're travelers seeking paradise, nomads on a never-ending journey for a perfect home.")
sm.sendDelay(500)
sm.blind(True, 255, 0, 0, 0, 500)
sm.sendDelay(500)
sm.onLayer(500, "d0", 0, -80, -1, "Effect/Direction17.img/effect/ark/illust/13/0", 4, True, -1, False)
sm.sendNext("#face0#We started searching long ago.")
sm.sendSay("#face0#My first memory is of seeing the night sky from the beautiful ship we traveled on.")
sm.sendSay("#face2#It truly was a marvelous ship!")
sm.offLayer(300, "d0", False)
sm.onLayer(300, "d1", 0, -80, -1, "Effect/Direction17.img/effect/ark/illust/13/1", 4, True, -1, False)
sm.sendDelay(300)
sm.moveLayer(300, "d1", -30, -30)
sm.sendDelay(300)
sm.moveLayer(300, "d1", 30, -30)
sm.sendDelay(300)
sm.moveLayer(300, "d1", -30, 30)
sm.sendDelay(300)
sm.moveLayer(300, "d1", 30, 30)
sm.sendDelay(300)
sm.sendNext("#face3#But one day, we had to make an emergency landing of sorts... here.")
sm.sendSay("#face2#Unfortunately, this place had a strange sort of vortex that drew our ship toward it.")
sm.sendSay("#face3#We tried everything, but we couldn't escape the planet's pull.")
sm.offLayer(500, "d1", False)
sm.blind(True, 255, 0, 0, 0, 0)
sm.sendDelay(1200)
sm.blind(False, 0, 0, 0, 0, 1000)
sm.sendDelay(1400)
sm.sendNext("#face2#The next thing we knew, we were stuck in this wasteland, and our ship was nowhere to be found...")
sm.sendSay("#face3#After wandering for days, we came to realize there's nothing here, nothing we can use to escape, no one to help us.")
sm.sendSay("#face2#But we were determined. So we gathered every scrap we could find, made this refuge, and began scavenging for food.")
sm.sendSay("#face2#All we can do now is survive and hope that one day we can find a way out of here.")
sm.sendSay("#face0#Then we can begin our search for paradise again. Ferret is always working on ways to find the ship's signal.")
sm.sendSay("#face0#And that's our story. I wish I had more to tell you, but I have to get back to rebuilding the refuge.")
sm.setInnerOverrideSpeakerTemplateID(3001500) # Ark
sm.sendSay("#face0#(Maybe we can't get off-planet right now, but there must be a way...)")
sm.blind(True, 255, 0, 0, 0, 0)
sm.sendDelay(1200)
sm.blind(False, 0, 0, 0, 0, 1000)
sm.sendDelay(1400)
sm.sendDelay(1500)
sm.createQuestWithQRValue(parentID, "exp=1")
sm.completeQuestNoCheck(parentID)
sm.lockInGameUI(False, True)
