# id 35903 (Power of the Relic), field 910090305
sm.setSpeakerType(3)
sm.setParam(548)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(1013358) # Pathfinder
sm.sendNext("#face0##b（和遗物接触后，古代之力进入了我的身体。\r\n……但同时也多了诅咒这个大问题。）#k")
sm.sendSay("#face6##b（好吧，事情都已经发生了，还能怎么办呢。\r\n后悔也没办法解决问题。还是应该保持一颗平常心。）#k")
res = sm.sendAskAccept("#face0##b在开始调查之前，先来检查一下状态吧。\r\n集中精神，感觉身体内部发生的变化。）#k")
sm.completeQuestNoCheck(parentID)
sm.openUI(1)
sm.setParam(549)
sm.sendNext("#face0##b（受到诅咒之后，就能使用远古弓了。\r\n以后就用这个吧。）#k")
sm.sendSay("#face0##b（触碰遗物之后，获得了一些新技能。\r\n按基本键(K)，试着分配SP吧。常用的技能可以添加到快捷栏中。）#k")
sm.openUI(2)
sm.sendSay("#face0##b（接下来……用基本快捷键(S) / 选择型(C)分配AP吧。\r\n这段时间等级提升了，应该会有一些AP。）#k")
sm.sendSay("#face3#好像已经准备好了。那就去周围……")
sm.playSound("Sound/SoundEff.img/pathfinder/mascapo", 100)
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(1013353) # Mascarpo
sm.sendSay("#face0#……救我！")
sm.sendSay("#face0#咕哎哎！")
sm.sendSay("#face3#那边传来了奇怪的声音。\r\n准备好之后，去确认一下发生了什么事吧。")
sm.setParam(549)
sm.setInnerOverrideSpeakerTemplateID(1013358) # Pathfinder
sm.sendSay("#face0#Bwah--!")
sm.sendSay("#face3#That's an awfully weird sound, and it's coming from somewhere nearby. After I've looked around a bit more, I'll go see what's up.")
