# id 35929 (Assuaged Fears), field 100051040
sm.setSpeakerType(3)
sm.setParam(36)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(1013350) # Brie
sm.sendNext("#face0#既然找到了答案,就快点离开这里吧,勇士？\r\n啊,对了……按照约定,现在我不会再跟着你了。")
sm.sendSay("#face0#不管你要去哪里,都希望你能多保重。\r\n虽然我很笨,又很胆小……还是谢谢你能带我一起来。")
sm.setSpeakerType(4)
sm.setSpeakerID(1013319) # Brie
res = sm.sendAskAccept("#face0#啊,如果你想再来我们卡鲁帕村……\r\n你想接受吗？这是可以随时来到这里的技能。")
sm.lockInGameUI(True, False)
sm.removeAdditionalEffect()
sm.progressMessageFont(3, 20, 4, 0, "You acquired the 'Return to Partem' skill.")
sm.sendDelay(500)
sm.setSpeakerType(3)
sm.setParam(37)
sm.sendNext("获得了<返回帕勒坦>技能。")
sm.sendSay("获得了<返回帕勒坦>技能。")
sm.sendSay("#face0#嘿嘿,希望什么时候能再见面。\r\n我会一直在这里等待着你的到来。")
sm.sendSay("#face2#我会把在废墟听到的事情告诉卡鲁帕们。\r\n虽然不知道大家会不会相信。啊,高尔根说不定会相信的,嘿嘿。")
sm.sendDelay(500)
sm.blind(True, 255, 0, 0, 0, 500)
sm.sendDelay(500)
sm.sendDelay(500)
sm.setParam(549)
sm.setInnerOverrideSpeakerTemplateID(1013358) # Pathfinder
sm.sendNext("#face0#呼……虽然没什么自信,但我会鼓起勇气的。\r\n将来的某一天,我也能成为像你一样勇敢的人吗？")
sm.sendDelay(1000)
sm.sendNext("#face0#呃啊,我又在胡说八道什么呢……\r\n现在你可以走了。我也该走了。再见！")
sm.sendSay("#face0#只顾自己说完就走掉了。是啊,你也要保重。")
sm.sendSay("#face0#事情总算暂时告一段落了……。")
sm.sendDelay(500)
sm.sendNext("#face1##b(诅咒之力没办法消除,那就只能勇敢面对了。\r\n我一定要将遗物的力量完全掌握在手中。)#k")
sm.sendSay("#face0##b(通过冒险让自己变得更强,是吧？\r\n既然知道了克服诅咒的方法,那就继续去冒险吧。)#k")
sm.sendDelay(1000)
sm.showFadeTransition(0, 1000, 3000)
sm.zoomCamera(0, 1000, 2147483647, 2147483647, 2147483647)
sm.moveCamera(True, 0, 0, 0)
sm.sendDelay(300)
sm.removeOverlapScreen(1000)
sm.moveCamera(True, 0, 0, 0)
sm.lockInGameUI(False, True)
sm.warp(910090314)
