# id 37157 ([Elodin] Nature's Roadblocks 2), field 101081000
sm.setSpeakerType(3)
sm.setParam(2)
sm.sendNext("呼……呼……\r\n已经过了多久了 ？")
sm.sendSay("怎么会一直在一个地方徘徊不前呢……")
sm.sendSay("而且怪物的数量不减反增。")
res = sm.sendAskYesNo("不赶快杀出一条路摆脱它们 ，恐怕要永远出不去了。")
sm.setParam(3)
sm.sendNext("I hope I'm going the right way...")
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
