# id 37901 ([Sellas] How to Fix a Radio), field 450007000
sm.setSpeakerType(3)
sm.setParam(56)
sm.setColor(1)
sm.sendNext("Hey, Shubert.")
sm.setParam(36)
sm.setInnerOverrideSpeakerTemplateID(3003502) # Shubert
sm.sendSay("#face0#Oh hey, #h0#. Welcome.")
sm.setParam(56)
sm.sendSay("What's going on?")
sm.setParam(36)
sm.sendSay("#face0#... Nothing.\r\nI just have to take care of something before I head back to Edelstein.")
sm.setParam(56)
sm.sendSay("Back to Edelstein?")
sm.setParam(36)
sm.sendSay("#face0#Yep, the mission's pretty much over now. Time for me to pack it up.")
sm.sendSay("#face0#But, uh... well, since you're here, I might as well show you around.")
sm.sendSay("#face0#Come on, this way.")
sm.completeQuestNoCheck(parentID)
sm.startQuest(37902)
sm.createQuestWithQRValue(37900, "00=h0;41=h0")
sm.createQuestWithQRValue(37900, "00=h0;01=h1;41=h0")
