# id 37903 ([Sellas] Underwater Operation), field 450007040
sm.setSpeakerType(3)
sm.setParam(56)
sm.setColor(1)
sm.sendNext("有#b发光的东西#k沉到了水底？")
sm.setParam(36)
sm.setInnerOverrideSpeakerTemplateID(3003500) # Ollie
sm.sendSay("#face3#是的。")
sm.setParam(56)
sm.sendSay("那是什么样的东西，你有头绪吗？")
sm.setParam(36)
sm.setInnerOverrideSpeakerTemplateID(1540451) # Neinheart
sm.sendSay("#face2#不，我们没掌握任何相关信息。\r\n在直接将它打捞出来之前，根本不知道究竟是什么样的物品。")
sm.sendSay("#face2#但那是#r光明超越者#k身上携带的东西。\r\n我认为不是寻常之物。")
sm.setParam(56)
sm.sendSay("嗯……为了找个毫无线索的东西，就要潜入未知的海底吗……")
sm.setParam(36)
sm.sendSay("#face2#是的……\r\n老实说，我也不太愿意开展此次作战……\r\n但这种不想放过任何一丝希望的心情，希望你们能理解。")
sm.sendSay("#face2#想到接下来我们#r联盟要去的地方#k，说真的，\r\n心里不得不期待能出现侥幸。")
sm.setParam(56)
sm.sendSay("#face2#所以我准备组织这次的作战队伍，\r\n首先第一位队员就是你，\r\n#b#h0##k。")
sm.setParam(36)
sm.sendSay("#face2#对付未知的怪物，没人比你更拿手。\r\n当然，是否参加全看#b#h0##k你自己的意思。")
sm.sendSay("(沉没的某物……。去找找吧？)")
sm.setSpeakerType(4)
sm.setSpeakerID(3003530) # Ollie
sm.setParam(56)
res = sm.sendAskYesNo("#face2#谢谢你这次也欣然答应。\r\n让我松了口气。")
sm.startQuest(parentID)
sm.setSpeakerType(3)
sm.setParam(36)
sm.sendNext("#face2#*Sigh* Thank you. It's quite a relief to hear you say that, if I'm being honest.")
