# id 37903 ([Sellas] Underwater Operation), field 450007040
sm.setSpeakerType(3)
sm.setParam(56)
sm.setColor(1)
sm.sendNext("#bSome shiny object#k sank deeper underwater?")
sm.setParam(36)
sm.setInnerOverrideSpeakerTemplateID(3003500) # Ollie
sm.sendSay("#face3#That's what it looked like.")
sm.setParam(56)
sm.sendSay("Do we have any guesses on what it might be?")
sm.setParam(36)
sm.setInnerOverrideSpeakerTemplateID(1540451) # Neinheart
sm.sendSay("#face2#None. We have zero intel on the object.\r\nI'm afraid the only way to find out is to recover it ourselves.")
sm.sendSay("#face2#But I will say this: given that it came from the #rTrascendent of Light#k... it's certainly no ordinary trinket.")
sm.setParam(56)
sm.sendSay("Hmm... So we're looking for one small, unknown object at the bottom of a deep, dark sea...")
sm.setParam(36)
sm.sendSay("#face2#Indeed we are. Not ideal, of course, but... I hope you understand our lack of options.")
sm.sendSay("#face2#Given #rour Alliance's destination#k, any possible help is worth reaching for.")
sm.setParam(56)
sm.sendSay("Hmm...")
sm.setParam(36)
sm.sendSay("#face2#We're assembling a task force to retrieve the object.\r\nYou, #h0#, were of course at the top of our list.")
sm.sendSay("#face2#When it comes to unknown dangers in unknown territory, you are second to none, and we'd be honored and fortunate to have you. Of course, as always, the choice is yours.")
sm.setSpeakerType(4)
sm.setSpeakerID(3003530) # Ollie
sm.setParam(56)
res = sm.sendAskYesNo("(Searching the ocean for sunken treasure... Should I give it a shot?)")
sm.startQuest(parentID)
sm.setSpeakerType(3)
sm.setParam(36)
sm.sendNext("#face2#*Sigh* Thank you. It's quite a relief to hear you say that, if I'm being honest.")
