# Jett 2nd job adv
sm.setSpeakerID(9270091)
sm.sendNext("Who dares disturb the greatest blacksmith in the world as he contemplates the co-valence of barbon-based binding agents?!")
sm.setPlayerAsSpeaker()
sm.sendNext("That was a lot of words, smithy. My name is #b#h ##k and I wanted to know if you can fix this.")
sm.setSpeakerID(9270091)
sm.sendNext("Ah, you are that 'alien' Kyrin spoke of. I will take a moment from pondering the boundless depths of our physical world to take a look at your problem. You called it a 'core'?")
sm.sendNext("............")
sm.sendNext("The stone's atomic structure is quite foreign. It is indeed from another world. Where does this come from?")
sm.setPlayerAsSpeaker()
sm.sendNext("It's... a long story. Do you think you can fix it?")
sm.setSpeakerID(9270091)
sm.sendNext("It is an odd piece of technology. But it is not outside my understanding. Bring me some #bBlue Ore#k. It should create a sort of energy barrier that will hold it together.")
sm.setPlayerAsSpeaker()
sm.sendNext("Where do I find #bBlue Ore#k?")
sm.setSpeakerID(9270091)
if sm.sendAskYesNo("If you are up to a challenge, you'll have your best luck in the depths of the #bBlue Ore Cave#k. It's quite deep and quite full of monsters, if you leave early, you will have to #bforfeit the quest and start again#k. Be sure to be prepared before you enter."):
    sm.startQuest(parentID)
    sm.warp(552000072)