# Jett 3rd job adv
sm.setSpeakerID(9270091)
sm.sendNext("Ah, #b#h ##k. I'm sure your core is better than it ever was. My calculations must have improved it ten--")
sm.setPlayerAsSpeaker()
sm.sendNext("It's a mess, #bThunder Hammer#k, I was coming to see you.")
sm.setSpeakerID(9270091)
if sm.sendAskYesNo("Are you trying to tell me that you broke the item I so perfectly fixed for you?"):
    sm.setPlayerAsSpeaker()
    sm.sendNext("It's been stable for a while, but I've noticed a lot more cracks showing up lately under the strain")
    sm.setSpeakerID(9270091)
    sm.sendNext("Blast it! #bBlue Ore#k isn't strong enough to handle the power output on this device! I should have known... You are going to need a much stronger compound to channel that energy.")
    sm.setPlayerAsSpeaker()
    sm.sendNext("Can we do something about it?")
    sm.setSpeakerID(9270091)
    sm.sendNext("Of course it can! A smithy always finds a way. But we will need stronger bonding agents to harden the coating..")
    sm.setPlayerAsSpeaker()
    sm.sendNext("What do we need? I'm not about to let the core break again.")
    sm.setSpeakerID(9270091)
    sm.sendNext("#bFire Ore#k has some very unique strengthening properties. It develops in the Blast Furnace, but it's quite hard to get in proper quantities.")
    sm.setPlayerAsSpeaker()
    sm.sendNext("I'll head into the #bBlast Furnace#k. What's a little furnace gonna do to me that space hasn't already?")
    sm.setSpeakerID(9270091)
    if sm.sendAskYesNo("A foolish anecdote at best, but I'm sure you know your limits. Remember to take enough potions, because if you have to quit before you succeed, #byou must forfeit the quest and start again#k."):
        sm.startQuest(parentID)
        sm.warp(552000073)