# Jett 4th job adv
sm.setSpeakerID(2111007)
sm.sendNext("#h #, I need your help! I have a deadline right around the corner and my client is breathing down my neck.")
sm.setPlayerAsSpeaker()
sm.sendNext("#p2111007#? What kind of low-down scheme are you running now?")
sm.setSpeakerID(2111007)
sm.sendNext("No scheme! I swear it. But I need someone with a little discretion. No one on the outside must know. Will you help me?")
sm.setPlayerAsSpeaker()
sm.sendNext("Spill the beans and I'll think about it.")
sm.setSpeakerID(2111007)
if sm.sendAskYesNo("I can't tell you anything untill you agree to help. I swear I will make it worth your while. What do you say?"):
    sm.sendNext("I had a feeling you couldn't resist a good surprise.")
    sm.sendNext("A couple of days ago, I received an order from a secret organization.")
    sm.setPlayerAsSpeaker()
    sm.sendNext("And you don't want anybody to know what you're cooking up?")
    sm.setSpeakerID(2111007)
    sm.sendNext("I prefer to keep my trade secrets to myself. The client asked me to make a #bMatter Disassembler#k, based on an old alchemy manuscript he found. The pay is VERY handsome.")
    sm.setPlayerAsSpeaker()
    sm.sendNext("#b(Matter Disassembler? That sounds like a dangerous thing to have...)")
    sm.sendNext("The client... You know him?")
    sm.setSpeakerID(2111007)
    sm.sendNext("No, I don't knwo him and I do not wish to! I need the ingredients and I need them immediately. The recipe calls for #b50#k sets of #bPiece of Steel#k, a #bHardened Piece of Steel#k, and #bWires#k bound together with magic. You will need to attack #r#o2600505# #o2600506##r and #r#o2600515##r machines to find them. Make sure no one sees you!")
    sm.setPlayerAsSpeaker()
    sm.sendNext("#b(This client sounds like somebody I oughtta set my eyes on...)")
    sm.startQuest(parentID)
