# id 58955 (Will of the Five Planets), field 811000008
sm.setSpeakerID(9130104) # Princess Sakuno
sm.sendNext("…....发生了一件非常遗憾的事情。")
sm.setParam(2)
sm.sendSay("怎么了？")
sm.setParam(0)
sm.sendSay("因为织田信长和浓姬的第二次时空转移，正在产生不稳定的气息。再这样下去，冒险岛世界终究会被时空转移，我们可能都会消失的。")
sm.setParam(2)
sm.sendSay("难道没有办法能阻止他们吗？")
sm.setParam(0)
sm.sendSay("为了第二次时空转移而召唤的魔王既没有进浓姬体内，也没有回自己原来的所在之地。为了把魔王送回去，必须消灭召唤者浓姬。")
sm.sendSay("五星的意志……为了帮助我们，留下了口信。这应该有助于我们消灭浓姬。")
sm.sendSay("战士要维承火之言灵，法师是水之言灵，弓箭手是木之言灵，盗贼是金之言灵，海盗是土之言灵。")
sm.sendSay("这下我们必须消灭浓姬的理由就变得更加明确了。")
sm.completeQuestNoCheck(parentID)
sm.createQuestWithQRValue(18418, "B=35674")
