# id 58914 ([Hieizan Temple] Sad Little Boy), field 811000014
sm.setSpeakerID(9130107) # Mysterious Boy
sm.setParam(4)
sm.setInnerOverrideSpeakerTemplateID(9130107) # Mysterious Boy
sm.sendNext("呜……呜……")
sm.setParam(16)
sm.sendSay("(在这里居然有这样的少年。太奇怪了。而且还在哭……还是不要管他为好。)")
sm.setParam(4)
res = sm.sendAskYesNo("呜……呜呜……嗯？人……人……！请你帮帮我！")
sm.startQuest(parentID)
sm.startQuest(58979)
sm.setParam(16)
sm.sendNext("((真是的……) 怎么了？")
sm.setParam(4)
sm.sendSay("呜呜，我是照看盟军马的侍童，被人从哨所带到了这里。我因为受到冲击，昏了过去，一睁眼就在这儿了。")
sm.setParam(16)
sm.sendSay(" (盟军在这里？)……其他盟军士兵去哪里了？")
sm.setParam(4)
sm.sendSay("士兵们都变得好奇怪……好……好可怕。我想离开这里，请你帮我找找我的行李吧。")
sm.sendSay("那是我父亲最后留下的遗物。应该是掉在这附近了……但是因为太黑了，看不清在哪儿。")
sm.sendSay("那是个非常漂亮有花纹的包裹。")
