# 59000 - The Town Prankster
sm.setPlayerAsSpeaker()
sm.sendNext("赫卡大嫂,对不起……")
sm.setSpeakerID(9390305)
sm.sendNext("你这捣什么蛋啦?")
sm.setPlayerAsSpeaker()
sm.sendNext("是,对不起。我只是想让大家快乐……")
sm.setSpeakerID(9390305)
sm.sendNext("哎,每天都吊儿郎当的……好吧,这次我就放过你,不过绝对不会有下次咯?")
sm.completeQuest(parentID)
sm.dispose()
