# id 64067 ([MONAD: The First Omen] Treatment Necessities), field 867201100
sm.lockInGameUI(True, False)
sm.forcedFlip(True)
sm.blind(True, 255, 0, 0, 0, 0)
sm.sendDelay(100)
sm.blind(False, 0, 0, 0, 0, 250)
sm.sendDelay(300)
sm.moveNpcByTemplateId(9400580, True, 20, 20)
sm.showNpcSpecialActionByTemplateId(9400584, "skill2", 0)
sm.sendDelay(2000)
sm.flipNpcByTemplateId(9400580, False)
sm.sendDelay(250)
sm.moveNpcByTemplateId(9400580, False, 20, 20)
sm.setSpeakerType(3)
sm.setParam(57)
sm.setColor(1)
sm.sendNext("#b(……看来她正忙着照顾伤员。) ")
sm.sendSay("#b(没什么我能帮忙做的吗……) ")
sm.forcedMove(False, 30)
sm.sendDelay(500)
sm.sendNext("#b扎奈特，我能帮你什么吗？")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400584) # Janyt
sm.sendSay("#face0#啊……不用了，我只要有亚皮纳斯的祝福就够了。")
sm.setParam(57)
sm.sendSay("#b但是你需不需要……")
sm.setParam(37)
sm.sendSay("#face0#不需要。")
sm.setInnerOverrideSpeakerTemplateID(9400580) # Alika
sm.sendSay("#b啊，艾丽卡，我在想有没有什么我能帮得上忙的地方。")
sm.flipNpcByTemplateId(9400580, True)
sm.sendDelay(250)
sm.moveNpcByTemplateId(9400580, True, 60, 30)
sm.sendDelay(500)
sm.setParam(57)
sm.sendNext("#face0#那可就多了！")
sm.setParam(37)
sm.sendSay("#face0#你能先去帮我找来一些治疗需要的材料吗？")
sm.sendSay("#face0#你也看到了，我们救护队和扎奈特的治愈能力都有限……我们都已经很累了，药物也有些不足……")
sm.sendSay("#b当然了，但是这里有能作为药材的东西吗？")
sm.setParam(57)
sm.sendSay("#face0#幸好在阿布鲁的民间疗法中，有用小白雪鬼的结晶融化后来涂抹的方法。虽然这个方法的疗效尚未得到证实，但是受伤的猎人都那么说，我也只能试一试了。")
sm.setParam(37)
sm.sendSay("#face0#据说在江附近的雪原就有小白雪鬼，凯恩也已经过去了，你应该很容易就能找到的。")
sm.sendSay("#face1#I was told that the leatty gather on the snowfield near the river. Cayne is already there, so you can look for him. ")
sm.startQuest(parentID)
sm.sendDelay(2000)
sm.lockInGameUI(False, True)
sm.warp(867201180)
