# id 64036 ([MONAD: The First Omen] Leader of the Dispatch), field 867200800
sm.lockInGameUI(True, False)
sm.startQuest(parentID)
sm.moveNpcByTemplateId(9400581, True, 50, 50)
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(9400581) # Butler
sm.sendNext("#face0#我承认，你是位有能力，又胆识过人的勇士，但你太缺乏经验了。")
sm.setParam(57)
sm.sendSay("#face0#正如可汗村长身边有佩图尔那么优秀的顾问兼人生前辈，我觉得你也很需要一个可以毫不吝啬地给你忠告的建议者。")
sm.setParam(37)
sm.sendSay("#face0#……你真觉得休息一下再走是明智的选择吗？")
sm.sendSay("#b身后有暴风雪在追赶，四面八方还不知何时会有怪物来袭……我很明白这是个有风险的选择。")
sm.sendSay("#b但正如艾丽卡所说，如果强行前进，将会有些太疲倦的人掉队。")
sm.sendDelay(2000)
sm.setParam(57)
sm.sendNext("#face1#不，你错了。现在就应该强行前进。")
sm.sendSay("#face1#在疲惫的情况下让他们有时间思考只会令他们更加绝望。")
sm.setParam(37)
sm.sendSay("#face1#根本不要给他们时间和余裕去思考！你得让他们脑海中只想着“我得去下个村庄！”这一目标。")
sm.sendSay("#b这个方法或许对骑士们有效，可这些人大部分只是普通的村民啊。")
sm.sendSay("#face0#我在成为骑士之前，也曾做过很长时间的佣兵，就像你一样。")
sm.setParam(57)
sm.sendSay("#face0#换句话说，我跟这种普通百姓相处的时间比跟那些训练有素的骑士多得多。你不要忽视我的经验之谈。")
sm.sendDelay(2000)
sm.setParam(37)
sm.sendNext("#face0#很快你就会发现目前的选择是错误的，到时再后悔可就晚了。")
sm.sendSay("#b……谢谢你的忠告。")
sm.sendSay("#face0#你要记住，谁才是给你提供所需建议和忠告的人。")
sm.setParam(57)
sm.sendSay("#face0#啊-，还有一件事。你要是觉得担不起这个需要负责任的位置，随时可以让给我。")
sm.setParam(37)
sm.sendSay("#face0#Remember well who gives you the advice and counsel you need. ")
sm.sendDelay(500)
sm.flipNpcByTemplateId(9400581, False)
sm.sendDelay(250)
sm.moveNpcByTemplateId(9400581, False, 70, 100)
sm.sendDelay(2500)
sm.flipNpcByTemplateId(9400581, True)
sm.sendDelay(500)
sm.sendNext("#face0#Ah, and just as a reminder... if the pressures of leadership are too much for you, I'd be happy to take over at any time. ")
sm.sendDelay(250)
sm.flipNpcByTemplateId(9400581, False)
sm.sendDelay(250)
sm.sendDelay(1500)
sm.lockInGameUI(False, True)
sm.completeQuestNoCheck(parentID)
