# id 64080 ([MONAD: The First Omen] Night in the Forest), field 867201600
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(9400580) # Alika
sm.sendNext("#face0#你回来了？")
sm.setParam(57)
sm.sendSay("#b你一个人生了火？")
sm.setParam(37)
sm.sendSay("#face2#嘿嘿，之前#h0#不是告诉了我怎么做嘛。")
sm.setParam(57)
sm.sendSay("#b啊，在煮汤的时候？……一个人生火还挺难的呢……")
sm.sendSay("#b啊，你的手都受伤了啊！")
sm.setParam(37)
sm.sendSay("#face0#没关系，#h0#应该也累了……我们快休息下吧。")
sm.setParam(57)
sm.sendSay("#b……谢谢你，你做得很好。")
sm.lockInGameUI(True, False)
sm.showEffect("Effect/OnUserEff.img/emotion/oh", 0, 0, 0, 0, 25, 0, 0)
sm.sendDelay(1000)
sm.setParam(37)
sm.sendNext("#face3#啊……难道那是……")
sm.sendSay("#face3#小石啊，闭上眼……")
sm.completeQuestNoCheck(parentID)
sm.startQuest(64081)
sm.blind(True, 255, 0, 0, 0, 500)
sm.sendDelay(500)
sm.lockInGameUI(False, True)
sm.warp(867201601)
