# id 64062 ([MONAD: The First Omen] Actinops), field 867201100
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(9400598) # Thorson
sm.sendNext("勇，勇士！等一下！")
sm.setParam(57)
sm.sendSay("我们曾经是捕鱼的渔夫。那个……在我们村子里出现的怪物……")
sm.setParam(37)
sm.sendSay("#b剧毒打嗝怪？")
sm.setParam(57)
sm.sendSay("啊！你是这么叫那个怪物的！？")
sm.setParam(37)
sm.sendSay("#b啊……没，有个话唠骑士是这么叫它的。")
sm.setParam(57)
sm.sendSay("#b那个？")
sm.setParam(37)
sm.sendSay("它似乎是我们以前抓到的埃特金森！")
sm.setParam(57)
sm.sendSay("啊！埃特金森是连血都是透明的鱼！虽然长得很恶心，但是作为阿布鲁地区的特产，味道很棒！")
sm.setParam(37)
sm.sendSay("#b但那是粉红色的……大小也不像是鱼啊。")
sm.setParam(57)
sm.sendSay("我也看到了！如果是吃了粉红色的什么……可能就会变色。但是移动的时候就会变透明了。啊，不只是这样！")
sm.setParam(37)
sm.sendSay("埃特金森本来再生能力就很强！甚至在自己觉得安全的时候还会继续长大，总之它能自由地延展身体。")
sm.setParam(57)
sm.sendSay("你看到……它把右手伸长的样子了吗？")
sm.setParam(37)
sm.sendSay("你还不相信吗？还有！")
sm.sendSay("正是那个毒！那个毒！埃特金森也是有毒的鱼！")
sm.sendSay("如果，那个真的是埃特金森……")
sm.setParam(57)
sm.sendSay("#b如果是埃特金森？")
sm.setParam(37)
sm.sendSay("如果是埃特金森……")
sm.sendSay("为了再生而集中的那个时候！如果在那时行动的话，它是不会攻击的。我们应该要抓住那个时机！")
sm.sendSay("#b(……确实在它伸长手臂攻击后，有一段时间它是没有任何动静的……) ")
sm.setParam(57)
sm.sendSay("但，其实……我虽然这么说，但这事儿其实有点奇怪。")
sm.setParam(37)
sm.sendSay("明明看起来很像埃特金森，但是那么小一条鱼是怎么变成那样的怪物的呢。")
sm.sendSay("#b谢谢你能告诉我这些。")
sm.setParam(57)
sm.sendSay("啊，没事！如果能帮上忙那就太好了！")
sm.setParam(37)
sm.sendSay("如果你有什么想知道的事情，请随时来问我！")
sm.sendSay("那个……")
sm.setParam(57)
sm.sendSay("#b……那是？")
sm.setParam(37)
sm.sendSay("#b好的，我知道了。")
sm.sendSay("If you have any questions about anything, you can ask me! ")
sm.setParam(57)
sm.sendSay("#bYes, will do. ")
sm.setParam(37)
sm.sendSay("...Whew!")
sm.completeQuestNoCheck(parentID)
