# id 64071 ([MONAD: The First Omen] Svarti Heirloom), field 867201050
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(9400598) # Thorson
sm.sendNext("勇，勇士！你真的要去吗？！")
sm.setParam(57)
sm.sendSay("#b是的，我正打算去呢。")
sm.setParam(37)
sm.sendSay("哎呀！真的……现在森林里真的很危险啊……")
sm.sendSay("如果村长知道了，可能会杀了我，但是……哎呀！请你拿着这个。")
sm.completeQuestNoCheck(parentID)
sm.sendSay("#b你要把这个给我……？")
sm.setParam(57)
sm.sendSay("比起我们，勇士应该更需要这个吧！我一直在等着这一天，我也想帮助勇士！")
sm.setParam(37)
sm.sendSay("#b谢谢你，托尔逊。我更希望我用不上这个呢。等我回来后再还给你。")
sm.setParam(57)
sm.sendSay("好的，那就请你早去早回吧！希望沉睡森林的呼吸与你同在！")
sm.setParam(37)
sm.sendSay("副本_莫奈德_Act2_探索森林")
sm.lockInGameUI(True, False)
sm.sendDelay(500)
sm.forcedFlip(True)
sm.forcedMove(True, 309)
sm.sendDelay(501)
sm.sendDelay(1000)
sm.lockInGameUI(False, True)
sm.createQuestWithQRValue(64008, "mapIdx=0")
sm.warp(867201200)
