# id 64087 ([MONAD: The First Omen] Alika's Research Materials), field 867202300
sm.completeQuestNoCheck(parentID)
sm.setSpeakerType(3)
sm.setParam(57)
sm.setColor(1)
sm.sendNext("#b艾丽卡，拿着这个。")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400580) # Alika
sm.sendSay("#face0#这是什么？")
sm.sendSay("#face0#难道……这是？")
sm.sendSay("#face2#啊！透明的埃特金森的皮肤组织……？难道是因为我在森林里说的那些……？")
sm.setParam(57)
sm.sendSay("#b希望这能有助于你的研究。")
sm.setParam(37)
sm.sendSay("#face0#真的谢谢你！其实我本来觉得就这么空手回到亚皮纳斯，有些不好意思，也有些遗憾。")
sm.sendSay("#face0#虽然因为还有更重要的事情，所以没能说出口……但是真的没想到啊，我该怎么报答你呢？")
sm.setParam(57)
sm.sendSay("#b不需要报答，这也不是什么困难的事情。")
sm.setParam(37)
sm.sendSay("#face3#真的？明明在森林里消灭冰霜巨人就很困难……")
sm.setParam(57)
sm.sendSay("#b……艾丽卡能开心就好了。")
