# id 64025 ([MONAD: The First Omen] Evacuation Prep), field 867200400
sm.completeQuestNoCheck(parentID)
sm.showNpcSpecialActionByTemplateId(9400588, "summon", 0)
sm.showNpcSpecialActionByTemplateId(9400587, "summon", 0)
sm.showNpcSpecialActionByTemplateId(9400616, "summon", 0)
sm.startQuest(64160)
sm.startQuest(64166)
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(9400589) # Peytour
sm.sendNext("#face0#你回来得正是时候，辛苦了！")
sm.sendSay("#face0#我把车上的雪清掉后，看着还不错，现在开始修理吧……")
sm.sendSay("#face0#啊~~你在卡夫塔佩没有要带的行李吧？比如地契或者金器啥的。")
sm.setParam(57)
sm.sendSay("#face0#……开玩笑的。我是想问你，要是现在不忙，能不能去巡视一下看村民们准备得怎么样。")
sm.setParam(37)
sm.sendSay("#b啊……好的。")
sm.setParam(57)
sm.sendSay("#face0#多谢，那待会儿见。")
sm.setParam(37)
sm.sendSay("#face0#Thanks. I'll see you in a bit.")
