# id 64029 ([MONAD: The First Omen] Essentials), field 867200400
sm.setMapTaggedObjectVisible("guide136", False, 0, 0)
sm.setMapTaggedObjectVisible("guide137", False, 0, 0)
sm.setMapTaggedObjectVisible("guide135", False, 0, 0)
sm.setSpeakerType(3)
sm.setParam(57)
sm.setColor(1)
sm.sendNext("#b（……这都被火烧焦了，还沾满了灰，不能吃了……）")
sm.sendSay("#b（得想个其他办法弄到食物。）")
sm.sendSay("#b（去找佩图尔商量一下。）")
sm.completeQuestNoCheck(parentID)
