# id 64065 ([MONAD: The First Omen] Butler's Dilemma), field 867201100
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(9400581) # Butler
sm.sendNext("#face0#真是难以置信，就算再怎么累，居然向普通人寻求帮助。")
sm.setParam(57)
sm.sendSay("#b……我觉得他们需要恢复体力的时间。")
sm.setParam(37)
sm.sendSay("#face0#在现在这种紧急的战时情况下，松懈就等于失败。")
sm.sendSay("#face0#我年轻的时候，为了追击敌人，好几天不吃不睡。但是你们三餐都好好吃着，每天还能睡在火堆旁边，居然还敢说出这种话！我无法容忍。")
sm.sendSay("#face0#本来我就因为在士兵间流传着在卡夫塔佩战斗时见到了巨大影子的传闻而头疼来着……")
sm.setParam(57)
sm.sendSay("#b巨大的影子？")
sm.setParam(37)
sm.sendSay("#face0#是啊，你不会也害怕吧？")
sm.setParam(57)
sm.sendSay("#b这是谁说的？")
sm.setParam(37)
sm.sendSay("#face0#之前在这里休息的士兵威尔森说的。这就说明他精神松懈到了那种程度了。你现在明白了吗？")
sm.setParam(57)
sm.sendSay("#b(……又一个目击者！和他谈谈吧。) ")
sm.setParam(37)
sm.sendSay("#b谢谢，巴特勒副团长。我先走了……")
sm.setParam(57)
sm.sendSay("#face0#我还没说完呢，你去哪……")
sm.setParam(37)
sm.sendSay("#face0#Where are you going? I'm not finished... ")
sm.startQuest(parentID)
