# id 64065 ([MONAD: The First Omen] Butler's Dilemma), field 867201100
sm.setSpeakerType(3)
sm.setParam(57)
sm.setColor(1)
sm.sendNext("啊，#h0#！派遣团团长是不是骂了你……？都是因为我们，抱歉……")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400622) # Williams
sm.sendSay("#b没有，巴特勒副团长说了关于“巨大的影子”的事情……")
sm.setParam(57)
sm.sendSay("啊！没有！那都是因为我太累了才会看见那种东西，真的！")
sm.setParam(37)
sm.sendSay("#b啊……我也看到了类似的东西，你可以跟我说实话的。")
sm.setParam(57)
sm.sendSay("不不，那真的是我的错觉。")
sm.setParam(37)
sm.sendSay("#face0#……在居民中也有很多人说起那个影子。")
sm.lockInGameUI(True, False)
sm.flipNpcByTemplateId(9400587, False)
sm.sendDelay(500)
sm.moveNpcByTemplateId(9400587, False, 50, 50)
sm.sendDelay(1000)
sm.lockInGameUI(False, True)
sm.setInnerOverrideSpeakerTemplateID(9400587) # Kan
sm.sendNext("#face0#人们把它叫做“雾中黑影”。虽然不知道那个是活着的……还是从地狱中冒出的烟雾形成的虚影……")
sm.sendSay("#face0#但是大家都不愿相信它是真实存在的。")
sm.sendSay("#b……究竟……那个……")
sm.setInnerOverrideSpeakerTemplateID(9400622) # Williams
sm.sendSay("#face0#在现在这种情况下，我希望那是个幻影。因为现在还没人看到它的实体。")
sm.setParam(57)
sm.sendSay("#face0#总是在刮着暴风雪……或者有烟雾的时候才能看到它。不过我也希望那只是人们在恐惧中……想象出来的幻影。如果那样的东西真的存在……")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400587) # Kan
sm.sendSay("#b……（看来还得再调查下。) ")
sm.sendSay("#b威尔森？")
sm.setParam(57)
sm.sendSay("#b(I definitely need to look into this further. ) ")
sm.createQuestWithQRValue(64020, "chk1=1;chk2=1;chk3=1")
sm.completeQuestNoCheck(parentID)
