# id 64111 ([MONAD: The First Omen] Guilt), field 867202300
sm.setSpeakerType(3)
sm.setParam(57)
sm.setColor(1)
sm.sendNext("#b郁兰？")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400588) # Ullan
sm.sendSay("…勇士…呜呜… ")
sm.setParam(57)
sm.sendSay("#b郁兰！出什么事了？")
sm.setParam(37)
sm.sendSay("呜呜… 都怪我太不懂事… ")
sm.sendSay("但那都是我很小的时候做的事情… ")
sm.setParam(57)
sm.sendSay("#b郁兰，你到底在说什么，能不能慢慢的告诉我。")
sm.setParam(37)
sm.sendSay("… 布兰茜姐姐的失踪都是我的错… ")
sm.setParam(57)
sm.sendSay("#b那是什么意思？")
sm.setParam(37)
sm.sendSay("呜呜… 小时候我和布兰茜姐姐，还有莎娜安婆婆一起生活在一个村子里… ")
sm.sendSay("我记得和布兰茜姐姐… 还有其他的朋友们… 一起在森林里玩耍…")
sm.sendSay("然后… ")
sm.sendSay("布兰茜姐姐… 肤色和我们不一样… 而且力量也很大…")
sm.sendSay("不知道从几何时我们开始害怕那样的姐姐… 我还记得大家都在取笑姐姐是个怪物…")
sm.setParam(57)
sm.sendSay("#b… 也许吧。")
sm.setParam(37)
sm.sendSay("之后莎娜安婆婆和布兰茜姐姐就离开了我们的村子。")
sm.sendSay("后来这件事情我忘得一干二净，也从不知道是因为我们才让姐姐和婆婆离开了村子… ")
sm.sendSay("呜呜… 莎娜安婆婆和布兰茜姐姐在森林里会多么害怕啊？")
sm.sendSay("如果他们不在森林里… 而是在村子里一起生活的话… 姐姐也不会就这么失踪了！")
sm.sendSay("呜呜呜… 我感到太愧疚了… ")
sm.sendSay("… 我讨厌爸爸，他没有跟我说过婆婆为了找布兰茜姐姐来到了村子！不，更讨厌他让婆婆离开了村子！")
sm.setParam(57)
sm.sendSay("#b郁兰，可汗村长是为了郁兰才那样做的。")
sm.setParam(37)
sm.sendSay("呜呜… 肯定会说为了大多数人只能那样做！我真的没法理解爸爸！")
sm.setParam(57)
sm.sendSay("#b… 郁兰，现在你用真心向莎娜安道歉的话，也不迟啊？")
sm.setParam(37)
sm.sendSay("婆婆… 会原谅我吗？")
sm.setParam(57)
sm.sendSay("#b反而会说你勇气可嘉。")
sm.sendSay("真… 真的吗？呜… ")
sm.setParam(37)
sm.sendSay("#b真的，你相信我。")
sm.setParam(57)
sm.sendSay("… 让我再想一想… 不！肯定会道歉的… 只是… 想一想该如何道歉… ")
sm.setParam(37)
sm.sendSay("#b如果需要我帮忙的话，可以随时来找我。")
sm.setParam(57)
sm.sendSay("呜呜… 是，勇士！谢谢你…！")
sm.setParam(37)
sm.sendSay("#b(… 阿尔西说的话不像是假的，能体会到他的真心。) ")
sm.lockInGameUI(True, False)
sm.showNpcSpecialActionByTemplateId(9400589, "attack1", -1)
sm.showNpcSpecialActionByTemplateId(9400592, "attack1", -1)
sm.sendDelay(3000)
sm.setParam(57)
sm.sendNext("#b(…在森林里待过的莎娜安说不定看到过什么吧？) ")
sm.sendSay("#b(比起郁兰我得先去找她了。) ")
sm.sendDelay(1000)
sm.sendNext("#b(莎娜安好像在杂货店里。)")
sm.sendSay("#b肯定会。")
sm.sendSay("#b(I should head to the General Store to find Sanaan.)")
sm.lockInGameUI(False, True)
sm.createQuestWithQRValue(64112, "chk1=1")
sm.completeQuestNoCheck(parentID)
sm.startQuest(64112)
