# id 64114 ([MONAD: The First Omen] Elva's Role), field 867202300
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(9400601) # Elva
sm.sendNext("#h0#，你说要谢我？")
sm.sendSay("那么… 可否帮我一个忙？")
sm.sendSay("啊啊，我说的话听起来是否在向你索取什么回报？噢，不是那样的。我怕你太忙了，所以不知道能不能拜托你……")
sm.setParam(57)
sm.sendSay("#b不，没关系。你尽管说。")
sm.setParam(37)
sm.sendSay("好好。我只是一介商人，但是作为商人我也有自己的使命。那就是我要常备人们所需要的所有物品。")
sm.sendSay("别人可能会笑我那算什么使命… ")
sm.setParam(57)
sm.sendSay("#b不，没人会那么认为。")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400586) # Sanaan
sm.sendSay("谁会那么想？我所看到的人都在感谢艾尔巴。")
sm.setInnerOverrideSpeakerTemplateID(9400601) # Elva
sm.sendSay("那真是太好了。")
sm.sendSay("但是最近村子和冰峰雪域断了联系之后，很多物品都需要补给。")
sm.sendSay("其他的倒是无所谓… 但是现在这种情况下，药水也快要断货了… ")
sm.sendSay("虽然厚颜无耻，但还是要拜托你。")
sm.setParam(57)
sm.sendSay("#b不不，药水是我们大家都需要的。反而要感谢你，是你提醒到了我。")
sm.setParam(37)
sm.sendSay("真的吗？哇噢，那我就可以放下心头的这块石头了。")
sm.sendSay("虽然实力不怎么样，但是我会调制药水。只要有几个材料的话… ")
sm.setParam(57)
sm.sendSay("#b需要什么材料？")
sm.setParam(37)
sm.sendSay("等下… 我记在哪里了呢… 啊！在这里。")
sm.sendSay("需要独眼触须怪的触须20个，扁柏树叶10个，小白雪鬼结晶10个，埃特金森透明的血10ml… ")
sm.sendSay("啊… 太多了吗？")
sm.setParam(57)
sm.sendSay("#b…不… 没有。独眼触须怪的触须20个，扁柏树叶10个… 还有呢… ")
sm.setParam(37)
sm.sendSay("小白雪鬼结晶10个，埃特金森透明的血10ml！")
sm.sendSay("我把这个笔记借给你吧，里边也写了寻找材料的方法，肯定会有帮助的。")
sm.startQuest(parentID)
sm.sendSay("打开艾尔巴的药水笔记。")
sm.setParam(57)
sm.sendSay("看… 是第10页的特级药水制作方法！")
