# id 64113 ([MONAD: The First Omen] Source of the Rumor), field 867202300
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(9400601) # Elva
sm.sendNext("那个…")
sm.sendSay("你好，我是这家商店的主人，我叫艾尔巴。")
sm.setInnerOverrideSpeakerTemplateID(9400586) # Sanaan
sm.sendSay("上次也介绍过，是把我带到这里的恩人。")
sm.sendSay("我住在森林小屋，经常来往与斯库亚斯的杂货店，买很多东西。")
sm.sendSay("后来我有好几个月没来，是他记得我并过来找到我的。")
sm.setParam(57)
sm.sendSay("#b真是了不起。")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400601) # Elva
sm.sendSay("作为商店的主人，记住每位顾客的脸，那是理所当然的事情。")
sm.sendSay("有很多人来我们的商店… 这里就像是一个各种消息的集散中心一样。")
sm.sendSay("所以… 我可以对刚才 #h0# 勇士的问题作出回答。")
sm.setParam(57)
sm.sendSay("#b刚才的问题… 你是说可疑的人？")
sm.setParam(37)
sm.sendSay("当然，不是我亲眼看到的。")
sm.sendSay("大概6个月前，有个人去森林里采药，说是发现了一个可疑的人。")
sm.sendSay("这仿佛是个非常遥远的故事，我都差点忘记了。不过刚才听到 #h0# 的问题，就突然想起来了。")
sm.setParam(57)
sm.sendSay("#b能告诉我详细的情况吗？")
sm.setParam(37)
sm.sendSay("嗯… 听说是穿着一套白色的盔甲，没有漏出一丝皮肤。看到的人都羡慕的说，貌似能穿透暴风雪一样。")
sm.sendSay("但是他们不是一个人。原以为他们会瞬间移动，但是实际上是几个穿着相同的人。")
sm.setParam(57)
sm.sendSay("#b… 一模一样啊… ")
sm.setParam(37)
sm.sendSay("#b还有一个人也见过。")
sm.setParam(57)
sm.sendSay("#b能否知道是谁告诉你这个故事吗？")
sm.setParam(37)
sm.sendSay("是去森林寻找妻子的人，但现在还没回来。")
sm.setParam(57)
sm.sendSay("#b感谢你，艾尔巴。")
sm.setParam(37)
sm.sendSay("#b(…阿尔西说的话原来是真的啊。)")
sm.setParam(57)
sm.sendSay("真的吗？")
sm.sendSay("#bThank you, Elva. ")
sm.sendSay("#b(Turns out Aruhi wasn't just rambling after all.)")
sm.createQuestWithQRValue(64039, "chk1=1;chk2=1")
sm.completeQuestNoCheck(parentID)
