# id 64133 ([MONAD: The First Omen] Building a Catapult), field 867202300
sm.lockInGameUI(True, False)
sm.setSpeakerType(3)
sm.setParam(57)
sm.setColor(1)
sm.sendNext("#b艾丽卡，有什么事吗？")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400580) # Alika
sm.sendSay("#face0#因为投石器的问题。")
sm.sendSay("#b是之前造了一般的那个投石器吗？有什么问题")
sm.setParam(57)
sm.sendSay("#face0#投石器的框架都做好了，而且巨石也都准备好了。")
sm.setParam(37)
sm.sendSay("#face0#问题是… 斯库亚斯内找不到可以支撑那巨石的绳索。")
sm.sendSay("#b那我们快去找绳索吧？")
sm.setParam(57)
sm.sendSay("#face0#发现芬里斯也已经过去很久了，怪物们马上就要攻过来了。")
sm.setParam(37)
sm.sendSay("#face0#这么危机的时刻… 谁也不能冒险出城。")
sm.sendSay("#b(怎么办… 我一个人快去快回行不行？) ")
sm.setParam(57)
sm.sendSay("#b… 需要多么强力的绳索？")
sm.sendSay("#face0##h0#，别想着出城，那很危险。")
sm.sendSay("#b如果能完成投石器的话，我可以快去快回。万一碰到怪物了，我一个人也好脱身。")
sm.setParam(37)
sm.sendSay("#face0#不，当然不能让你一个人去那么危险的地方。")
sm.setParam(57)
sm.sendSay("#face0#就当我没听见吧，应该还有别的方法。")
sm.setParam(37)
sm.sendSay("#b(… 我还是去一趟吧。) ")
sm.sendSay("#face4#Just forget about the rope. We'll find something to substitute for it.")
sm.setParam(57)
sm.sendSay("#b(Yeah, might as well sneak out and get this done.) ")
sm.lockInGameUI(False, True)
sm.startQuest(parentID)
sm.warp(867202200)
