# id 64112 ([MONAD: The First Omen] Another Witness), field 867202300
sm.lockInGameUI(True, False)
sm.forcedFlip(True)
sm.setSpeakerType(3)
sm.setParam(57)
sm.setColor(1)
sm.sendNext("#b我正要去找你呢，你在这里做什么？")
sm.flipNpcByTemplateId(9400586, False)
sm.flipNpcByTemplateId(9400601, False)
sm.sendSay("啊，#h0#…… 这房子里的家伙又惹事了，好几天都没有开门… ")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400586) # Sanaan
sm.sendSay("#b这个房子？")
sm.setParam(57)
sm.sendSay("住在里边的家伙非常让人头痛，不知道这次又有什么事情让他不开心… ")
sm.flipNpcByTemplateId(9400586, True)
sm.setParam(37)
sm.sendSay("莎娜安，艾伊纳尔会听到的。")
sm.flipNpcByTemplateId(9400601, True)
sm.setInnerOverrideSpeakerTemplateID(9400601) # Elva
sm.sendSay("对了，你找我有什么事？")
sm.setInnerOverrideSpeakerTemplateID(9400586) # Sanaan
sm.sendSay("#b你在森林里居住的时候… 有没有看到过外人？或者说形迹可疑的人… ")
sm.flipNpcByTemplateId(9400586, False)
sm.flipNpcByTemplateId(9400601, False)
sm.sendSay("外地人我倒是看到过几个，大概什么时候？")
sm.setParam(57)
sm.sendSay("#b嗯… 6个月前… ")
sm.setParam(37)
sm.sendSay("… 可惜那时候没有。")
sm.setParam(57)
sm.sendSay("#b原来如此，不知道我是不是又让你回忆起伤心的往事。")
sm.setParam(37)
sm.sendSay("没什么，过去的事情罢了。如果这些能找回布兰茜的话，你们随时都可以来找我。")
sm.setParam(57)
sm.sendSay("啊！对了，我没有告诉你这个！")
sm.setParam(37)
sm.sendSay("… 你去森林的时候… 看到过粉色的很粘稠的… 东西了吧？")
sm.blind(True, 255, 0, 0, 0, 250)
sm.sendDelay(250)
sm.spawnNpc(9400586, 710, 0)
sm.showNpcSpecialActionByTemplateId(9400586, "summon", 0)
sm.spawnNpc(9400601, 770, 0)
sm.showNpcSpecialActionByTemplateId(9400601, "summon", 0)
sm.forcedFlip(True)
sm.moveNpcByTemplateId(9400601, False, 150, 70)
sm.moveNpcByTemplateId(9400586, False, 150, 70)
sm.blind(True, 255, 0, 0, 0, 0)
sm.sendDelay(100)
sm.blind(False, 0, 0, 0, 0, 250)
sm.sendDelay(300)
sm.sendDelay(1500)
sm.forcedMove(False, 100)
sm.showEffect("Effect/OnUserEff.img/emotion/oh", 0, 0, 0, 0, 34418552, 0, 0)
sm.sendNext("在小屋附近是不是有很多！")
sm.sendDelay(900)
sm.setParam(57)
sm.sendNext("#b是的，我看到了。我和艾丽卡称之为… ‘恶心的粉红触手’。")
sm.flipNpcByTemplateId(9400586, True)
sm.flipNpcByTemplateId(9400601, True)
sm.setParam(37)
sm.sendSay("呵呵，名字起的到不错！")
sm.sendSay("我在森林里等着孙女的时候，无意间看到了那奇怪的东西。")
sm.setParam(57)
sm.sendSay("‘那家伙’ 好像通过你们所说的‘恶心的粉红触手’来控制其他的怪物。")
sm.setParam(37)
sm.sendSay("#b… 果不其然，和我们的猜测完全相同。")
sm.sendSay("那… 你们知道这个吗？")
sm.sendSay("就是‘那家伙’产生恶心粉色的事情… ？")
sm.setParam(57)
sm.sendSay("#b… 我们只是猜测肯定会有某种关联… ")
sm.flipNpcByTemplateId(9400586, False)
sm.flipNpcByTemplateId(9400601, False)
sm.sendDelay(300)
sm.moveNpcByTemplateId(9400601, False, 150, 70)
sm.moveNpcByTemplateId(9400586, False, 150, 70)
sm.sendDelay(900)
sm.setParam(37)
sm.sendNext("只要‘那家伙’一出现，天空即刻变灰，然后就开始下起了雪。他那庞大的身躯每每移动时，地上的积雪全部会弹起。")
sm.forcedMove(False, 100)
sm.sendDelay(900)
sm.setParam(57)
sm.sendNext("下雪的时候‘那家伙’好像喷出什么奇怪的粉末，感觉空中飘落下来红色的雪一样。")
sm.sendDelay(900)
sm.setParam(37)
sm.sendNext("然后那个巨大的身影，我用这双眼睛看的非常清楚！它好像在斩断身体的一部分！")
sm.setParam(57)
sm.sendSay("… 不知道是不是因为那个缘故，它每次能制作的数量有一定的上限。")
sm.flipNpcByTemplateId(9400586, True)
sm.flipNpcByTemplateId(9400601, True)
sm.setParam(37)
sm.sendSay("如果‘那家伙’真的能用恶心的粉红触手来控制怪物的话…")
sm.sendSay("#b如果我们消灭的速度比制作的速度快的话，它就会到极限了吧。")
sm.sendSay("正是！")
sm.sendSay("#b不过… 上一次在森林里，当我把恶心的粉红触手全都消灭之后… ‘那家伙’一过来，触手们又开始活过来了。照那样看来… ")
sm.setParam(57)
sm.sendSay("… ‘那家伙’自己好像也有控制能力。")
sm.setParam(37)
sm.sendSay("#b对，不过他每次制作的数量有限制的话，说不定真能帮上大忙。")
sm.sendSay("如果那样可真是太好了，我这把老骨头也算没有枉费在小屋里生活的日子啦。")
sm.setParam(57)
sm.sendSay("还有件事要告诉你… ")
sm.setParam(37)
sm.sendSay("也对，你来到阿布鲁的时间也不短，而且也进过森林，能看到的应该都看到了吧。")
sm.setParam(57)
sm.sendSay("如果我还能记起什么，到时候再告诉你。")
sm.setParam(37)
sm.sendSay("#b谢谢你，莎娜安。")
sm.setParam(57)
sm.sendSay("#b莎娜安！")
sm.setParam(37)
sm.sendSay("我就是要让他听到。")
sm.sendSay("#b这个？是什么？")
sm.sendSay("#b哪个？")
sm.sendSay("#b这是真的吗？！")
sm.setParam(57)
sm.sendSay("对，是真的。")
sm.completeQuestNoCheck(parentID)
sm.lockInGameUI(False, True)
