# id 64116 ([MONAD: The First Omen] Shabby Armor), field 867202300
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(9400601) # Elva
sm.sendNext("我正在帮莎娜安婆婆制作盔甲呢。")
sm.setInnerOverrideSpeakerTemplateID(9400586) # Sanaan
sm.sendSay("不过也就修理而已… 收集了全部盔甲碎片。")
sm.setParam(57)
sm.sendSay("#b盔甲？")
sm.setParam(37)
sm.sendSay("啊！你也知道，我打算送给那个麻烦的家伙。")
sm.sendSay("话说，能给我一下不用的盔甲吗？因为我这里少一条胳膊…#b\r\n#L0#没有。#l\r\n#L1#查看背包。#l")
res = sm.sendNext("那也没办法…")
sm.sendNext("做的差不多了。怎么样？")
sm.sendSay("对你来说这个恐怕没什么用，但对那家伙就是必不可少的。")
sm.sendSay("他和我有很多共同点。")
sm.sendSay("我希望他能穿上这件盔甲之后，能走出屋子… 但是我不敢确定。")
sm.sendSay("不过有一点可以肯定… 至少我也在努力地去做一些我力所能及的事情… ")
sm.sendSay("看这个！有两个犄角，是不是很酷？")
sm.sendSay("#b是的。")
sm.setParam(57)
sm.sendSay("那当然，一想到艾伊纳尔能带着这个头盔出门… 想想都很酷…")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400601) # Elva
sm.sendSay("如果真能那样就好了… ")
sm.setInnerOverrideSpeakerTemplateID(9400586) # Sanaan
sm.sendSay("你也别太担心了。不过这个嘈杂声音是怎么回事？")
sm.setInnerOverrideSpeakerTemplateID(9400601) # Elva
sm.sendSay("好像有骚乱。")
sm.setInnerOverrideSpeakerTemplateID(9400586) # Sanaan
sm.sendSay("#b我们最好去看一下。")
sm.setParam(57)
sm.sendSay("啊！差点忘记了，这个是送给你的。虽然和你身上的根本没法相比，但这是我这老太婆的心意。")
sm.setParam(37)
sm.sendSay("但是没人送。")
sm.sendSay("快去看一下。")
sm.playExclSoundWithDownBGM("Field.img/masteryBook/EnchantSuccess", 100)
sm.completeQuestNoCheck(parentID)
sm.warp(867202305)
