# id 64104 ([MONAD: The First Omen] Skuas Remembers), field 867202300
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(9400600) # Birna
sm.sendNext("#h0#，感谢你的演说。")
sm.sendSay("您也别太在意。")
sm.setParam(57)
sm.sendSay("#b感谢维尔纳村长，为我们提供庇护。")
sm.setParam(37)
sm.sendSay("这么多的人聚在一起，最困难的事情就是定相同的目标。")
sm.sendSay("但是我们大家的迫切心情都是一样的，所以我觉得已经达到一半的目的了。")
sm.sendSay("过去斯库亚斯也同样收容了很多遇难者，这种事情经常有。")
sm.sendSay("我们从历史中学到过，要让人们团结起来就得向这样把大家聚在一起。我们今天的事迹也许会载入史册，被后代所传颂。")
sm.setParam(57)
sm.sendSay("#b斯库亚斯是不会忘记历史的。")
sm.completeQuestNoCheck(parentID)
