package net.swordie.ms.handlers.header;

import net.swordie.ms.ServerConstants;
import net.swordie.ms.util.Util;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.*;

public enum InHeader {
    LEAVE_BUTTON_PRESSED(-1),
    DUMMY_CODE(100),
    BEGIN_SOCKET(101),
    SECURITY_PACKET(102),
    PERMISSION_REQUEST(103),
    LOGIN_BASIC_INFO(104),
    CHECK_LOGIN_AUTH_INFO(105),
    VIEW_CHANNEL_REQUEST(106),
    SELECT_WORLD(107),
    CHECK_SPW_REQUEST(108),
    CHAR_SELECT(109),
    CHECK_SPW_EXIST_REQUEST(110),
    SELECT_CHARACTER(111), // ?
    MIGRATE_IN(112),
    SELECT_ACCOUNT(113),
    WORLD_INFO_REQUEST(115),
    CHECK_DUPLICATE_ID(116),
    LOGOUT_WORLD(117),
    PERMISSION_REQUEST_FAKE(118),
    CHECK_LOGIN_AUTH_INFO_FAKE(119),
    CREATE_MAPLE_ACCOUNT_FAKE(120),
    SELECT_ACCOUNT_FAKE(121),
    SELECT_WORLD_FAKE(122),
    SELECT_CHARACTER_FAKE(123),
    CREATE_NEW_CHARACTER_FAKE(124),
    CREATE_NEW_CHARACTER(125),
    DELETE_CHARACTER(128),
    RESERVED_DELETE_CHARACTER_CONFIRM(129),
    RESERVED_DELETE_CHARACTER_CANCEL(130),
    RENAME_CHARACTER(131),
    EXCEPTION_LOG(132),
    PRIVATE_SERVER_PACKET(133),
    RESET_LOGIN_STATE_ON_CHECK_OTP(134),
    CHANGE_SPW_REQUEST_OLD(135),
    CHECK_SOW_REQUEST_FAKE(136),
    CHECK_OTP_REQUEST(137),
    CHECK_DELETE_CHARACTER_OTP(138),
    CHECK_OTP_FOR_WEB_LAUNCHING_REQUEST(139),
    CREATE_SECURITY_HANDLE(140),
    ALBA_REQUEST(141),
    UPDATE_CHARACTER_CARD_REQUEST(142),
    ALIVE_ACK(150),
    CLIENT_ERROR(153),
    APPLY_HOTFIX(156),
    SERVER_STATUS_REQUEST(157),
    WVS_SET_UP_STEP(158),
    WVS_CRASH_CALLBACK(159),
    WORLD_LIST_REQUEST(163),
    SELECT_CHARACTER_AFTER_CREATE(165),
    CHAR_POSITION_CHANGE(166),
    UNK288_169(169),
    ANTI_MACRO_RESPONSE(170),
    SOME_CHANNEL_INFO_REQUEST(182),
    WORLD_STATUS_REQUEST(185),
    USE_AUTH_SERVER(186),
    CHANGE_SPW_REQUEST(189),
    CHAR_SELECT_NO_PIC(190),
    AUTH_FAILURE(191),
    DONE_LOADING(198),
    SOME_DATE_REQUEST(199),

    BEGIN_USER(200),
    USER_TRANSFER_FIELD_REQUEST(201),
    USER_TRANSFER_CHANNEL_REQUEST(202),
    USER_TRANSFER_TO_HUB_REQUEST(203),
    WORLD_TRANSFER_REQUEST(204),
    WORLD_TRANSFER_SHINNING_STAR_REQUEST(205),
    USER_MIGRATE_TO_CASH_SHOP_REQUEST(206),
    USER_MIGRATE_AUCTION_REQUEST(207),
    USER_MIGRATE_TO_MONSTER_FARM(208),
    USER_MIGRATE_TO_MONSTER_FARM_BY_INVITE_ITEM(209),
    USER_TRANSFER_ASWAN_REQUEST(210),
    USER_TRANSFER_ASWAN_READY_REQUEST(211),
    ASWAN_RETIRE_REQUEST(212),
    USER_REQUEST_PV_P_STATUS(213),
    USER_MIGRATE_TO_PVE_REQUEST(213),
    USER_MOVE(214),
    USER_SIT_REQUEST(215),
    USER_PORTABLE_CHAIR_SIT_REQUEST(216),
    USER_EMOTICON_ITEM_USE_REQUEST(217),
    USER_DANCE_STOP_REQUEST(218),
    USER_MELEE_ATTACK(219),
    USER_SHOOT_ATTACK(220),
    USER_MAGIC_ATTACK(221),
    USER_BODY_ATTACK(222),
    USER_AREA_DOT_ATTACK(223),
    USER_AFFECTED_AREA_FOR_SCREEN_ATTACK(224),
    //
    USER_HIT(226),
    //
    USER_CHAT(228),
    USER_ITEM_LINKED_CHAT(229),
    USER_AD_BOARD_CLOSE(230),
    USER_EMOTION(231),
    ANDROID_EMOTION(232),
    USER_ACTIVATE_EFFECT_ITEM(233),
    USER_MONKEY_EFFECT_ITEM(234),
    USER_ACTIVATE_NICK_ITEM(235),
    USER_ACTIVATE_DAMAGE_SKIN(236),
    USER_ACTIVATE_DAMAGE_SKIN_PREMIUM(237),
    USER_ACTIVATE_DAMAGE_SKIN_UNIT(238),
    USER_ACTIVATE_DAMAGE_SKIN_UNK(239),

    USER_DAMAGE_SKIN_SAVE_REQUEST(241),
    USER_DEFAULT_WING_ITEM(242),
    USER_KAISER_TRANSFORM_WING(243),
    USER_KAISER_TRANSFORM_TAIL(244),
    USER_UPGRADE_TOMB_EFFECT(245),
    USER_BAN_MAP_BY_MOB(246),
    USER_MONSTER_BOOK_SET_COVER(247),
    USER_SELECT_NPC(248),
    USER_SCRIPT_MESSAGE_ANSWER(249),
    USER_SHOP_REQUEST(250),
    USER_TRUNK_REQUEST(251),
    USER_STORE_BANK_REQUEST(252),
    USER_PARCEL_REQUEST(253),
    USER_EFFECT_LOCAL(254),
    USER_SPECIAL_EFFECT_LOCAL(255),
    USER_UNK214_259(256),
    USER_CREATE_AREA_DOT_REQUEST(257),
    USER_CREATE_HOLIDOM_REQUEST(258),
    USER_RECIPE_COOLTIME_REQUEST(260),
    AUCTION_REQUEST(261),
    AUCTION_LEAVE_REQUEST(262),
    UNK233_264(263),
    USER_GATHER_ITEM_REQUEST(264),
    USER_SORT_ITEM_REQUEST(265),
    USER_CHANGE_SLOT_POSITION_REQUEST(266),
    USER_TEXT_EQUIP_INFO(267),
    USER_POP_OR_PUSH_BAG_ITEM_TO_INVEN(268),
    USER_BAG_TO_BAG_ITEM(269),
    USER_POUR_IN_BAG_TO_BAG(270),
    USER_STAT_CHANGE_ITEM_USE_REQUEST(271),
    USER_STAT_CHANGE_ITEM_CANCEL_REQUEST(272),
    USER_STAT_CHANGE_BY_PORTABLE_CHAIR_REQUEST(273),
    USER_MOB_SUMMON_ITEM_USE_REQUEST(274),
    USER_PET_FOOD_ITEM_USE_REQUEST(275),
    USER_TAMING_MOB_FOOD_ITEM_USE_REQUEST(276),
    USER_SCRIPT_ITEM_USE_REQUEST(277),
    USER_RECIPE_OPEN_ITEM_USE_REQUEST(278),
    USER_CONSUME_CASH_ITEM_USE_REQUEST(279),
    USER_ADDITIONAL_SLOT_EXTEND_ITEM_USE_REQUEST(280),
    USER_CASH_PET_PICK_UP_ON_OFF_REQUEST(281),
    USER_CASH_PET_SKILL_SETTING_REQUEST(282),
    USER_OPTION_CHANGE_REQUEST(282),
    USER_DESTROY_PET_ITEM_REQUEST(283),
    USER_BRIDLE_ITEM_USE_REQUEST(284),
    USER_SKILL_LEARN_ITEM_USE_REQUEST(285),
    USER_SKILL_RESET_ITEM_USE_REQUEST(286),
    USER_ABILITY_RESET_ITEM_USE_REQUEST(287),
    USER_ABILITY_CHANGE_ITEM_USE_REQUEST(288),
    USER_EXP_CONSUME_ITEM_USE_REQUEST(289),
    USER_MONSTER_LIFE_INVITE_ITEM_USE_REQUEST(290),
    USER_EXP_ITEM_GET_REQUEST(291),
    USER_CHAR_SLOT_INC_ITEM_USE_REQUEST(292),
    USER_CHAR_RENAME_ITEM_USE_REQUEST(293),
    USER_KAISER_COLOR_CHANGE_ITEM_USE_REQUEST(294),
    USER_MAP_TRANSFER_ITEM_USE_REQUEST(295),
    // Between 297 and 301 a new Header was added
    USER_PORTAL_SCROLL_USE_REQUEST(297),
    USER_FIELD_TRANSFER_REQUEST(298),
    USER_UPGRADE_ITEM_USE_REQUEST(299),
    USER_UPGRADE_ASSIST_ITEM_USE_REQUEST(300),
    USER_HYPER_UPGRADE_ITEM_USE_REQUEST(301),
    USER_EX_ITEM_UPGRADE_ITEM_USE_REQUEST(302),
    USER_KARMA_CONSUME_ITEM_USE_REQUEST(303),
    USER_EVENT_UPGRADE_ITEM_USE_REQUEST(304),
    USER_ITEM_OPTION_UPGRADE_ITEM_USE_REQUEST(307),
    USER_ADDITIONAL_OPT_UPGRADE_ITEM_USE_REQUEST(308),
    USER_ITEM_SLOT_EXTEND_ITEM_USE_REQUEST(309),
    USER_WEAPON_TEMP_ITEM_OPTION_REQUEST(310),
    USER_ITEM_SKILL_SOCKET_UPGRADE_ITEM_USE_REQUEST(311),
    USER_ITEM_SKILL_OPTION_UPGRADE_ITEM_USE_REQUEST(312),
    USER_FREE_MIRACLE_CUBE_ITEM_USE_REQUEST(313),
    USER_UNK_CUBE_ITEM_USE_REQUEST(314),
    USER_EQUIPMENT_ENCHANT_WITH_SINGLE_UI_REQUEST(315),

    USER_ARCANE_SYMBOL_REQUEST(318),
    USER_AUTHENTIC_SYMBOL_REQUEST(319),
    USER_UI_OPEN_ITEM_USE_REQUEST(320),
    USER_BAG_ITEM_USE_REQUEST(321),
    USER_ITEM_RELEASE_REQUEST(322),
    USER_UNK228_323(323),
    USER_MEMORIAL_CUBE_OPTION_REQUEST(324),
    USER_UNK227_322_MABYBE_FLAME(325),

    USER_USE_NAVI_FLYING_SKILL_REQUEST(326),
    USER_TOADS_HAMMER_REQUEST(328),
    USER_TOADS_HAMMER_HELP_REQUEST(329),
    USER_CHANGE_SOUL_COLLECTION_REQUEST(330),
    USER_SELECT_SOUL_SKILL_UP_REQUEST(331),

    USER_ABILITY_UP_REQUEST(333),
    USER_ABILITY_MASS_UP_REQUEST(334),
    USER_DOT_HEAL(335),
    USER_CHANGE_STAT_REQUEST(336),
    USER_CHANGE_STAT_REQUEST_BY_ITEM_OPTION(337),
    SET_SON_OF_LINKED_SKILL_REQUEST(338),
    UNLINK_SKILL_REQUEST(339),
    LINK_SKILL_REQUEST(340),
    USER_SKILL_UP_REQUEST(341),
    USER_SKILL_USE_REQUEST(342),
    USER_SKILL_UNK227_340(343),
    USER_SKILL_CANCEL_REQUEST(344),
    USER_SKILL_PREPARE_STOP(345),
    USER_SKILL_PREPARE_START(346),
    USER_SKILL_KEYDOWN_STOP(347),
    USER_SKILL_KEYDOWN_CHARGE_REQUEST(348),
    USER_DROP_MONEY_REQUEST(349),
    USER_GIVE_POPULARITY_REQUEST(350),
    USER_PARTY_REQUEST(351),
    USER_UNK218_347(352),
    USER_CHARACTER_INFO_REQUEST(353),
    USER_ACTIVATE_PET_REQUEST(354),
    USER_REGISTER_PET_AUTO_BUFF_REQUEST(355),
    USER_TEMPORARY_STAT_UPDATE_REQUEST(356),
    USER_PORTAL_SCRIPT_REQUEST(357),
    USER_PORTAL_TELEPORT_REQUEST(358),
    USER_CALLING_TELEPORT_REQUEST(360),
    USER_MAP_TRANSFER_REQUEST(361),
    USER_ANTI_MACRO_ITEM_USE_REQUEST(362),
    USER_ANTI_MACRO_SKILL_USE_REQUEST(363),
    USER_ANTI_MACRO_REFRESH_REQUEST(364),
    USER_CLAIM_REQUEST(365),
    USER_QUEST_REQUEST(366),
    USER_MEDAL_REISSUE_REQUEST(367),
    USER_CALC_DAMAGE_STAT_SET_REQUEST(368),
    USER_B2_BODY_REQUEST(369),
    USER_THROW_GRENADE(370),
    USER_DESTROY_GRENADE(371),
    USER_CREATE_AURA_BY_GRENADE(372),
    USER_SET_MOVE_GRENADE(373),
    USER_MACRO_SYS_DATA_MODIFIED(374),
    USER_SELECT_NPC_ITEM_USE_REQUEST(375),
    USER_LOTTERY_ITEM_USE_REQUEST(376),
    USER_ROULETTE_START_REQUEST(377),
    USER_ROULETTE_RESULT_REQUEST(378),
    USER_ITEM_MAKE_REQUEST(379),
    USER_REPAIR_DURABILITY_ALL(380),
    USER_REPAIR_DURABILITY(381),
    USER_QUEST_RECORD_SET_STATE(382),
    USER_CLIENT_TIMER_END_REQUEST(382),
    USER_CLIENT_RESOLUTION_RESULT(383),
    USER_FOLLOW_CHARACTER_REQUEST(384),
    USER_FOLLOW_CHARACTER_WITHDRAW(385),
    USER_SELECT_PQ_REWARD(386),
    USER_REQUEST_PQ_REWARD(387),
    SET_PASSENGER_RESULT(388),
    USER_REQUEST_INSTANCE_TABLE(389),
    USER_REQUEST_CREATE_ITEM_POT(390),
    USER_REQUEST_REMOVE_ITEM_POT(391),
    USER_REQUEST_INC_ITEM_POT_LIFE_SATIETY(392),
    USER_REQUEST_CURE_ITEM_POT_LIFE_SICK(393),
    USER_REQUEST_COMPLATE_TO_ITEM_POT(394),
    USER_REQUEST_RESPAWN(395),
    USER_CONSUME_HAIR_ITEM_USE_REQUEST(396),
    //
    USER_FORCE_ATOM_COLLISION(400),
    USER_DEBUFF_OBJ_COLLISION(401),
    USER_CREATE_LUCK_OF_THE_DRAW(402),
    USER_UPDATE_PARTY_BUFF_AREA(403),
    USER_UPDATE_DEBUFF_OBJ(405),
    USER_UPDATE_LAPIDIFICATION(406),


    USER_REQUEST_CHARACTER_POTENTIAL_SKILL_RAND_SET(408),
    USER_REQUEST_CHARACTER_POTENTIAL_SKILL_RAND_SET_UI(409),
    USER_REQUEST_OCCUMPATION_DATA(410),
    USER_REQUEST_ASWAN_TIME_TABLE_CLIENT_INIT(411),
    USER_PROTECT_BUFF_DIE_ITEM_REQUEST(412),
    USER_PROTECT_BUFF_DIE_MAPLE_POINT_REQUEST(413),
    USER_PROTECT_EXP_DIE_MAPLE_POINT_REQUEST(413),
    USER_KEY_DOWN_AREA_MOVING(412),
    USER_CHECK_WEDDING_EX_REQUEST(413),
    USER_CATCH_DEBUFF_COLLISION(414),
    USER_AFFECTED_AREA_CREATED(415),
    USER_AFFECTED_AREA_REMOVED(416),
    USER_DAZZLE_HIT(417),
    USER_MESO_EXCHANGE_REQUEST(419),
    USER_GROUP_CHAIR_INVITE_REQUEST(420),
    USER_GROUP_CHAIR_INVITE_RESPONSE(421),
    USER_GROUP_CHAIR_REMOVE_REQUEST(422),

    ZERO_TAG(423),
    ZERO_SHARE_CASH_EQUIP_PART(424),
    ZERO_LAST_ASSIST_STATE(425),
    SHOOT_ATTACK_IN_FPS_REQUEST(426),

    USER_DRAGON_ACTION(429),
    USER_DRAGON_BREATH_EARTH_EFFECT(430),
    USER_RENAME_REQUEST(431),
    UNK212_437(432),
    BROADCAST_MSG(433),
    GROUP_MESSAGE(434),
    ITEM_LINKED_GROUP_MESSAGE(435),
    UNK209_434(436),
    WHISPER(437),
    ITEM_LINKED_WHISPER(438),
    MESSENGER(439),
    MINI_ROOM(440),
    UNK212_443(441),
    PARTY_REQUEST(442),
    PARTY_RESULT(443),
    PARTY_INVITABLE_SET(444),
    EXPEDITION_REQUEST(445),
    PARTY_ADVER_REQUEST(446),
    URSUS_PARTY_REQUEST(447),
    GUILD_REQUEST(448),
    GUILD_RESULT(449),
    GUILD_JOIN_REQUEST(450),
    GUILD_JOIN_CANCEL_REQUEST(451),
    GUILD_JOIN_ACCEPT(452),
    GUILD_JOIN_REJECT(453),
    GUILD_CONTENT_RANK_REQUEST(454),
    TOWER_RANK_REQUEST(455),
    ADMIN(456),
    LOG(457),

    FRIEND_REQUEST(462),  // *
    LOAD_ACCOUNT_ID_OF_CHARACTER_FRIEND_REQUEST(463),
    MEMO_REQUEST(464),
    MEMO_FLAG_REQUEST(465),

    ENTER_TOWN_PORTAL_REQUEST(466),
    ENTER_RANDOM_PORTAL_REQUEST(467),
    ENTER_OPEN_GATE_REQUEST(468),
    SLIDE_REQUEST(469),

    FUNC_KEY_MAPPED_MODIFIED(471),
    R_P_S_GAME(472),
    G_S_R_P_S_GAME(473),
    G_S_R_P_S_FORCE_SELECT(474),
    MARRIAGE_REQUEST(475),
    WEDDING_WISH_LIST_REQUEST(476),
    GUEST_BLESS(477),
    BOOBY_TRAP_ALERT(478),
    STALK_BEGIN(479),
    ALLIANCE_REQUEST(480),
    ALLIANCE_RESULT(481),
    TALK_TO_TUTOR(482),
    TALK_TO_PARTNER(483),
    USER_SWITCH_R_P(484),

    REQUEST_INC_COMBO(486),
    REQUEST_DEC_COMBO(487),
    REQUEST_SET_BLESS_OF_DARKNESS(488),
    UNK227_486(489),
    DEMON_BLOOD_SPILL_REQUEST(490),
    XENON_CORE_OVERLOAD(491),
    REQUEST_SET_HP_BASE_DAMAGE(492),
    MOB_CRC_KEY_CHANGED_REPLY(493),
    MOB_CRC_DATA_RESULT(494),
    MAKING_SKILL_REQUEST(495),
    BROADCAST_EFFECT_TO_SPLIT(496),
    BROADCAST_ONE_TIME_ACTION_TO_SPLIT(497),
    BROADCAST_AFFECTED_EFFECT_TO_SPLIT(498),
    DEBUG_ONLY_COMMAND(499),
    MICRO_BUFF_END_TIME(500),
    REQUEST_SESSION_VALUE(501),
    USER_TRANSFER_FREE_MARKET_REQUEST(502),
    USER_REQUEST_SET_STEAL_SKILL_SLOT(503),
    USER_REQUEST_STEAL_SKILL_MEMORY(504),
    USER_REQUEST_STEAL_SKILL_LIST(505),
    USER_REQUEST_STEAL_SKILL(506),
    RECALL_SUMMON(507),

    REWARD_MOB_LIST_REQUEST(510),
    USER_LV_UP_GUIDE_NOTICE(511),
    RESET_CROSS_HUNTER_ALERT(512),
    CROSS_HUNTER_COMPLETE_REQUEST(513),
    CROSS_HUNTER_SHOP_REQUEST(514),
    USER_EQUIP_SLOT_LEVEL_MINUS_ITEM_USE_REQUEST(515),
    BOARD_GAME_REQUEST(516),
    USER_REQUEST_FLYING_SWORD_START(517),
    BINGO_REQUEST(518),
    BINGO_CASSANDRA_REQUEST(519),
    ACTION_BAR_REQUEST(520),
    USER_REQUEST_SET_OFF_TRINITY(521),
    USER_DRAGON_LINK_REQUEST(523),
    USER_HYPER_SKILL_UP_REQUEST(524),
    USER_HYPER_SKILL_RESET_REQUEST(525),
    USER_HYPER_STAT_SKILL_UP_REQUEST(526),
    USER_HYPER_STAT_SKILL_RESET_REQUEST(527),
    USER_HYPER_SKILL_PRESET_REQUEST(528),
    USER_SET_DRESS_CHANGED_REQUEST(529),
    ENTRY_RECORD_REQUEST(530),
    SET_MAX_GAUGE(531),
    USER_RETURN_EFFECT_RESPONSE(532),
    GET_SERVER_TIME(533),
    GET_CHARACTER_POSITION(534),
    USER_REQUEST_CHANGE_MOB_ZONE_STATE(535),
    EVOLVING_REQUEST(536),
    USER_MIXER_REQUEST(537),
    SUMMON_EVENT_REWARD(538),
    MYSTIC_FIELD_MOVE(539),
    YUT_GAME_REQUEST(540),
    VALUE_PACK_REQUEST(541),
    REQUEST_RELOGIN_COOKIE(542),
    WAIT_QUEUE_REQUEST(543),
    CHECK_TRICK_OR_TREAT_REQUEST(544),
    MONSTER_FARM_MIGRATE_OUT_REQUEST(545),
    HALLOWEEN_CANDY_RANKING_REQUEST(546),
    GET_REWARD_REQUEST(547),
    MAPLE_STYLE_BONUS_REQUEST(548),
    MAPLE_STYLE_ADVICE_REQUEST(549),
    MAPLE_STYLE_SET_SCORE_REQUEST(550),
    MENTORING(550),
    GET_LOTTERY_RESULT(551),
    ROOT_ABYSS_ENTER_REQUEST(552),
    USER_SET_ITEM_ACTION(553),
    USER_SET_BITS_CASE(554),
    USER_SET_BITS_SLOT(555),
    USER_ANTI_MACRO_QUESTION_RESULT(556),
    USER_PINKBEAN_ROLLING(557),
    USER_WIND_ENERGY_REQUEST(558),

    USER_QUICK_MOVE_SCRIPT(561),
    //    TIME_GATE_REQUEST(562), // ?
    USER_COMPLETE_NPC_SPEECH(562),
    USER_COMPLETE_COMBO_KILL_COUNT_CHECK(564),
    USER_COMPLETE_MULTI_KILL_COUNT_CHECK(565),
    USER_COMPLETE_MULTI_KILL_CHECK(566),
    USER_DAMAGE_FALLING_CHECK(567),
    USER_COMPLETE_PERSONAL_SHOP_BUY_CHECK(568),
    USER_DAILY_COMMITMENT_CHECK(569),
    USER_MOB_DROP_MESO_PICKUP(570),
    USER_BREAK_TIME_FIELD_ENTER(571),

    USER_ZERO_SKILL_COOLTIME_REQUEST(574),
    USER_RUN_ACT_QUEST(570),
    JOURNAL_AVATAR_REQUEST(571),
    REQUEST_EVENT_LIST(573),
    USER_SIGN_REQUEST(574),
    ADD_ATTACK_RESET(575),
    SET_EVENT_NAME_TAG(575),
    USER_AFFECTED_AREA_REMOVE_BY_TIME(578),
    REQUEST_FREE_CHANGE_JOB(579),
    LIBRARY_START_SCRIPT(580),
    CHANNEL_USER_COUNT_REQUEST(581),
    UN_URSUS_SELECTED_SKILL_LIST(582),
    SOUL_DUNGEON_SYS(583),
    USER_COORDINATION_CONTEST_REQUEST(584),
    USER_SOUL_EFFECT_REQUEST(586),
    USER_SPIN_OFF_NEW_MODIFY_REQUEST(587),

    BLACK_LIST(589),
    SKILL_HELPER_POPUP(590),
    BLOCKBUSTER(591),
    M_TALK_OFFLINE_ACCOUNT_FRIENDS_NAME_REQUEST(592),
    CHARACTER_BURNING(592),
    TRY_REGISTER_TELEPORT(593),
    USER_TOWER_CHAIR_SETTING(594),
    BULLET_BARRAGE_DURATION_EXTENSION_REQUEST(595),

    UNION_REQUEST(599),
    GRAND_GUARDIAN_REQUEST(601),
    TRADE_KING_SHOP_INFO_REQ(609),
    KEY_DOWN_SKILL_COST(610),

    USER_REVIVE_REQUEST(614),
    MATRIX_UPDATE_REQUEST(615),

    MATRIX_CRAFT_NODESTONE_REQUEST(618),

    MOD_SPECTRA_ENERGY(620),
    UNK_232_621(621),
    USER_IN_BOSS_REVIVE_REQUEST(622),  // *
    GREATER_DARK_SERVANT_SWAP_REQUEST(623),
    //
    INHUMAN_SPEED_FORCE_ATOM_REQUEST(625),
    //
    CRYSTAL_SKILL_REQUEST(627),
    //
    SPAM_HEADER(632),
    //
    UNK228_643(643),


    B_E_G_I_N__P_E_T(644),
    PET_MOVE(645),
    PET_ACTION(646),
    PET_INTERACTION_REQUEST(647),
    PET_DROP_PICK_UP_REQUEST(648),
    PET_STAT_CHANGE_ITEM_USE_REQUEST(649),
    PET_UPDATE_EXCEPTION_LIST_REQUEST(650),
    PET_FOOD_ITEM_USE_REQUEST(651),
    PET_OPEN_SHOP(652),
    E_N_D__P_E_T(653),

    B_E_G_I_N__S_K_I_L_L_P_E_T(654),
    SKILL_PET_MOVE(655),
    SKILL_PET_ACTION(656),
    SKILL_PET_STATE(657),
    SKILL_PET_DROP_PICK_UP_REQUEST(658),
    SKILL_PET_UPDATE_EXCEPTION_LIST_REQUEST(659),
    E_N_D__S_K_I_L_L_P_E_T(660),

    B_E_G_I_N__S_U_M_M_O_N_E_D(661),
    SUMMONED_MOVE(662),
    SUMMONED_ATTACK(663),
    SUMMONED_HIT(664),
    SUMMONED_SKILL(665),
    SUMMONED_CREATE_SHOOT_OBJ(666),
    SUMMONED_REMOVE(667),
    SUMMONED_ATTACK_PV_P(668),
    SUMMONED_ACTION(669),

    SUMMONED_ACTION_CHANGE_REQUEST(671),
    SUMMONED_ASSIST_ATTACK_DONE(672),
    SUMMONED_INTERACTION_REQUEST(673),

    SUMMONED_SKILL_ATTACK(675),

    SUMMONED_SECOND_ATOM_ATTACK_REQUEST(677),

    E_N_D__S_U_M_M_O_N_E_D(678),

    B_E_G_I_N__D_R_A_G_O_N(678),
    DRAGON_UNK218_668(678),
    DRAGON_UNK218_669(679),
    DRAGON_MOVE(680),
    DRAGON_GLIDE(681),
    E_N_D__D_R_A_G_O_N(682),

    B_E_G_I_N__A_N_D_R_O_I_D(683),
    ANDROID_MOVE(684),
    ANDROID_ACTION_SET(685),
    E_N_D__A_N_D_R_O_I_D(686),

    B_E_G_I_N__F_O_X_M_A_N(687),
    FOX_MAN_MOVE(688),
    FOX_MAN_ACTION_SET_USE_REQUEST(689),
    E_N_D__F_O_X_M_A_N(690),

    QUICKSLOT_KEY_MAPPED_MODIFIED(691),
    PASSIVE_SKILL_INFO_UPDATE(692),
    UPDATE_CLIENT_ENVIRONMENT(693),
    DIRECTION_NODE_COLLISION(696),
    USER_LASER_INFO_FOR_REMOTE(697),
    RETURN_TELEPORT_DEBUFF(698),
    CHECK_PROCESS(699),
    MEMO_IN_GAME_REQUEST(699),
    EGO_EQUIP_GAUGE_COMPLETE_RETURN(700),
    EGO_EQUIP_CREATE_UPGRADE_ITEM(701),
    EGO_EQUIP_CREATE_UPGRADE_ITEM_COST_REQUEST(702),
    EGO_EQUIP_TALK_REQUEST(703),
    EGO_EQUIP_CHECK_UPDATE_ITEM_REQUEST(704),
    INHERITANCE_INFO_REQUEST(705),
    INHERITANCE_UPGRADE_REQUEST(706),
    MIRROR_READING_SELECT_BOOK_REQUEST(707),
    LIKE_POINT(708),
    USER10TH_STREAMING_URL_REQUEST(709),
    USER_UPDATE_MAPLE_TV_SHOW_TIME(710),
    REDUCE_DOT_DAMAGE_BASE_BUFF_REQUEST(711),
    MIRROR_STUDY_COMPLETE(712),

    REQUEST_ARROW_PLATTER_OBJ(715), // *

    USER_TIME_EVENT_UI_OPEN_REQUEST(717),
    USER_TIME_EVENT_RESULT_REQUEST(718),
    USER_TIME_EVENT_COMPLETE_REQUEST(719),
    USER_TIME_EVENT_PASSED_TIME_SET(720),
    INVASION_SETTING_REQUEST(721),
    USER_FIELD_ATTACK_OBJ_REQUEST_BOARDING(722),
    USER_FIELD_ATTACK_OBJ_REQUEST_GET_OFF(723),
    //MONSTER_BATTLE(714),
    BOSS_ARENA_MATCH_REQUEST(724),
    BOSS_ARENA_MIGRATE_REQUEST(725),
    MOB_USER_CONTROL_SKILL_Q_PUSH(726),
    MOB_USER_CONTROL_SKILL_Q_POP(727),
    MOB_USER_CONTROL_SKILL_FORCED_Q_POP(728),
    PARTY_QUEST_RANKING_REQUEST(729),
    ATTENDANCE_EVENT(730),
    ATTENDANCE_EVENT_REWARD_REQ(731),
    UI_ATTENDANCE_GHOST_CHANGE_REQ(732),
    EVENT_UI_REQ(733),
    ATTENDANCE_EVENT_SELECT_REWARD(734),
    UNK_232_734(735),

    USER_SET_CUSTOMIZE_EFFECT(738),  // *
    USER_CUSTOMIZE_EFFECT_ITEM_MODIFY(738),
    USER_GROWTH_HELPER_REQUEST(739),
    USER_CONTENTS_MAP_REQUEST(740),
    USER_TIMER_REQ(741),
    USER_MANNEQUIN(742),
//    USER_BUFFER_FLY_REQ(730),

    USER_RUN_SCRIPT(743),

    USER_NON_TARGET_FORCE_ATOM_ATTACK(745),
    UI_SCRIPT_REQUEST(746),
    CHECK_BOSS_PARTY_BY_SCRIPT(747),
    TIDE_OF_BATTLE_INCREASE_STACK_REQUEST(748),

    MOVE_TO_URSUS_WAITING_FIELD(752),
    MONSTER_COLLECTION_COMPLETE_REWARD_REQ(753),
    MONSTER_COLLECTION_EXPLORE_REQ(754),
    UNK227_748(755),
    BOSS_TELEPORT_REQUEST(756),

    UNK228_758(759),

    UNION_RAID_RETREAT(765),

    STIGMA_DELIVERY_REQUEST(761),

    B_E_G_I_N__E_V_E_N_T__G_R_O_U_P(762),
    INVITATION_ACCEPT_USER(763),
    INVITATION_CANCEL_USER(764),
    EVENT_GROUP_LEAVE(766),
    B_E_G_I_N__E_V_E_N_T__G_R_O_U_P__P_A_C_K_E_T(766),
    E_N_D__E_V_E_N_T__G_R_O_U_P__P_A_C_K_E_T(767),
    E_N_D__E_V_E_N_T__G_R_O_U_P(768),

    B_E_G_I_N__E_V_E_N_T__R_A_N_K_I_N_G(769),
    EVENT_RANKING_OPEN(770),
    EVENT_RANKING_HELP(771),
    E_N_D__E_V_E_N_T__R_A_N_K_I_N_G(772),

    B_E_G_I_N__A_F_R_E_E_C_A_T_V(773),
    AFREECA_TV_BROAD_START(774),
    AFREECA_TV_BROAD_STOP(775),
    E_N_D__A_F_R_E_E_C_A_T_V(776),

    USER_SURVEY_REQUEST(785),
    NPS_INFO(786),
    USER_FLAME_ORB_REQUEST(787),
    USER__SAD_RESULT_UI__CLOSE(788),
    FREE_LOOK_CHANGE_REQUEST(789),
    FREE_LOOK_CHANGE_UI_OPEN_FAILED(790),
    USER_SMART_PHONE_CALL_REQUEST(791),

    USER_JAGUAR_CHANGE_REQUEST(793),
    FPS_LOG(794),
    PACKET_MODIFY_LOG(795),
    BATTLE_USER_AVATAR_SELECT(796),
    BATTLE_USER_ATTACK(797),
    BATTLE_USER_ATTACK_EXPIRE(798),
    BATTLE_USER_ATTACK_POSITION(799),
    BATTLE_USER_HIT(800),
    BATTLE_USER_HIT_BY_MOB(801),
    BATTLE_STAT_CORE_REQUEST(802),
    BATTLE_USER_ALIVE(803),
    USER_CONTENTS_BOOK_REQUEST(804),
    PERFORMANCE_CLIENT_LOGIN(805),
    PERFORMANCE_CLIENT_IN_FIELD(806),
    PING_CHECK_REQUEST__CLIENT_TO_GAME(807),
    PING__CLIENT_TO_GAME(808),
    PLANT_POT_CLICK(809),
    RANDOM_MISSION_REQUEST(810),
    ITEM_COLLECTION_SET_FLAG(811),
    ITEM_COLLECTION_CHECK_COMPLETE(812),
    SELF_STAT_CHANGE_REQUEST(813),
    CASH_BUFF_EVENT_CANCEL(814),

    SURPRISE_MISSION_CLAIM_REWARD_REQUEST(816),

    CREATE_PSYCHIC_LOCK(821),
    RESET_PATH_PSYCHIC_LOCK(822),
    RELEASE_PSYCHIC_LOCK(823),
    RESERVE_DAMAGE_PSYCHIC_LOCK(824),
    CREATE_KINESIS_PSYCHIC_AREA(825),
    DO_ACTIVE_PSYCHIC_AREA(826),
    DEBUFF_PSYCHIC_AREA(827),
    RELEASE_PSYCHIC_AREA(828),
    //
    PSYCHIC_OVER_REQUEST(830),
    DEC_PSYCHIC_POINT_REQUEST(831),
    TOUCH_ME_END_REQUEST(832),
    BITE_ATTACK_RESPONSE(832),
    SAVE_URSUS_SKILL(833),
    GET_SAVED_URSUS_SKILL(834),
    URSUS_SHOP_REQUEST(835),
    URSUS_PARTY_MEMBER_LIST(835),
    USER_KEY_DOWN_STEP_REQUEST(836),
    DAILY_GIFT_REQUEST(837),
    SKILL_COMMAND_LOCK_ARAN(838),
    SKILL_COMMAND_LOCK_ARK(839),
    BEAST_FORM_WING_OFF(840),
    RESET_AIR_HIT_COUNT_REQUEST(841),
    RW_ACTION_CANCEL(843),
    RELEASE_RW_GRAB(844),
    RW_CLEAR_CURRENT_ATTACK_REQUEST(845),
    RW_MULTI_CHARGE_CANCEL_REQUEST(846),
    DIMENSIONAL_MIRROR_WARP_REQUEST(848),
    FUNCTION_FOOTHOLD_MAN(851),

    SHOOT_OBJECT_CREATE_REQUEST(853),

    SHOOT_OBJECT_EXPLODE_REQUEST(856),

    LOADED_DICE_SELECTION_RESULT(861),
    STACK_OVER_TIME_SKILL_INCREASE_REQUEST(862),

    SPOTLIGHT_STACK_REQUEST(864),
    UNION_PRESET_CHANGED(865),

    UNION_ASSIGN_REQUEST(869),
    UNION_PRESET_INFO_REQUEST(870),

    USER_SKILL_INFO(876),
    UNK227_869(877),

    ACHIEVEMENT_REQUEST(879),

    // PROBABLY START 218 SKILLS
    GUIDE_FORCE_ATOM_FOR_REMOTE(881),

    USER_TELEPORT_ROCK_ALLOWED_SETTING_REQUEST(885),

    INCREASE_SKILL_STACK_REQUEST(889),

    ANTI_MACRO_VIOLETTA_RESPONSE(897),
    DIVINE_ECHO_EXPIRE_REQUEST(898),

    SEND_SUMMON_ATTACK_STATE_CHANGE(899),
    UNK227_892(900),
    INFERNO_SPHERE_FEATHER_COUNT(901),

    LARA_STACK_OVER_TIME_SKILL_INCREASE_REQUEST(905),
    BULLET_BLAST_RELOAD_REQUEST(906),

    // Beast Tamer
    BEAST_TAMER_REGROUP_REQUEST(918),
    DEMONIC_BLAST_KEYDOWN_COST(919),

    CLIENT_SYNC_COOLTIME_REQUEST(921),
    V_BLESSING_UPDATE_REQUEST(922),
    AURA_SKILL_UPDATE_REQUEST(923),

    EMOTICON_REQUEST(929),  // *
    GACHAPON_REQUEST(930),

    UNK227_933(935),

    REVENANT_FURY_UPDATE(937),

    JUPITER_THUNDER_CREATE_REQUEST(943),
    JUPITER_THUNDER_UPDATE_REQUEST(944),
    JUPTIER_THUNDER_UNK227_943(945),
    JUPITER_THUNDER_REMOVE_REQUEST(946),
    // END 218 SKILLS

    KAIN_DEATHBLESSING_REQUEST(952),
    KAIN_STACK_OVER_TIME_SKILL_INCREASE_REQUEST(953),

    LARA_DRAGON_VEIN_READING_REQUEST(963),

    FAMILIAR_ADD_REQUEST(985),  // *
    FAMILIAR_SUMMON_REQUEST(986),
    FAMILIAR_CODEX_MODIFY_REQUEST(987),
    FAMILIAR_EDIT_REQUEST(988),
    FAMILIAR_SHOP_OPEN_REQUEST(989),

    GUILD_BBS(1001),

    CASH_SHOP_SURPRISE_ITEM_OPEN(1009),

    FAMILIAR_MOVE(1043),
    FAMILIAR_ATTACK(1044),
    FAMILIAR_SKILL(1045),

    SET_USER_CUSTOM_TITLE_REQUEST(1069),
    UPDATE_USER_CUSTOM_TITLE_REQUEST(1070),
    SLASH_COMMAND(1071),

    E_N_D__U_S_E_R(1075),

    B_E_G_I_N__F_I_E_L_D(1076),
    B_E_G_I_N__L_I_F_E_P_O_O_L(1076),


    B_E_G_I_N__M_O_B(1080),
    MOB_MOVE(1081),
    MOB_APPLY_CTRL(1082),
    MOB_DROP_PICK_UP_REQUEST(1083),
    MOB_HIT_BY_OBSTACLE(1084),
    MOB_HIT_BY_OBSTACLE_ATOM(1085),
    MOB_HIT_BY_MOB(1086),
    MOB_SELF_DESTRUCT(1087),
    MOB_SELF_DESTRUCT_COLLISION_GROUP(1088),

    MOB_ATTACK_MOB(1090),
    MOB_SKILL_DELAY_END(1091),
    MOB_TIME_BOMB_END(1092),
    MOB_ESCORT_COLLISION(1093),
    MOB_REQUEST_ESCORT_INFO(1094),
    MOB_ESCORT_STOP_END_REQUEST(1095),
    MOB_AREA_ATTACK_DISEASE(1096),
    MOB_EXPLOSION_START(1097),
    MOB_LIFTING_END(1098),
    MOB_UPDATE_FIXED_MOVE_DIR(1099),
    MOB_CREATE_FIRE_WALK(1100),
    MOB_AFTER_DEAD_REQUEST(1101),
    MOB_DAMAGE_SHARE_INFO(1102),
    MOB_CREATE_AFFECTED_AREA(1103),
    MOB_DOWN_RESPONSE(1104),
    E_N_D__M_O_B(1105),

    B_E_G_I_N__N_P_C(1119),  // *
    NPC_MOVE(1120),
    NPC_SPECIAL_ACTION(1121),
    E_N_D__N_P_C(1122),
    E_N_D__L_I_F_E_P_O_O_L(1123),

    B_E_G_I_N__D_R_O_P_P_O_O_L(1124),
    DROP_PICK_UP_REQUEST(1125),
    E_N_D__D_R_O_P_P_O_O_L(1126),

    B_E_G_I_N__R_E_A_C_T_O_R_P_O_O_L(1127),
    REACTOR_HIT(1128),
    REACTOR_CLICK(1129),
    REACTOR_RECT_IN_MOB(1130),
    REACTOR_UNK229_1136(1131),
    REACTOR_KEY(1132),
    REACTOR_UNK208_1094(1133),
    //REACTOR_UNK208_1095(1139),
    REACTOR_GATHER(1134),
    E_N_D__R_E_A_C_T_O_R_P_O_O_L(1136),

    B_E_G_I_N__F_I_S_H_I_N_G_Z_O_N_E_P_O_O_L(1137),
    FISHING_INFO(1138),
    FISHING_END(1139),
    E_N_D__F_I_S_H_I_N_G_Z_O_N_E_P_O_O_L(1140),

    B_E_G_I_N__P_E_R_S_O_N_A_L__O_B_J_E_C_T(1141),
    DECOMPOSER_REQUEST(1142),
    E_N_D__P_E_R_S_O_N_A_L__O_B_J_E_C_T(1143),

    B_E_G_I_N__E_V_E_N_T__F_I_E_L_D(1144),
    EVENT_START(1145),
    SNOW_BALL_HIT(1146),
    SNOW_BALL_TOUCH(1147),
    COCONUT_HIT(1148),
    TOURNAMENT_MATCH_TABLE(1149),
    PULLEY_HIT(1150),
    E_N_D__E_V_E_N_T__F_I_E_L_D(1151),

    B_E_G_I_N__M_O_N_S_T_E_R__C_A_R_N_I_V_A_L__F_I_E_L_D(1152),
    M_CARNIVAL_REQUEST(1153),
    E_N_D__M_O_N_S_T_E_R__C_A_R_N_I_V_A_L__F_I_E_L_D(1154),

    B_E_G_I_N__D_E_F_E_N_S_E__F_I_E_L_D(1155),
    DEFENSE_GAME_REQUEST(1156),
    E_N_D__D_E_F_E_N_S_E__F_I_E_L_D(1157),

    C_O_N_T_I_S_T_A_T_E(1169),

    B_E_G_I_N__P_A_R_T_Y__M_A_T_C_H(1170),
    INVITE_PARTY_MATCH(1171),
    CANCEL_INVITE_PARTY_MATCH(1172),
    PARTY_MEMBER_CANDIDATE_REQUEST(1173),
    URSUS_PARTY_MEMBER_CANDIDATE_REQUEST(1174),
    PARTY_CANDIDATE_REQUEST(1175),
    INTRUSION_FRIEND_CANDIDATE_REQUEST(1176),
    INTRUSION_LOBBY_CANDIDATE_REQUEST(1177),
    E_N_D__P_A_R_T_Y__M_A_T_C_H(1178),

    REQUEST_FOOT_HOLD_MOVE(1180),
    GATHER_REQUEST(1181),
    GATHER_END_NOTICE(1182),
    UNK221_1143(1183),
    ACT_CHANGE_REACTOR_USE_REQUST(1184),
    USER_ANTI_MACRO_BOMB_REQUEST(1185),
    MAKE_ENTER_FIELD_PACKET_FOR_QUICK_MOVE(1186),
    RUNE_STONE_USE_REQ(1187),
    RUNE_STONE_END_NOTICE(1188),
    RUNE_STONE_ARROW_INPUT(1189),
    OBSTACLE_ATOM_COLLISION(1190),
    TIMER_GAUGE_TIMEOUT(1191),
    FALLING_CATCHER_HACK_CHECK(1192),
    COOK_GAME_REQUEST(1193),
    FPS_MODE_EXIT_REQUEST(1194),
    MAKE_ENTER_FIELD_PACKET_FOR_MIRROR_DUNGEON(1195),
    LEAVE_MIRROR_DUNGEON(1196),
    PEACEMAKER_TRAVEL_CONTACT_COUNT(1197),
    PEACEMAKER_EXPLOSION_CONTACT_COUNT(1198),

    ILLIUM_RESONANCE_LINK(1202),


    B_E_G_I_N__R_H_Y_T_H_M_G_A_M_E(1194),
    RHYTHM_GAME_HIT_NOTE(1195),
    RHYTHM_GAME_START_REGION(1196),
    //RHYTHM_GAME_END_REGION(1134),
    //RHYTHM_GAME_END_SPECIAL_ATTACK(1135),

    //RHYTHM_GAME_SELECT_MODE(1104),
    //RHYTHM_GAME_ATTACK_REQUEST(1105),
    RHYTHM_GAME_NPC_ACTION_REQUEST(1201),
    //RHYTHM_GAME_EXIT_GAME(1119),
    E_N_D__R_H_Y_T_H_M_G_A_M_E(1203),

    B_E_G_I_N__M_O_U_N_T_A_I_N_R_I_D_I_N_G(1204),
    MOUNTAIN_RIDING_HP_INFO(1205),
    MOUNTAIN_RIDING_MOB_INFO(1206),
    E_N_D__M_O_U_N_T_A_I_N_R_I_D_I_N_G(1207),

    B_E_G_I_N__P_I_R_A_N_H_A(1208),
    PIRANHA_INFO(1209),
    PIRANHA_DIE(1210),
    PIRANHA_DAMAGE(1211),
    PIRANHA_PREPARE(1212),
    E_N_D__P_I_R_A_N_H_A(1213),

    B_E_G_I_N__R_O_B_B_I_N_S(1214),
    ROBBINS__INC_BOMB(1215),
    ROBBINS__DEC_BOMB(1216),
    ROBBINS__TOSS_BOMB(1217),
    E_N_D__R_O_B_B_I_N_S(1218),

    B_E_G_I_N__F_A_L_L_I_N_G_S_T_O_N_E(1219),
    FALLING_STONE_INFO(1220),
    FALLING_STONE_HP_INFO(1221),
    FALLING_STONE_PREPARE(1222),
    E_N_D__F_A_L_L_I_N_G_S_T_O_N_E(1223),

    B_E_G_I_N__B_A_T_T_L_E_F_I_E_L_D(1224),
    BATTLE_FIELD_DAMAGE(1225),
    BATTLE_FIELD_SHEEP_REVIVAL_REQ(1226),
    BATTLE_FIELD_SHEEP_REVIVE(1227),
    E_N_D__B_A_T_T_L_E_F_I_E_L_D(1228),

    B_E_G_I_N__B_O_S_S_A_R_E_N_A(1229),
    BOSS_ARENA_SELECT_BOSS(1230),
    BOSS_ARENA_SELECT_SKILL(1231),
    BOSS_ARENA_SELECT_DIFFICULTY(1232),
    BOSS_ARENA_SELECT_CONFIRM(1233),
    E_N_D__B_O_S_S_A_R_E_N_A(1234),

    B_E_G_I_N__C_A_T_A_P_U_L_T(1235),
    CATAPULT__UPGRADE_SKILL(1236),
    E_N_D__C_A_T_A_P_U_L_T(1237),

    FIELD_ATTACK_OBJ_PUSH_ACT(1238),
    FIELD_RESPAWN(1239),

    B_E_G_I_N__S_O_U_L__D_U_N_G_E_O_N(1240),
    SOUL_ITEM_USE(1241),
    SOUL_ITEM_USE_VOTE(1242),
    SOUL_DUNGEON_SUMM_SOUL_BOSS(1243),
    E_N_D__S_O_U_L__D_U_N_G_E_O_N(1244),

    B_E_G_I_N__S_P_A_C_E_M_O_O_N_R_A_B_B_I_T(1245),
    SPACE_MOON_RABBIT_HIT_EFF(1246),
    SPACE_MOON_RABBIT_DAMAGE(1247),
    E_N_D__S_P_A_C_E_M_O_O_N_R_A_B_B_I_T(1248),

    B_E_G_I_N__H_U_N_D_R_E_D_B_I_N_G_O(1249),
    H_BINGO_CHECK_NUMBER(1250),
    H_BINGO_CHECK_BINGO(1251),
    E_N_D__H_U_N_D_R_E_D_B_I_N_G_O(1252),

    B_E_G_I_N__T_Y_P_I_N_G_G_A_M_E(1253),
    TYPING_GAME_CHECK_MSG(1254),
    TYPING_GAME_WORD_MOB_ATTACK(1255),
    TYPING_GAME_LEVEL_SELECT(1256),
    TYPING_GAME_SKILL_ATTACK(1257),
    TYPING_GAME_FIELD_OUT(1258),
    E_N_D__T_Y_P_I_N_G_G_A_M_E(1259),

    B_E_G_I_N__H_U_N_D_R_E_D_O_X_Q_UI_Z(1260),
    H_OX_QUIZ_SELECTED(1261),
    E_N_D__H_U_N_D_R_E_D_O_X_Q_UI_Z(1262),

    B_E_G_I_N__S_T_A_R_P_L_A_N_E_T_R_P_S(1263),
    S_P_RPS_GAME_USER_SELECT(1264),
    S_P_RPS_GAME_ANSWER(1265),
    S_P_RPS_GAME_LEAVE(1266),
    E_N_D__S_T_A_R_P_L_A_N_E_T_R_P_S(1267),

    B_E_G_I_N__S_I_D_E_S_C_R_O_L_L_F_L_Y_S_H_O_O_T_I_N_G(1268),
    SSFS_HIT_USER(1269),
    SSFS_LETHAL_ATTACK(1270),
    SSFS_EXIT(1271),
    E_N_D__S_I_D_E_S_C_R_O_L_L_F_L_Y_S_H_O_O_T_I_N_G(1272),

    B_E_G_I_N__G_H_O_S_T_P_A_R_K(1273),
    GHOST_PARK_USE_RUNE_REQ(1274),
    GHOST_PARK_RUNE_HEAL_REQ(1275),
    GHOST_PARK_HIT_BULLET(1276),
    E_N_D__G_H_O_S_T_P_A_R_K(1277),

    B_E_G_I_N__F_I_E_L_D__U_R_U_S(1278),
    URSUS_SAVE_DEADLY_USER(1279),
    E_N_D__F_I_E_L_D__U_R_U_S(1280),

    FIELD_SKILL_USE_REQUEST(1281),
    FIELD_WEATHER_MSG(1282),
    FIELD_STAT_QR_EX_DAY(1283),

    B_E_G_I_N__P_O_L_O_F_R_I_T_O_B_O_U_N_T_Y_H_U_N_T_I_N_G(1284),
    POLO_FRITO_BOUNTY_HUNTING_REQUEST(1285),
    RAIL_RUSH_END_REQUEST(1286),
    E_N_D__P_O_L_O_F_R_I_T_O_B_O_U_N_T_Y_H_U_N_T_I_N_G(1287),

    B_E_G_I_N__P_O_L_O_F_R_I_T_O_T_O_W_N_D_E_F_E_N_S_E(1287),
    POLO_FRITO_TOWN_DEFENSE_REQUEST(1288),
    E_N_D__P_O_L_O_F_R_I_T_O_T_O_W_N_D_E_F_E_N_S_E(1289),

    B_E_G_I_N__P_O_L_O_F_R_I_T_O_C_O_U_R_T_S_H_I_P_D_A_N_C_E(1318),
    POLLO_FRITTO_COURTSHIP_DANCE_RESULT(1319),
    E_N_D__P_O_L_O_F_R_I_T_O_C_O_U_R_T_S_H_I_P_D_A_N_C_E(1320),

    VERUS_HILLA_SOUL_ALTAR_REQUEST(1290),

    LOTUS_FOOTHOLD_OBJECT_FALL_ACK(1292),

    B_E_G_I_N__B_O_S_S__D_E_M_I_A_N__F_L_Y_I_N_G_S_W_O_R_D(1321),
    DEMIAN_OBJECT_MAKE_ENTER_ACK(1322),
    DEMIAN_OBJECT_NODE_END(1323),
    DEMIAN_OBJECT_ERR__RECREATE(1324),
    E_N_D__B_O_S_S__D_E_M_I_A_N__F_L_Y_I_N_G_S_W_O_R_D(1325),
    E_N_D__F_I_E_L_D(1301),

    // Lucid begins here somewhere
    LUCID_UNK212_1302(1327),
    LUCID_UNK212_1303(1328),
    LUCID_WELCOME_BARRAGE_END_REQUEST(1329),

    CHECK_S_P_W_CREATE_NEW_CHARACTER(1317),
    SET_S_P_W(1318),

    PAPULATUS_LASER_TOUCH(1334),
    PAPULATUS_TWEEZER_GRAB(1335),
    PAPULATUS_TWEEZER_RELEASE(1336),

    WILL_INFECTION_HIT(1340),

    // Castle Column
    CASTLE_COLUMN_PLACE(1345),
    CASTLE_COLUMN_PLACE_2(1346),
    CASTLE_COLUMN_RETREAT(1347),
    // Castle Column

    // Will begins here somewhere
    WILL_MOONLIGHT_REQUEST(1370), // *
    WILL_EYE_ORB_HIT(1371),
    WILL_WEB_HIT(1372),

    B_E_G_I_N__B_L_A_C_K__M_A_G_E(1402),
    BLACK_MAGE_ORB_HIT(1403),
    E_N_D__B_L_A_C_K__M_A_G_E(1404),

    MONSTER_PYRAMID_REQUEST(1427),

    USER_SECOND_ATOM_COMMAND_REQUEST(1444),
    USER_SECOND_ATOM_REMOVE_REQUEST(1445),
    USER_SECOND_ATOM_COLLISION_REQUEST(1446),

    GOLLUX_MINI_MAP_UPDATE_REQUEST(1476),
    GOLLUX_UNK223_1419(1477),
    GOLLUX_MINI_MAP_LEAVE_REQUEST(1478),

    VOYAGE_COMPLETE_REQUEST(1480),

    B_E_G_I_N__C_A_S_H_S_H_O_P(1511),  // *
    CASH_SHOP_CHARGE_PARAM_REQUEST(1512),
    CASH_SHOP_QUERY_CASH_REQUEST(1513),
    CASH_SHOP_CASH_ITEM_REQUEST(1514),
    CASH_SHOP_CHECK_COUPON_REQUEST(1515),
    CASH_SHOP_MEMBER_SHOP_REQUEST(1517),
    CASH_SHOP_GIFT_MATE_INFO_REQUEST(1518),
    CASH_SHOP_SEARCH_LOG(1519),
    CASH_SHOP_COODINATION_REQUEST(1520),
    CASH_SHOP_CHECK_MILEAGE_REQUEST(1521),
    CASH_SHOP_NAVER_USAGE_INFO_REQUEST(1522),
    MVP_DAILY_PACK_REQUEST(1523),
    MVP_SPECIAL_PACK_REQUEST(1524),

    CASH_SHOP_ACTION(1529),
    CASH_SHOP_BUTTON_PRESS(1530),
    E_N_D__C_A_S_H_S_H_O_P(1531),

    UNK216_1471(1532),
    UNK227_1500(1533),

    B_E_G_I_N__R_A_I_S_E(1536),
    RAISE_REFRESH(1537),
    RAISE_UI_STATE(1538),
    RAISE_INC_EXP(1539),
    RAISE_ADD_PIECE(1540),
    E_N_D__R_A_I_S_E(1541),

    SEND_MATE_MAIL(1542),
    REQUEST_GUILD_BOARD_AUTH_KEY(1543),
    REQUEST_CONSULT_AUTH_KEY(1544),
    REQUEST_CLASS_COMPETITION_AUTH_KEY(1545),
    REQUEST_WEB_BOARD_AUTH_KEY(1546),
    IRBOX_EVENT(1547),

    B_E_G_I_N__I_T_E_M_U_P_G_R_A_D_E(1547),  // *
    GOLD_HAMMER_REQUEST(1548),
    GOLD_HAMMER_COMPLETE(1549),
    E_N_D__I_T_E_M_U_P_G_R_A_D_E(1550),

    B_E_G_I_N__B_A_T_T_L_E_R_E_C_O_R_D(1553),
    BATTLE_RECORD_ON_OFF_REQUEST(1554),
    BATTLE_RECORD_SKILL_DAMAGE_LOG(1555),
    E_N_D__B_A_T_T_L_E_R_E_C_O_R_D(1556),

    B_E_G_I_N__F_A_R_M(1575),
    INSERT_FARM_OBJECT(1576),
    DELETE_FARM_OBJECT(1577),
    INSERT_FARM_TILE(1578),
    DELETE_FARM_TILE(1579),
    TRANSFER_FARM_FIELD(1580),
    BUY_FARM_OBJECT(1581),
    SEL_FARM_OBJECT(1582),
    MY_HOUSE_UPGRADE(1582),
    FARM_ADMIN_COMMAND(1583),
    REQUEST_QUEST_COMPLETE(1584),
    CHECK_FARM_NAME(1585),
    REQUEST_INTERACT_OBJECT(1586),
    REQUEST_CONSUME_OBJECT(1587),
    REQUEST_CLICK_NPC(1588),
    REQUEST_RANDOM_FARM(1589),
    REQUEST_FARM_VISIT(1590),
    REQUEST_ADD_FARM_FRIEND(1591),
    FARM_IN_GAME_FRIEND_REQUEST(1592),
    REQUEST_DELETE_FARM_FRIEND(1593),
    REQUEST_ADD_BLACK_LIST(1594),
    REQUEST_DELETE_BLACK_LIST(1595),
    UNK228_1604(1596),
    REQUEST_FARM_INFO_UI(1597),
    CHECK_FARM_NAME_BY_CONSUME(1598),
    REQUEST_AUTO_HARVEST(1599),
    REQUEST_SOUL_RECHARGE(1600),
    REQUEST_TRANSFER_FARM_BY_NAME(1601),
    MY_FARM_MONSTER_REQUEST(1602),
    FARM_MONSTER_COMBINE(1603),
    FARM_MONSTER_SET_NAME_REQUEST(1604),
    FARM_MONSTER_CARE(1605),
    FARM_MONSTER_PLAY(1606),
    FARM_MONSTER_RELEASE(1607),
    FARM_MONSTER_SEARCH_REQUEST(1608),
    FARM_MONSTER_POS_RECODE(1609),
    // FARM_MONSTER_LOCKER_REQUEST(1618),
    FARM_MONSTER_LIFE_EXTEND(1611),
    PHOTO_UPDATE(1612),
    PHOTO_GET_REQUEST(1613),
    MY_HOME_SEND_NOTICE_REQUEST(1612),
    MY_HOME_LOAD_MAIN_LOG_REQUEST(1613),
    MY_HOME_DELETE_LOG_REQUEST(1614),
    FARM_WHISPER(1615),
    FARM_GROUP_MESSAGE(1616),

    WORLD_MAP_BOOKMARK_UPDATE_REQUEST(1610),

    XENON_CORE_INC_REQUEST(1618), // *
    REQUEST_FARM_FRIEND_RECOMMEND(1619),
    FARM_REQUEST_IN_GAME_INFO_SET(1620),
    FARM_REQUEST_IN_GAME_INFO_MOD(1621),
    REQUEST_FARM_FRIEND_INFO(1622),
    REQUEST_FARM_TODAY(1623),
    REQUEST_FIRST_ENTER_REWARD(1627),
    UNK227_1591(1628),
    CHECK_ADMIN_ACCOUNT_LOG(1629),
    E_N_D__F_A_R_M(1630),


    CHARACTER_LIST_REQUEST(1629),
    COPY_CHARACTER_TO_TEST_REQUEST(1629),

    VOYAGE_REQUEST(1630),

    REWARD_REQUEST(1641),

    CASH_SHOP_TUTORIAL_DONE(1655),

    NO(1664),
    ;

    private static List<InHeader> spam = Arrays.asList(
            UPDATE_CLIENT_ENVIRONMENT,
            WVS_SET_UP_STEP,
            SECURITY_PACKET,
            PRIVATE_SERVER_PACKET,
            MOB_MOVE,
            USER_MOVE,
            USER_HIT,
            USER_EMOTION,
            PASSIVE_SKILL_INFO_UPDATE,
            USER_CHANGE_STAT_REQUEST,
            SUMMONED_MOVE,
            USER_TEMPORARY_STAT_UPDATE_REQUEST,
            USER_CALC_DAMAGE_STAT_SET_REQUEST,
            MOB_APPLY_CTRL,
            USER_REQUEST_INSTANCE_TABLE,
            USER_QUEST_REQUEST,
            CHECK_LOGIN_AUTH_INFO,
            NPC_MOVE,
            FAMILIAR_MOVE,
            PET_MOVE,
            ALIVE_ACK,
            OBSTACLE_ATOM_COLLISION,
            USER_COMPLETE_COMBO_KILL_COUNT_CHECK,
            USER_COMPLETE_MULTI_KILL_COUNT_CHECK,
            USER_COMPLETE_MULTI_KILL_CHECK,
            USER_CHAT,
            XENON_CORE_OVERLOAD,
            MOB_SKILL_DELAY_END,
            ANDROID_MOVE,
            DRAGON_MOVE,
            STACK_OVER_TIME_SKILL_INCREASE_REQUEST,
            MOD_SPECTRA_ENERGY,
            MOB_LIFTING_END,
            SKILL_PET_MOVE,
            MY_HOME_DELETE_LOG_REQUEST,
            INFERNO_SPHERE_FEATHER_COUNT,
            FOX_MAN_MOVE,
            SPAM_HEADER,
            EGO_EQUIP_CREATE_UPGRADE_ITEM_COST_REQUEST,
            USER_WIND_ENERGY_REQUEST,
            FARM_REQUEST_IN_GAME_INFO_SET,
            USER_TIMER_REQ
    );

    private short value;
    private final static Map<Short, InHeader> opToHeaderMap = new HashMap<>();

    static {
        for (InHeader ih : values()) {
            opToHeaderMap.put(ih.getValue(), ih);
        }
    }

    InHeader(int op) {
        this.value = (short) op;
    }

    public short getValue() {
        return value;
    }

    public static InHeader getInHeaderByOp(int op) {
        return opToHeaderMap.getOrDefault((short) op, null);
    }

    public static boolean isSpamHeader(InHeader inHeaderByOp) {
        return spam.contains(inHeaderByOp);
    }

    public boolean isAlwaysShowExceptions() {
        switch (this) {
            case USER_TRANSFER_CHANNEL_REQUEST:
            case MIGRATE_IN:
            case CREATE_NEW_CHARACTER:
            case DELETE_CHARACTER:
            case CHECK_SPW_REQUEST:
            case SELECT_WORLD:
            case USER_CHARACTER_INFO_REQUEST:
                return true;
        }
        return false;
    }

    public boolean isIgnoreShowExceptions() {
        switch (this) {
            case USER_MELEE_ATTACK:
            case USER_SHOOT_ATTACK:
            case USER_MAGIC_ATTACK:
            case SUMMONED_HIT:
            case SUMMONED_ATTACK:
            case MOB_MOVE:
            case USER_MOVE:
            case USER_FORCE_ATOM_COLLISION:
                return true;
        }
        return false;
    }

    public static void main(String[] args) {
        File file = new File(ServerConstants.DIR + "\\src\\main\\java\\net\\swordie\\ms\\handlers\\header\\InHeader.java");
        int change = -2;
        InHeader checkOp = null;
        try (Scanner s = new Scanner(file)) {
            while (s.hasNextLine()) {
                String line = s.nextLine();
                if (line.contains(",") && line.contains("(")) {
                    String[] split = line.split("[()]");
                    String name = split[0];
                    if (!Util.isNumber(split[1])) {
                        System.out.println(line);
                        continue;
                    }
                    int val = Integer.parseInt(split[1]);
                    InHeader ih = Arrays.stream(InHeader.values()).filter(o -> o.toString().equals(name.trim())).findFirst().orElse(null);
                    if (ih != null) {
                        InHeader start = B_E_G_I_N__C_A_S_H_S_H_O_P;
                        if (ih.ordinal() >= start.ordinal() && ih.ordinal() < B_E_G_I_N__I_T_E_M_U_P_G_R_A_D_E.ordinal()) {
                            if (line.contains("*")) {
                                checkOp = ih;
                            }
                            val += change;
                            System.out.println(String.format("%s(%d), %s", name, val, start == ih ? " // *" : ""));
                        } else {
                            System.out.println(line);
                        }
                    } else {
                        System.out.println(line);
                    }
                } else {
                    System.out.println(line);
                }
            }
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
        if (checkOp != null) {
            System.err.println(String.format("Current op (%s) contains a * (= updated). Be sure to check for overlap.", checkOp));
        }
    }
}
