package net.swordie.ms;

/**
 * Created on 2/18/2017.
 */
public class ServerConstants {
	public static final String DIR = System.getProperty("user.dir");
	public static final byte LOCALE = 8;
	public static final String BAT_DIR = DIR + "/bat";
	public static final String WZ_DIR = DIR + "/wz";
	public static final String DAT_DIR = DIR + "/dat";
	public static final String LOG_DIR = DIR + "/logs";
	public static final String SQL_DIR = DIR + "/sql";
	public static final String LOADINS_DIR = DIR + "/loadins";
	public static final int MAX_CHARACTERS = 54;
	public static final String SCRIPT_DIR = DIR + "/scripts";
	public static final String RESOURCES_DIR = DIR + "/resources";
	public static final String HANDLERS_DIR = DIR + "/src/main/java/net/swordie/ms/handlers";
	public static final String BASE_API_PATH = "/api";
	public static final short VERSION = 232;
	public static final short VERSION_FOR_WZ = 777;
	public static final String MINOR_VERSION = "2";
	public static final int LOGIN_PORT = 8484;
	public static final int CLIENT_API_PORT = 8483;
	public static final int WEB_API_PORT = 3000; // Gets proxied via nginx
	public static final short CHAT_PORT = 0;
	public static final int BCRYPT_ITERATIONS = 5;
	public static final long TOKEN_EXPIRY_TIME = 60 * 24; // 24h
	public static final long CLEAR_CACHE_RATE = 4; // 24h
	public static boolean CHECK_WZ_ON_LOGIN = false;

	// Tespia
	public static final boolean IS_TESPIA = false; // set true if Tespia instance of server.
	public static final String SCRIPT_DIR_TESPIA = SCRIPT_DIR + "_tespia";

    public static final byte[] WZ_HASH = new byte[]{
			(byte) 0x75,
			(byte) 0x8D,
			(byte) 0xCC,
			(byte) 0x19,
			(byte) 0xDA,
			(byte) 0xE2,
			(byte) 0x21,
			(byte) 0x8E,
			(byte) 0xDD,
			(byte) 0x66,
			(byte) 0xA2,
			(byte) 0x36,
			(byte) 0xD4,
			(byte) 0xF5,
			(byte) 0x64,
			(byte) 0x10,
	}; // generated by SHA1
}
