package net.swordie.ms.client.character.achievement;

public enum AchievementCheckValueType {
    date,
    mob,
    quest_change_info,
    suddenmission_clear_time,
    meso,
    fieldset,
    object_template_id,
    hit_damage_percent,
    character,
    rune_stone_id,
    nc_stat_type,
    skill,
    spell_trace_enchant,
    quest_id,
    ability,
    combokill_count,
    item,
    multikill_count,
    makingskill_result,
    item_reward,
    achievement_change_info,
    enchant_result,
    skill_use,
    field,
    npc_id,
    starforce_enchant,
    skill_id,
}
