package net.swordie.ms.client.character.achievement;

public enum AchievementType {
    mob_kill,
    makingskill_making,
    quest_state_change,
    pickup_mob_reward_item,
    ability_change,
    starforce_enchant,
    npcshop_buy,
    spell_trace_enchant,
    script,
    field_enter,
    combokill_get_marble,
    master_piece_success,
    nc_stat_level_up,
    quest_qrex_change,
    user_lvup,
    makingskill_lvup,
    dailygift_get_reward,
    user_hit,
    guild_commitment_inc,
    nc_stat_exp_up,
    combokill_increse,
    multikill,
    suddenmission_reward,
    rune_stone_use_result_success,
    makingskill_synthesize,
    suddenmission_complete,
    makingskill_fatigue_inc,
    makingskill_gather,
    makingskill_decomposition,
    pickup_mob_reward_meso,
    achievement_state_change,
    field_attack_obj_use,
    pickup_reactor_reward_item,
    guild_attend_check,
    item_use,

}
