# Burke, Jett 4th job, 552000074
sm.setSpeakerID(9270090)
sm.sendNext("You are lucky I need you alive for a few moments longer to unlock the #rcore's power#k.")
sm.chatScript("Baroq sealed off the entrance with a powerful magic barrier!")
sm.removeNpc(9270090)
sm.setSpeakerID(9270092)
sm.sendNext("Y-you gotta go. Get out of here and let me rot...")
sm.setPlayerAsSpeaker()
sm.sendNext("#p9270092# you yellow-bellied toad, get on your feet and get movin!")
sm.setSpeakerID(9270092)
sm.sendNext("I... wanted your power... I wanted to be special like you.")
sm.sendNext("I couldn't see past the offer the Black Wings gave me, and they played me like a two-buck fiddle. They knew everything about the core.")
sm.sendNext("They knew the only way to get you this far into space was with a big scandal. That king didn't have anything to do with anything... just a pawn in their plan. All they cared about was getting the #bcore#k to Maple World.. and into their hands.")
sm.setPlayerAsSpeaker()
sm.sendNext("You knew I was the only one that could use the #bcore's power#k. .. Why'd you let me live?")
sm.setSpeakerID(9270092)
sm.sendNext("I hated your power, not you.")
sm.sendNext("These scumbags found out you could use the #bcore#k and they were gonna make you their slave... I tried to stop them... Don't.. let it... go to waste...")
sm.sendNext("*Cough*")
sm.sendNext("*Cough* I was hopin' to get back home once... before I kicked the bucket... I wanted to go back... to the way things used to be... when all we needed was... each other.. *Cough*")
sm.setPlayerAsSpeaker()
sm.sendNext("I'm gonna get you out of here!")
sm.setSpeakerID(9270092)
sm.sendNext("I... hid the real core at #b#m240010300##k They'll figure it out soon. You... you gotta get a move on!")
sm.sendNext("#rit ain't gonna end like this!")
sm.sendNext("I... won't... let them... get the #bcore#k! No matter what it takes!")
sm.completeQuest(53252)
sm.startQuest(53253)
sm.warp(240000000)